### ISSUE TITLE
Error occurred when executing KSampler:  CUDA error: out of memory CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by KillyTheNetTerminal** [patientx/ComfyUI-Zluda#10]
![image](https://github.com/patientx/ComfyUI-Zluda/assets/120438550/1feae00f-ca99-4414-a7af-8aff6a85b6cf)
this error in very simple workflow (RX580)

**Comment by patientx** [comment]
sorry but your gpu (rx480-580 and variants) have a few problems that can't be solved at the moment, there is a potential fix (downgrading to a certain version of torch) but can't promise you a fix , you can try this :

open cmd , go to comfyui-zluda directory

run these one by one :

'venv\scripts\activate'
'pip uninstall torch torchvision torchaudio -y'
'pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu118'
patchzluda.bat

these will uninstall latest versions of torch-torchvision-torchaudio and install the last known torch versions that work with rx 580 (but it has been sometime and I can't promise you these old versions will work with latest comfyui)

**Comment by KillyTheNetTerminal** [comment]
Thanks for help 
I'm trying:
![image](https://github.com/patientx/ComfyUI-Zluda/assets/120438550/9f827f36-6381-450d-b14d-0e6a8bd559bd)
the first generated image is very slow?

**Comment by KillyTheNetTerminal** [comment]
![image](https://github.com/patientx/ComfyUI-Zluda/assets/120438550/7565e1a0-b158-499d-9454-1201ae381009)

**Comment by KillyTheNetTerminal** [comment]
![image](https://github.com/patientx/ComfyUI-Zluda/assets/120438550/a702172e-432a-4fc2-8e50-f779142a4808)

![image](https://github.com/patientx/ComfyUI-Zluda/assets/120438550/47688244-b4c3-490d-8995-4eeca5dcdb52)

**Comment by patientx** [comment]
did you read the "readme" , zluda 1st gen is building a database for future use, it only happens when you change torch / zluda , and some different model types but only time.

**Comment by KillyTheNetTerminal** [comment]
![image](https://github.com/patientx/ComfyUI-Zluda/assets/120438550/f23a919b-266a-4c6c-9f2e-0d97a0bc8224)
Yes, apparently it has been solved, although the program crashes several times until I insist and it works, it is a bit strange. I'm testing extensions

**Comment by KillyTheNetTerminal** [comment]
I'll see how it goes, I really wanted to use this to go faster and second, to try to use some extensions that use Cuda

**Comment by patientx** [comment]
try the deepcache workflow I posted , it gives a bit more speed -although it is sdxl only-

**Comment by KillyTheNetTerminal** [comment]
thanks, what is "Deepcache"?

**Comment by patientx** [comment]
load that workflow, there is explanation inside.
