### ISSUE TITLE
The specified module could not be found. Error loading "C:\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\cudnn64_9.dll" or one of its dependencies

### ISSUE THREAD

**Issue by Lezad** [patientx/ComfyUI-Zluda#139]
### Your question

Attempted to use install-n.bat, but encounter this error upon setup completion. 
I have tried deleting and letting it create a fresh environment, but this did not resolve the issue.
The regular install.bat works fine. 

### Logs

```powershell
---------------------------------------------------------------
* COMFYUI-ZLUDA INSTALL (for HIP 6.2.4 with MIOPEN and Triton)*
---------------------------------------------------------------

 ::  12:46:43  ::  - Setting up the virtual enviroment
 ::  12:46:43  ::  - Virtual enviroment activation
 ::  12:46:43  ::  - Updating the pip package

 ::  12:46:44  ::  Beginning installation ...

 ::  12:46:44  ::  - Installing required packages
 ::  12:46:45  ::  - Installing torch for AMD GPUs (First file is 2.7 GB, please be patient)
 ::  12:47:47  ::  - Installing onnxruntime (required by some nodes)
 ::  12:47:48  ::  - (temporary numpy fix)
 ::  12:47:53  ::  - Detecting Python version and installing appropriate triton package
 ::  12:47:53  ::  - Python 3.11 detected, installing triton for 3.11
 ::  12:47:55  ::  - Installing flash-attention
 ::  12:47:57  ::  - Patching sage-attention
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.

 ::  12:47:57  ::  Custom node(s) installation ...

 ::  12:47:57  ::  - Installing Comfyui Manager
fatal: destination path 'ComfyUI-Manager' already exists and is not an empty directory.
 ::  12:47:57  ::  - Installing ComfyUI-deepcache
fatal: destination path 'ComfyUI-deepcache' already exists and is not an empty directory.

 ::  12:47:57  ::  - Patching ZLUDA
 ::  12:47:58  ::  - ZLUDA patched for HIP SDK 6.2.4 with miopen and triton-flash attention.

.....................................................
*** Installation is completed in 00:01:14.40 .
*** You can use "comfyui-n.bat" to start the app later.
*** It is advised to make a copy of "comfyui-n.bat" and modify it to your liking so when updating later it won't cause problems.
*** You can use -- "--use-pytorch-cross-attention" , "--use-quad-cross-attention" , "--use-flash-attention" or "--use-sage-attention"
.....................................................

*** Starting the Comfyui-ZLUDA for the first time, please be patient...

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-05-15 12:47:59.905
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: C:\ComfyUI-Zluda
** ComfyUI Base Folder Path: C:\ComfyUI-Zluda
** User directory: C:\ComfyUI-Zluda\user
** ComfyUI-Manager config path: C:\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: C:\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   2.2 seconds: C:\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "C:\ComfyUI-Zluda\main.py", line 135, in <module>
    import comfy.utils
  File "C:\ComfyUI-Zluda\comfy\utils.py", line 20, in <module>
    import torch
  File "C:\ComfyUI-Zluda\venv\Lib\site-packages\torch\__init__.py", line 270, in <module>
    _load_dll_libraries()
  File "C:\ComfyUI-Zluda\venv\Lib\site-packages\torch\__init__.py", line 266, in _load_dll_libraries
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\cudnn64_9.dll" or one of its dependencies.
```

### Other

Tried this as well https://github.com/patientx/ComfyUI-Zluda/issues/69#issuecomment-2798949128 to replace the files but to no avail. 

5700X/7900XT

**Comment by patientx** [comment]
Do not change comfyui-zluda directory name, use the original. That could cause these

**Comment by goldenalexeysky** [comment]
> Do not change comfyui-zluda directory name, use the original. That could cause these


The error is the same; I used the standard repository cloning command without changing the directory name:

git clone https://github.com/patientx/ComfyUI-Zluda



Traceback (most recent call last):
  File "D:\Comfy\ComfyUI-Zluda\main.py", line 135, in <module>
    import comfy.utils
  File "D:\Comfy\ComfyUI-Zluda\comfy\utils.py", line 20, in <module>
    import torch
  File "D:\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\__init__.py", line 270, in <module>
    _load_dll_libraries()
  File "D:\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\__init__.py", line 266, in _load_dll_libraries
    raise err
OSError: [WinError 126] Не найден указанный модуль. Error loading "D:\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\lib\cudnn64_9.dll" or one of its dependencies.

**Comment by Lezad** [comment]
> Do not change comfyui-zluda directory name, use the original. That could cause these

It's the default, as shown in the log:
`ComfyUI Path: C:\ComfyUI-Zluda`

**Comment by UnsexSituation** [comment]
Can confirm I am also experiencing this problem.

**Comment by patientx** [comment]
Properly apply the hip addon , check your paths etc

**Comment by goldenalexeysky** [comment]
> Properly apply the hip addon , check your paths etc

![Image](https://github.com/user-attachments/assets/c0f438c0-aa2f-4e4a-9cfe-367b76ccaaa3)

![Image](https://github.com/user-attachments/assets/9bfd2d7f-5651-4947-b128-0aaf8a3a281e)

C:\Program Files\AMD\ROCm\6.2

![Image](https://github.com/user-attachments/assets/0dc402cc-65ca-49e1-a45b-89459039eb2d)



HIP SDK extension correctly added C:\Program Files\AMD\ROCm\6.2

**Comment by Lezad** [comment]
> Properly apply the hip addon , check your paths etc

Reinstalling the extension worked for me, thank you

**Comment by JarodStreck** [comment]
@Lezad What do you mean by reinstalling the extension ? i've just done a fresh install and have the exactly the same error

**Comment by quanzs538** [comment]
> 应用 hip 插件 ，检查你的路径等

我是7800XT，按这个步骤就可以了，打开解压，直接覆盖，不过多出来好多G文件，不知道是干什么的

**Comment by patientx** [comment]
> [@Lezad](https://github.com/Lezad) What do you mean by reinstalling the extension ? i've just done a fresh install and have the exactly the same error

5.1 *** YOU MUST DO THIS ADDITIONAL STEP : if you want to try miopen-triton with high end gpu : ***

Install HIP SDK 6.2.4 from [HERE](https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html) the correct version, "Windows 10 & 11 6.2.4 HIP SDK"
Then download hip sdk addon from this url https://drive.google.com/file/d/1JSVDV9yKCJ_vldXb5hS7NEHUeDJGoG6M/view?usp=sharing and extract that into C:\Program Files\AMD\ROCm\6.2

**Comment by JarodStreck** [comment]
Yeah fried this but still not fixing the issue

**Comment by cookriss** [comment]
> Yeah tried this but still not fixing the issue

Hi! Had the same problem, after 2 days, I found that updating the zluda that install-n.bat is installings solves it. You have to download the hip-sdk extension for that version too.

Basically I modified patchzluda-n so it isntalls: https://github.com/lshqqytiger/ZLUDA/releases/download/rel.5e717459179dc272b7d7d23391f0fad66c7459cf/ZLUDA-nightly-windows-rocm6-amd64.zip

and you have to download de v3.9.5 hip sdk extension (the one you have to paste on \ROC\6.2\): https://drive.google.com/file/d/1Gvg3hxNEj2Vsd2nQgwadrUEY6dYXy0H9/view?usp=sharing

Got the versions from this git:
https://github.com/lshqqytiger/ZLUDA/releases/download/rel.0d1513a017397bf9ebbac0b3c846160c8d4fc700/ZLUDA-nightly-windows-rocm6-amd64.zip

**Comment by NaviVoid** [comment]
In my experience you need install the matched version of HIP extension and zluda, furthermore you need to add these to your path:

![Image](https://github.com/user-attachments/assets/9ed97292-0eb7-4feb-8cbb-6d8f069c7d60)

![Image](https://github.com/user-attachments/assets/1e3f1a92-fff8-42d5-8303-26384d3dc048)
