### ISSUE TITLE
CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by natesrooms** [patientx/ComfyUI-Zluda#155]
### Your question

I keep getting this? Anyone know how to fix it?

### Logs

```powershell

```

**Comment by patientx** [comment]
if it is the error when vae decoding , use tiled-vae , from either comfyui itself and select a tile size below or equal to 512 or use tiled-diffusion and same.

**Comment by Testamentcho** [comment]
still no update to this issue :(

**Comment by patientx** [comment]
> still no update to this issue :(

Exactly where does this error comes up ?

What is your gpu, have you used the new setup method, have you got the libraries if necessary, have you correctly copied the hip addon into 6.2 if you are using the new method ?

**Comment by aerocat135** [comment]
I'm not sure if this is a related issue, but I am getting the following error while trying to run custom node AdvancedLivePortrait-->Expression Editor:

RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSdot(handle, n, x, incx, y, incy, result)`

Windows 10
GPU: AMD Radeon 6700XT
HIP SDK: 6.2
Python 3.11
patched with patchzluda2.bat

The error occurs in torch, the line that seems to be causing it is:

File "E:\ComfyUI\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\utils\spectral_norm.py", line 91, in compute_weight
    sigma = torch.dot(u, torch.mv(weight_mat, v))

I also just noticed while scrolling back in the shell window that there is:

rocBLAS error from hip error code: 'hipErrorInvalidDeviceFunction':98

I do believe I have the HIP SDK installed properly and have added the add-on from the 'likelovewant' repository.

**Comment by Sally-san** [comment]
I am getting the same issue. With a fresh install with miopen-triton when doing a basic SDXL txt2img generation on the negative prompt of the workflow.

[sdxl workflow.json](https://github.com/user-attachments/files/20593731/sdxl.workflow.json)

I can get zluda to work and zluda2 with the fork but not Zluda-n

```
# ComfyUI Error Report
## Error Details
- **Node ID:** 20
- **Node Type:** CLIPTextEncode
- **Exception Type:** RuntimeError
- **Exception Message:** CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

Windows 11
GPU: AMD Radeon 7900XTX
HIP SDK: 6.2
Adrenaline: 25.4.1
Python 3.10
fresh install with install-n.bat


[Stacktrace.txt](https://github.com/user-attachments/files/20593732/Stacktrace.txt)

**Comment by patientx** [comment]
For now, try using my cudnn toggle node , copy it from cfz folder into custom_nodes, you can use it when declearing the size (latent) it disables cudnn for that season unless you re-enable it later.

**Comment by patientx** [comment]
Found a potential cause : the checkpoint file just got corrupted, when I download it again or use other sdxl checkpoints, it is working all right.

**Comment by patientx** [comment]
> I am getting the same issue. With a fresh install with miopen-triton when doing a basic SDXL txt2img generation on the negative prompt of the workflow.
> 
> [sdxl workflow.json](https://github.com/user-attachments/files/20593731/sdxl.workflow.json)
> 
> I can get zluda to work and zluda2 with the fork but not Zluda-n
> 
> ```
> # ComfyUI Error Report
> ## Error Details
> - **Node ID:** 20
> - **Node Type:** CLIPTextEncode
> - **Exception Type:** RuntimeError
> - **Exception Message:** CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
> ```
> 
> Windows 11 GPU: AMD Radeon 7900XTX HIP SDK: 6.2 Adrenaline: 25.4.1 Python 3.10 fresh install with install-n.bat
> 
> [Stacktrace.txt](https://github.com/user-attachments/files/20593732/Stacktrace.txt)

The checkpoint file just got corrupted, when I download it again or use other sdxl checkpoints, it is working all right. check the filesize, my corrupted model was just smaller. If you have used my cfz checkpoint loader , that could be the one that corrupted the file, I fixed it, infact it now works outside checkpoint loader so doesn't touch the main models. Please delete the one in your custom_nodes and copy and the new node instead.

**Comment by Sally-san** [comment]
> > I am getting the same issue. With a fresh install with miopen-triton when doing a basic SDXL txt2img generation on the negative prompt of the workflow.
> > [sdxl workflow.json](https://github.com/user-attachments/files/20593731/sdxl.workflow.json)
> > I can get zluda to work and zluda2 with the fork but not Zluda-n
> > ```
> > # ComfyUI Error Report
> > ## Error Details
> > - **Node ID:** 20
> > - **Node Type:** CLIPTextEncode
> > - **Exception Type:** RuntimeError
> > - **Exception Message:** CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Windows 11 GPU: AMD Radeon 7900XTX HIP SDK: 6.2 Adrenaline: 25.4.1 Python 3.10 fresh install with install-n.bat
> > [Stacktrace.txt](https://github.com/user-attachments/files/20593732/Stacktrace.txt)
> 
> The checkpoint file just got corrupted, when I download it again or use other sdxl checkpoints, it is working all right. check the filesize, my corrupted model was just smaller. If you have used my cfz checkpoint loader , that could be the one that corrupted the file, I fixed it, infact it now works outside checkpoint loader so doesn't touch the main models. Please delete the one in your custom_nodes and copy and the new node instead.

OK so i am a little confused at what im supposed to do here. (I was using the basic checkpointloader from comfycore)

I tried re downloading a checkpoint "Jugg_XI_Lightning_by_RD" replacing it and running the workflow with a standard checkpointloader, same Issue.

Then i added cfz checkpoint loader to my custom models, restarted and replaced "Jugg_XI_Lightning_by_RD" incase it got corrupted then ran the work flow with the cfz checkpoint loader, same result.

I then played around with the "cfz checkpoint loader" parameters since i dont actually know what it does, each time i unloaded my model (top right) and replaced the checkpoint with the one from the download folder to ensure it was a "untainted" checkpoint. same result.

[sdxl workflow(1).json](https://github.com/user-attachments/files/20598485/sdxl.workflow.1.json)
[Stacktrace.txt](https://github.com/user-attachments/files/20598484/Stacktrace.txt)

**Comment by patientx** [comment]
I have updated the install. Please follow the readme, remove hip etc.. remove those three folders (in the readme) and reinstall for your best chance.

**Comment by Sally-san** [comment]
> I have updated the install. Please follow the readme, remove hip etc.. remove those three folders (in the readme) and reinstall for your best chance.

OK so I've cleared every thing pip, Triton (and the other 2), Uninstalled my drivers, HIP, deleted my rocm/6.2 folder. Followed install guide step by step and I get the same error. I'm going assume something is fucked on my windows and I need to reinstall, it's been 2 years now. 

But zluda2 patch still works for me this is only an issue for install-n/comfy-n.

So thank you for your help and your work on the project I appreciate it a ton, you don't need to waste anymore time debugging my niche issue. I wish I could contribute to this project but I'm only a web dev this shit is above my paygrade.

**Comment by aerocat135** [comment]
First of all, yes, thank you patientx for your efforts here and your continued support.  I am afraid I am new to trying to implement Comfyui so I don't have a previous configuration that worked to give you a baseline; these are my initial attempts to install/use.  Using the latest instructions in the README, the execution still failed for me, though the error is closer to that in the issue from the OP.  My current configuration is:

Windows 10
GPU: AMD Radeon 6700XT (gfx1031)
HIP SDK: 6.2
copied in the files from likelovewant's repository for gfx1031 (little wu's tensile logic)
Python 3.11
installed with install-n.bat
patched with patchzluda-n.bat
run using comfyui-n,bat

The error that I get now is:

rocBLAS error from hip error code: 'hipErrorInvalidDeviceFunction':98
!!! Exception during processing !!! CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy)`

  File "E:\ComfyUI\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\utils\spectral_norm.py", line 111, in compute_weight
    sigma = torch.dot(u, torch.mv(weight_mat, v))
                         ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy)

I admittedly do not have a detailed understanding of how the processing is being done, but the rocblas error code occurring while performing the cublas math functions nags at me a bit.  Forgive me if I am stating obvious things, but skimming around a bit on AMD's ROCm website seems to indicate that AMD supports ROCm for Runtime, but not for HIP_SDK.  I am assuming that the files being copied in from likelovewant/Brknsoul repositories into the rocblas folders are to account for this.  I have noticed that Brknsoul's repository has library files for gfx1031/ROCm6.2.4....are these the same as the little wu tensile logic ones. or should they maybe be used instead?

**Comment by aerocat135** [comment]
Patientx - 

Alright, so it seems I have now been able to make ComfyUI-Zluda work on my AMD 6700XT, and I do truly appreciate your having put this all together to make ComfyUI work on the AMD GPUs.  I did a couple things differently:

1) I did a 2nd 'start from scratch' clean install of HIP_SDK 6.2.4, also following all of your latest instructions for cache removal, re-installing the new HIP_SDK Add-on, etc.  I used the library files for the AMD6700 (gfx1031) that are in Brknsoul's repository instead of the ones in likelovewant's repository.  I don't really think this made the difference; they basically look the same, i.e., files and filesizes.  However, figured it might not hurt in case something had been corrupted, as you mentioned before regarding your checkpoint file.

2) I noticed that in HIP_SDK files that the original rocblas.dll file is in the 'C:\Program Files\AMD\ROCm\bin' folder and not 'C:\Program Files\AMD\bin\rocblas' where you have said to copy it in your Dependencies instruction 6--bullet 2--ii).  I copied the rocblas.dll file into the '\bin' folder, overwriting AMD's rocblas.dll.  I suspect that was the real culprit, but honestly, I'm guessing.

Hopefully that might help someone else.  Regardless, your work here seems to me a large undertaking, and it is certainly appreciated.

**Comment by badwario** [comment]
install the sdk extensions and u solve this :D https://drive.google.com/file/d/1Gvg3hxNEj2Vsd2nQgwadrUEY6dYXy0H9/view

**Comment by Dwanvea** [comment]
My setup was working but I installed a new SSD and I did a clean install of Comfy-ui. I started getting this error. I re-installed rocm tried switching over from 5.7 to 6.2. I spent hours trying to resolve but Nothing works. 

I don't understand what broke it :( . My GPU is RX 5700 

EDIT: I've fixed the issue by installing a previous version of zluda through patchzluda2 bat on hip 5.7. Zluda Version 3.7.2 did the trick
