### ISSUE TITLE
MOST Audio interactions not working.

### ISSUE THREAD

**Issue by KungFuFurniture** [patientx/ComfyUI-Zluda#164]
### Your question

Truly about the only audio anything I have gotten to work is Ace-Step.   Any of the lip sync tools (LatentSync, Sonic, LivePortrait, new FLOAT) All of em either kick an error (pending on which, extension), or just produce nothing.   I don't have any specific logs, as again, its all of em.   I will gladly grab a log for any of em.   The most recent (tried today) I have tried is FLOAT.   I kept getting a MIOpen error.   "Find could not find a library for computation" or something close.   It started with an error    MIOpen(HIP) ERROR:  [DO] ...   That has to be a different problem, as I have not been able to do audio since well before the addition of "-n" installations / upgrades.   I also tried ChatterBox TTS, which I have as a standalone that works.   In comfy I get a 1 second silent audiofile.  No errors.   Which is what has broght me here, today.   To be clear, I don't really care about any one of the specifc modules, I mentioned above, the common denominator seems to be audio.   Am I doing something wrong, or Not doing something to work with zluda / rocm and audio?

I am on Win 10, RX5700XT, 25.5.1, HIP 6.2.4, Triton, py 3.10.11, Nightly zluda, I am pretty sure I got it all...

### Logs

```powershell

```

**Comment by patientx** [comment]
Don't know about the others (LatentSync, Sonic, LivePortrait, new FLOAT) BUT I solved chatterbox . First of all it seems chatterbox doesn't like cudnn at all, after zluda 3.8.4 most audio problems should have been solved with patches to zluda BUT with our new install we are installing miopen-triton etc. now there comes another problem. the cudnn one. -maybe that is the same with the others as well- 

To cut things short, if you are using this node pack "https://github.com/filliptm/ComfyUI_Fill-ChatterBox" the solution is relatively easy. We need to disable cudnn when chatterbox runs in gpu mode (it works in cpu mode) then enable it after it finishes so it won't be disabled for the rest of that comfyui season. 

Open "chatterbox_node.py" with a text editor , find line 95 , and those three lines after the ...inference"... line it so it looks like below : (the two prints are for confirming it is indeed disabled and also shows the actual value a second time for a second confirmation, so you can delete-remove them or keep them for checking in the future)

        elif torch.cuda.is_available() and device == "cuda":
             message = "Using CUDA (NVIDIA GPU) for inference"
             torch.backends.cudnn.enabled = False
             print("FL_NODE: cuDNN temporarily disabled.")
             print(f"FL_NODE: cuDNN state after disabling: {torch.backends.cudnn.enabled}")
        else:
            message = f"Using {device} for inference" # Should be CPU if no GPU found
        
This makes it so when you select gpu and start using the node, it disables cudnn and works , now we need to re-enable it and that should be in line 232 (before adding the above so after adding those it should line 235) Before the ... for temp_.. line add these two lines : 

        finally:
            torch.backends.cudnn.enabled = True
            print(f"FL_NODE: cuDNN state after enabling: {torch.backends.cudnn.enabled}")  
            for temp_file in temp_files:
                if os.path.exists(temp_file):
                    os.unlink(temp_file)

Add those two lines , so we re-enable it and show the actual value so we know it is re-enabled. This can run again and again. I haven't tried the other ones you mention but they might work this way too, you need to experiment. OR you can use comfy without miopen etc , the previous install but then the old torch-zluda combo might cause other problems for audio models. It is your choice.

You can activate venv ,  on commandline in the comfyui-zluda folder, "venv\scripts\activate" 
install torch 2.7, "pip uninstall torch" , "pip install pip install torch==2.7.0 --index-url https://download.pytorch.org/whl/cu118"
 patch again (the patchzluda-n.bat is updated for this) of course if you want to use latest 3.9.5 don't forget to change its url with the 3.9.4 one in the batch.

**Comment by patientx** [comment]
Built a new node, update comfyui-zluda. There is a cfz folder on the main folder now, copy those nodes inside custom_nodes directory. Next time you start comfy they would be available. "CFZ Cudnn Toggle" is for this audio models not working basically, put it before or after ksampler -some models require before, some only have problems with vae decoding- toggle cuddn off, select latent, then put it after vae decoding between it and save audio node, select audio. This way , it disables cudnn before using said audio model THEN re-enables it after vae-decoding.

Two places the disabling can occur : 

![Image](https://github.com/user-attachments/assets/34e42bd4-7e3e-4302-ad5c-ed437f8da322)

![Image](https://github.com/user-attachments/assets/07773292-c41f-4cae-9959-6d9d0a8157e1)

ace in particular would work with after ksampler but for example chatterbox won't, that would need cudnn disabled before ksampler so 1st example.

**Comment by KungFuFurniture** [comment]
@patientx   Thanks for getting back to me.  I saw your post on the Chatterbox repo, and applied the code changes.  So now there is no gpu error, but still no audio.   I have had this issue since well before you made the big "-n" type file changes (miopen, cudnn, triton, etc.)  So I don't think it's generally related (thought this makes another hurdle), to such issues.   Ace-step had no issue with cudnn.  Here is my terminal from startup to a TTS attempt with ChatterBox.  Again this is not about Chatterbox, but since its a fresh topic on the mind...

```
*** Checking and updating to new version if possible
Already up to date.

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-06-02 10:33:27.898
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: D:\Games\Comfy\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: D:\Games\Comfy\ComfyUI-Zluda
** ComfyUI Base Folder Path: D:\Games\Comfy\ComfyUI-Zluda
** User directory: D:\Games\Comfy\ComfyUI-Zluda\user
** ComfyUI-Manager config path: D:\Games\Comfy\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: D:\Games\Comfy\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-easy-use
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\rgthree-comfy
   5.6 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
Installed version of comfyui-frontend-package: 1.21.6
Installed version of comfyui-workflow-templates: 0.1.25
Installed version of av: 14.4.0

  ::  ------------------------ ZLUDA -----------------------  ::
  ::  Triton core imported successfully
  ::  Running Triton kernel test...
  ::  Triton kernel test passed successfully
  ::  Triton initialized successfully
  ::  Patching ONNX Runtime for ZLUDA — disabling CUDA EP.
  ::  Using ZLUDA with device: AMD Radeon RX 5700 XT [ZLUDA]
  ::  Applying core ZLUDA patches...
  ::  Initializing Triton optimizations
  ::  Configuring Triton device properties...
  ::  Triton device properties configured
  ::  Flash attention components found
  ::  AMD flash attention enabled successfully
  ::  Configuring PyTorch backends...
  ::  Disabled CUDA flash attention
  ::  Enabled math attention fallback
  ::  ZLUDA initialization complete
  ::  ------------------------ ZLUDA -----------------------  ::

Total VRAM 8176 MB, total RAM 49072 MB
pytorch version: 2.7.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 5700 XT [ZLUDA] : native
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
ComfyUI version: 0.3.39
ComfyUI frontend version: 1.21.6
[Prompt Server] web root: D:\Games\Comfy\ComfyUI-Zluda\venv\lib\site-packages\comfyui_frontend_package\static
'sox' is not recognized as an internal or external command,
operable program or batch file.
SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.

Error: File not found - extra_help_file.yaml
No customize audios loading path found, use default path.
[Crystools INFO] Crystools version: 1.22.1
[Crystools INFO] CPU: AMD Ryzen 9 3900X 12-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools WARNING] ZLUDA detected. GPU monitoring will be disabled.
[Crystools WARNING] No GPU with CUDA detected.
xFormers not available
xFormers not available
[ComfyUI-Easy-Use] server: v1.3.0 Loaded
[ComfyUI-Easy-Use] web root: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-easy-use\web_version/v2 Loaded
ComfyUI-GGUF: Partial torch compile only, consider updating pytorch
### Loading: ComfyUI-Impact-Pack (V8.11)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Impact-Subpack (V1.3.2)
[Impact Pack/Subpack] Using folder_paths to determine whitelist path: D:\Games\Comfy\ComfyUI-Zluda\user\default\ComfyUI-Impact-Subpack\model-whitelist.txt
[Impact Pack/Subpack] Ensured whitelist directory exists: D:\Games\Comfy\ComfyUI-Zluda\user\default\ComfyUI-Impact-Subpack
[Impact Pack/Subpack] Loaded 0 model(s) from whitelist: D:\Games\Comfy\ComfyUI-Zluda\user\default\ComfyUI-Impact-Subpack\model-whitelist.txt
[Impact Subpack] ultralytics_bbox: D:\Games\Comfy\ComfyUI-Zluda\models\ultralytics\bbox
[Impact Subpack] ultralytics_segm: D:\Games\Comfy\ComfyUI-Zluda\models\ultralytics\segm
Total VRAM 8176 MB, total RAM 49072 MB
pytorch version: 2.7.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 5700 XT [ZLUDA] : native
Set up system temp directory: C:\Users\ADAMNE~1\AppData\Local\Temp\latentsync_7466ebe5
### Loading: ComfyUI-Manager (V3.32.5)
[ComfyUI-Manager] network_mode: public
### ComfyUI Revision: 4330 [b858113f] | Released on '2025-06-02'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
--------------
 ### Mixlab Nodes: Loaded
json_repair## OK
ChatGPT.available True
edit_mask.available True
## clip_interrogator_model not found: D:\Games\Comfy\ComfyUI-Zluda\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: D:\Games\Comfy\ComfyUI-Zluda\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: D:\Games\Comfy\ComfyUI-Zluda\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
TripoSR.available
MiniCPMNode.available
Scenedetect.available
FishSpeech.available
SenseVoice.available
Whisper.available False
fal-client## OK
FalVideo.available
 --------------
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-LTXVideo
MultiGPU: Found ComfyUI-LTXVideo, creating compatible MultiGPU nodes
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-Florence2
MultiGPU: Found ComfyUI-Florence2, creating compatible MultiGPU nodes
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI_bitsandbytes_NF4
MultiGPU: Module ComfyUI_bitsandbytes_NF4 not found - skipping
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui_bitsandbytes_nf4
MultiGPU: Module comfyui_bitsandbytes_nf4 not found - skipping
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\x-flux-comfyui
MultiGPU: Module x-flux-comfyui not found - skipping
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\x-flux-comfyui
MultiGPU: Module x-flux-comfyui not found - skipping
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-MMAudio
MultiGPU: Module ComfyUI-MMAudio not found - skipping
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-mmaudio
MultiGPU: Module comfyui-mmaudio not found - skipping
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-GGUF
MultiGPU: Found ComfyUI-GGUF, creating compatible MultiGPU nodes
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\PuLID_ComfyUI
MultiGPU: Module PuLID_ComfyUI not found - skipping
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\pulid_comfyui
MultiGPU: Module pulid_comfyui not found - skipping
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-HunyuanVideoWrapper
MultiGPU: Module ComfyUI-HunyuanVideoWrapper not found - skipping
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-hunyuanvideowrapper
MultiGPU: Module comfyui-hunyuanvideowrapper not found - skipping
MultiGPU: Checking for module at D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-WanVideoWrapper
MultiGPU: Found ComfyUI-WanVideoWrapper, creating compatible MultiGPU nodes
MultiGPU: Registration complete. Final mappings: DeviceSelectorMultiGPU, HunyuanVideoEmbeddingsAdapter, MergeFluxLoRAsQuantizeAndLoaddMultiGPU, UNETLoaderMultiGPU, VAELoaderMultiGPU, CLIPLoaderMultiGPU, DualCLIPLoaderMultiGPU, TripleCLIPLoaderMultiGPU, QuadrupleCLIPLoaderMultiGPU, CLIPVisionLoaderMultiGPU, CheckpointLoaderSimpleMultiGPU, ControlNetLoaderMultiGPU, LTXVLoaderMultiGPU, Florence2ModelLoaderMultiGPU, DownloadAndLoadFlorence2ModelMultiGPU, UnetLoaderGGUFMultiGPU, UnetLoaderGGUFDisTorchMultiGPU, UnetLoaderGGUFAdvancedMultiGPU, UnetLoaderGGUFAdvancedDisTorchMultiGPU, CLIPLoaderGGUFMultiGPU, CLIPLoaderGGUFDisTorchMultiGPU, DualCLIPLoaderGGUFMultiGPU, DualCLIPLoaderGGUFDisTorchMultiGPU, TripleCLIPLoaderGGUFMultiGPU, TripleCLIPLoaderGGUFDisTorchMultiGPU, QuadrupleCLIPLoaderGGUFMultiGPU, QuadrupleCLIPLoaderGGUFDisTorchMultiGPU, WanVideoModelLoaderMultiGPU, WanVideoVAELoaderMultiGPU, LoadWanVideoT5TextEncoderMultiGPU

[ReActor] - STATUS - Running v0.6.0-a1 in ComfyUI
Torch version: 2.7.0+cu118
[ReActor] - STATUS - Running v0.5.2-a2 in ComfyUI
Torch version: 2.7.0+cu118
xFormers not available
xFormers not available
xFormers not available
xFormers not available
Set up system temp directory: C:\Users\ADAMNE~1\AppData\Local\Temp\latentsync_7466ebe5\latentsync_1ff9dbd7
FETCH ComfyRegistry Data: 5/87
[D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui_controlnet_aux\ckpts
[D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui_controlnet_aux] | INFO -> Using symlinks: False
[D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Please 'pip install xformers'
Nvidia APEX normalization not installed, using PyTorch LayerNorm
FETCH ComfyRegistry Data: 10/87
FETCH ComfyRegistry Data: 15/87
FETCH ComfyRegistry Data: 20/87
FETCH ComfyRegistry Data: 25/87

[rgthree-comfy] Loaded 47 exciting nodes. 🎉


███████████████████████████████████████████████████████████████████████████████████████████████████████████████████
█                                                                                                                 █
█ ___  _   _  _ __  | |_   __ _ __  __  __| |(_) / _| / _| _   _  ___ (_)  ___   _ __       ___   ___   _ __ ___  █
█/ __|| | | || '_ \ | __| / _` |\ \/ / / _` || || |_ | |_ | | | |/ __|| | / _ \ | '_ \     / __| / _ \ | '_ ` _ \ █
█\__ \| |_| || | | || |_ | (_| | >  < | (_| || ||  _||  _|| |_| |\__ \| || (_) || | | | _ | (__ | (_) || | | | | |█
█|___/ \__, ||_| |_| \__| \__,_|/_/\_\ \__,_||_||_|  |_|   \__,_||___/|_| \___/ |_| |_|(_) \___| \___/ |_| |_| |_|█
█      |___/                                                                                                      █
█                                                                                                                 █
███████████████████████████████████████████████████████████████████████████████████████████████████████████████████


--- Syntax Nodes: Custom Nodes Loaded ---
ComfyUI Custom Nodes: Loaded TryOff Anyone Node
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
FETCH ComfyRegistry Data: 30/87
WAS Node Suite: Finished. Loaded 220 nodes successfully.

        "Art is the most powerful tool we have to connect with the world and express our individuality." - Unknown


Import times for custom nodes:
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-DeepCache-Fix
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI_LatentSync
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\wanblockswap
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-LTX13B-Blockswap
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-deepcache
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\tiled_ksampler
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-mxtoolkit
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-logic
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-VideoBasicLatentSync
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-Upscaler-Tensorrt
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-WanStartEndFramesNative
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-previewlatent
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-ltxvideolora
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-GGUF
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-ultimate-openpose-estimator
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-TiledDiffusion
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\wavespeed
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui_patches_ll
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-custom-scripts
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui_essentials
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-multigpu
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-depthanythingv2
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-WanVideoStartEndFrames
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-frame-interpolation
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\derfuu_comfyui_moddednodes
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-WanVideoWrapper
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-Video-Depth-Anything
   0.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-LTXVideo
   0.1 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI_Sonic
   0.1 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-FramePackWrapper
   0.1 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-Crystools
   0.1 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-LatentSyncWrapper
   0.1 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-impact-pack
   0.1 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-Dwpose-Tensorrt
   0.1 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-tensorops
   0.1 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui_layerstyle
   0.1 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-impact-subpack
   0.2 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-reactor-node
   0.2 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-KJNodes
   0.2 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\gguf
   0.2 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui_pulid_flux_ll
   0.3 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-reactor
   0.3 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-florence2
   0.3 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-videohelpersuite
   0.4 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\syntax-nodes
   0.5 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\audiotools
   0.6 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-easy-use
   0.7 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-Image-Filters
   0.9 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-FLOAT
   1.0 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-Depth-Anything-Tensorrt
   1.1 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
   1.9 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ComfyUI_Fill-ChatterBox
   2.3 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-mixlab-nodes
   2.6 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\was-node-suite-comfyui
   3.2 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ace-step
  10.6 seconds: D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\rgthree-comfy

comfyui-embedded-docs package not found
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH ComfyRegistry Data: 35/87
FETCH ComfyRegistry Data: 40/87
FETCH ComfyRegistry Data: 45/87
FETCH ComfyRegistry Data: 50/87
FETCH ComfyRegistry Data: 55/87
D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
FETCH ComfyRegistry Data: 60/87
FETCH ComfyRegistry Data: 65/87
FETCH ComfyRegistry Data: 70/87
FETCH ComfyRegistry Data: 75/87
FETCH ComfyRegistry Data: 80/87
FETCH ComfyRegistry Data: 85/87
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
got prompt
FL_NODE: cuDNN temporarily disabled.
FL_NODE: cuDNN state after disabling: False
input frame rate=25
loaded PerthNet (Implicit) at step 250,000
FL_NODE: cuDNN state after enabling: True
Prompt executed in 10.05 seconds


With CPU:
got prompt
Prompt executed in 1.45 seconds
```

NOTE, I have never been able to do audio (the sox issue above came with ace-step, which as of today throws an error)

I get this Error from MIOpen  With all sorts of activity.  (non audio related)

```
MIOpen(HIP): Error [Do] 'amd_comgr_do_action(kind, handle, in.GetHandle(), out.GetHandle())' : INVALID_ARGUMENT (2)
MIOpen(HIP): Error [BuildOcl] comgr status = INVALID_ARGUMENT (2)
MIOpen Error: E:/ML/MIOpen/src/hipoc/hipoc_program.cpp:296: Code object build failed. Source: MIOpenIm2d2Col.cl
MIOpen(HIP): Error [Do] 'amd_comgr_do_action(kind, handle, in.GetHandle(), out.GetHandle())' : INVALID_ARGUMENT (2)
MIOpen(HIP): Error [BuildOcl] comgr status = INVALID_ARGUMENT (2)
MIOpen Error: E:/ML/MIOpen/src/hipoc/hipoc_program.cpp:296: Code object build failed. Source: MIOpenIm2d2Col.cl
!!! Exception during processing !!! GET was unable to find an engine to execute this computation
Traceback (most recent call last):
  File "D:\Games\Comfy\ComfyUI-Zluda\execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Games\Comfy\ComfyUI-Zluda\execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Games\Comfy\ComfyUI-Zluda\execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Games\Comfy\ComfyUI-Zluda\execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ace-step\ace_step_nodes.py", line 415, in acestepgen
    audio_output = ap(
  File "D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ace-step\ace_step\pipeline_ace_step.py", line 1370, in __call__
    output_audios = self.latents2audio(
  File "D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ace-step\ace_step\cpu_offload.py", line 40, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ace-step\ace_step\pipeline_ace_step.py", line 1137, in latents2audio
    _, pred_wavs = self.music_dcae.decode(pred_latents, sr=sample_rate)
  File "D:\Games\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ace-step\ace_step\music_dcae\music_dcae_pipeline.py", line 127, in decode
    wav_ch1 = self.vocoder.decode(mels[:,0,:,:]).squeeze(1).cpu()
  File "D:\Games\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ace-step\ace_step\music_dcae\music_vocoder.py", line 551, in decode
    y = self.backbone(mel)
  File "D:\Games\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Games\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Games\Comfy\ComfyUI-Zluda\custom_nodes\ace-step\ace_step\music_dcae\music_vocoder.py", line 254, in forward
    x = channel_layer(x)
  File "D:\Games\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Games\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Games\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\container.py", line 240, in forward
    input = module(input)
  File "D:\Games\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Games\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Games\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\conv.py", line 375, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Games\Comfy\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\conv.py", line 359, in _conv_forward
    return F.conv1d(
RuntimeError: GET was unable to find an engine to execute this computation
```

This is the new one from Ace-step.  But this MIOpen(HIP) ERROR  always starts the same, and ends with either   FIND or GET unable to find engine.

I am on torch 2.7  (started on 2.3 still no audio) I am on nightly zluda 3.9.5.  Got the extras.  Updated VS Tools Yesteday... 

None of this is New. (errors / failures)  I always thought it was a limitation of Zluda.  But I am discovering it's my own handicap of some sort...  Any info or ideas on any of this bologma, would be greatly appreciated.

Either way, Big Thanks to PatientX for getting me / us this Far.  Kudos to you for sure.

**Comment by patientx** [comment]
Have you tried the new node, it completely disables cudnn, just don't re-enable so it would be disabled in that instance of comfy until you exit. Other than that, there was a file causing problems with our zluda setup it is now fixed as of yesterday. Just "activate venv , on commandline in the comfyui-zluda folder, "venv\scripts\activate"
install torch 2.7, "pip uninstall torch" , "pip install pip install torch==2.7.0 --index-url https://download.pytorch.org/whl/cu118"
patch again (the patchzluda-n.bat is updated for this) of course if you want to use latest 3.9.5 don't forget to change its url with the 3.9.4 one in the batch." When you run patchzluda-n.bat, it correctly patches the missing dll and it also copies the new zluda py with audio parts removed, there is no error in chatterbox with this setup, actually if you use the new node I created before chatterbox you won't need to manually change chatterbox node itself probably.

**Comment by KungFuFurniture** [comment]
Ok, So uninstall torch 2.7.   Re-install torch2.7, Repatch with the 3.9.5 nightly.   Had to add  "__init__.py to the CFZ folder once copied into custom nodes.    But after an hour of compile...   It works.   Both Ace (what version are you using?) and Chatterbox.   This also resolved a similar issue I was having with Depth anything.   Cool.   I am about to try FLOAT, see if it'll float...  (sorry)   I think LatentSync and Sonic that I mentioned before look for xformers, so that answers itself.    FYI I used your code fix for Chatterbox tts, and the switch for VC.   It just works now.  Thanks dude!

**UPDATE**
Float works, And Sonic works, but sonic tried to take 8 hours for 8 seconds, so abandon ship.  I would certainly call this problem solved.

**Comment by patientx** [comment]
Closing this, as people can read it from closed as well.
