### ISSUE TITLE
I'm having cuda error in a clean install

### ISSUE THREAD

**Issue by Dwanvea** [patientx/ComfyUI-Zluda#177]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

I had an old setup which was working but I wiped my drives (not C where windows, python, drivers and all other stuff is located), and everything is broken now. I tried re-installing with rocm 5.7 first but couldn't find the old libs I used for RX 5700, there were new ones but after getting this " RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)` " error, I thought they were broken and switched to ROCM 6.2.4. 

At first I had tried Brknsoul Repository for hip 5.7.1 when that didn't work, I Used DDU to wipe out GPU drivers, then installed adrenaline 25.4.1, and after installing rocm 6.2.4 I used the lib from likelovewant Repository for gfx 1010. Then installed Comfy again, used the install bat and I am still getting this annoying error. First zluda starts compiling while reading Negative clip then it gives this error. Been using this awesome fork for months now, I don't understand how simply re-installing it broke everything. Do I need to do anything else? What am I doing wrong?

### Logs

```powershell
Total VRAM 8176 MB, total RAM 16310 MB
pytorch version: 2.3.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 5700 [ZLUDA] : native
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
ComfyUI version: 0.3.40
ComfyUI frontend version: 1.21.7
[Prompt Server] web root: E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\comfyui_frontend_package\static
### Loading: ComfyUI-Manager (V3.32.8)
[ComfyUI-Manager] network_mode: public
### ComfyUI Revision: 4408 [96890e6e] | Released on '2025-06-12'

Import times for custom nodes:
   0.0 seconds: E:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\ComfyUI-deepcache
   1.7 seconds: E:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Context impl SQLiteImpl.
Will assume non-transactional DDL.
No target revision found.
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH ComfyRegistry Data: 5/88
FETCH ComfyRegistry Data: 10/88
FETCH ComfyRegistry Data: 15/88
FETCH ComfyRegistry Data: 20/88
FETCH ComfyRegistry Data: 25/88
FETCH ComfyRegistry Data: 30/88
FETCH ComfyRegistry Data: 35/88
FETCH ComfyRegistry Data: 40/88
FETCH ComfyRegistry Data: 45/88
FETCH ComfyRegistry Data: 50/88
FETCH ComfyRegistry Data: 55/88
FETCH ComfyRegistry Data: 60/88
FETCH ComfyRegistry Data: 65/88
FETCH ComfyRegistry Data: 70/88
FETCH ComfyRegistry Data: 75/88
FETCH ComfyRegistry Data: 80/88
FETCH ComfyRegistry Data: 85/88
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Requested to load SDXLClipModel
loaded completely 9.5367431640625e+25 1560.802734375 True
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
loaded diffusion model directly to GPU
Requested to load SDXL
loaded completely 9.5367431640625e+25 4897.0483474731445 True
Requested to load SDXLClipModel
loaded completely 1720.096875 1560.802734375 True
Compilation is in progress. Please wait...
Compilation is in progress. Please wait...
Compilation is in progress. Please wait...
Compilation is in progress. Please wait...
Compilation is in progress. Please wait...
Compilation is in progress. Please wait...
Compilation is in progress. Please wait...
!!! Exception during processing !!! CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
Traceback (most recent call last):
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\Stable Diffusion\ComfyUI-Zluda\nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\sd.py", line 166, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\sd.py", line 228, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\sdxl_clip.py", line 59, in encode_token_weights
    g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\sd1_clip.py", line 288, in encode
    return self(tokens)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\sd1_clip.py", line 261, in forward
    outputs = self.transformer(None, attention_mask_model, embeds=embeds, num_tokens=num_tokens, intermediate_output=intermediate_output, final_layer_norm_intermediate=self.layer_norm_hidden_state, dtype=torch.float32)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\clip_model.py", line 145, in forward
    x = self.text_model(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\clip_model.py", line 118, in forward
    x, i = self.encoder(x, mask=mask, intermediate_output=intermediate_output)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\clip_model.py", line 70, in forward
    x = l(x, mask, optimized_attention)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\clip_model.py", line 51, in forward
    x += self.self_attn(self.layer_norm1(x), mask, optimized_attention)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\clip_model.py", line 17, in forward
    q = self.q_proj(x)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\ops.py", line 84, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\ops.py", line 80, in forward_comfy_cast_weights
    return torch.nn.functional.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

**Comment by patientx** [comment]
you are using old method but with hip 6.2.4 , am I right ? 

I think for your gpu 5.7.1 would be better and if you are trying to find libs for that (5.7.1) , this archive should have it. 

"https://www.mediafire.com/file/boobrm5vjg7ev50/rocBLAS-HIP5.7.1-win%2528old_gpu%2529.rar/file"

 It has a library folder and a roclass.dll outside so put the library folder as always in "C:\Program Files\AMD\ROCm\5.7\bin\rocblas" and the dll should be put in "C:\Program Files\AMD\ROCm\5.7\bin" of course make a backup of both library folder and the rocblas.dll you are replacing incase something goes wrong.

**Comment by Dwanvea** [comment]
I tried the install-n method as well. I will try this file thanks for sharing it! I tried making 5.7.1 work, only after, trying multiple things I went with 6.2.4. Crazy I get the exact same error no matter what I do. I just want it to work the way it used to work. Hope this one will do it. Going to do another clean install. I will literally start from scratch with python and everything.

**Comment by Dwanvea** [comment]
So, I did a clean re-install of everything, from git to python (used python 3.10.11 this time), and restarted the computer between every step to ensure. I installed 5.7.1 then replaced the libs with the ones from the archive, I made sure they are in PATH, git cloned the repo, ran the install bat, waited for the compiles, and then 

`Requested to load SDXLClipModel
loaded completely 1718.22626953125 1560.802734375 True
Compiling in progress. Please wait...
Compiling in progress. Please wait...
Compiling in progress. Please wait...
Compiling in progress. Please wait...
Compiling in progress. Please wait...
Compiling in progress. Please wait...
Compiling in progress. Please wait...
!!! Exception during processing !!! CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
Traceback (most recent call last):
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\Stable Diffusion\ComfyUI-Zluda\nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\sd.py", line 166, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\sd.py", line 228, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\sdxl_clip.py", line 59, in encode_token_weights
    g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\sd1_clip.py", line 288, in encode
    return self(tokens)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\sd1_clip.py", line 261, in forward
    outputs = self.transformer(None, attention_mask_model, embeds=embeds, num_tokens=num_tokens, intermediate_output=intermediate_output, final_layer_norm_intermediate=self.layer_norm_hidden_state, dtype=torch.float32)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\clip_model.py", line 145, in forward
    x = self.text_model(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\clip_model.py", line 118, in forward
    x, i = self.encoder(x, mask=mask, intermediate_output=intermediate_output)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\clip_model.py", line 70, in forward
    x = l(x, mask, optimized_attention)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\clip_model.py", line 51, in forward
    x += self.self_attn(self.layer_norm1(x), mask, optimized_attention)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\clip_model.py", line 17, in forward
    q = self.q_proj(x)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\ops.py", line 84, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\comfy\ops.py", line 80, in forward_comfy_cast_weights
    return torch.nn.functional.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)``

exact same error. :((

I had also cleaned the caches. I can't understand what's causing this.

**Comment by TheSeraph** [comment]
I am also getting this with a 7900 XTX (two of them)

Python 3.10.11
HIP SDK 5.7
pytorch version: 2.3.0+cu118

**Comment by Dwanvea** [comment]
Got it working, what a headache it has been. I tried guessing what could have changed when I re-installed and HIP was never touched. Shouldn't have bothered with it. Only venv and zluda were updated and got affected by reinstall.

I had a backup the venv so that wasn't it. The issue was the version of Zluda, applying the Zluda patch via patchzluda2.bat fixed the issue. I've tried several of them, I started with 3.8.4 and worked my way down, and at v3.7.2 it started working again 🙏🙏
