### ISSUE TITLE
Lama Remover Nodes

### ISSUE THREAD

**Issue by Dwanvea** [patientx/ComfyUI-Zluda#183]
### Feature Idea

I'm having troubles trying to run this node :  " https://github.com/Layer-norm/comfyui-lama-remover "

After the LAMA model is loaded I get " !!! Exception during processing !!! The following operation failed in the TorchScript interpreter. RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR " this error. I used to get the same error with Florance, for that reason I think it's zluda related but now Florance is fixed and works. I have no idea how it would work but could the same fix work for this one as well?

**Comment by patientx** [comment]
use cudnn toggle node (disable) before using those nodes. Using it one time in the entire comfy run should be enough so you can use it in a basic workflow , just make sure it worked , see its cudnn disabled message and try your nodes.

**Comment by Dwanvea** [comment]
where can I find that node? I think it's included with zluda but it doesn't show up on the list.

**Comment by patientx** [comment]
search with "cfz "

**Comment by Dwanvea** [comment]
I did but nothing shows up when I search by CFZ in the node library.

**Comment by patientx** [comment]
If they are not in custom_nodes, then you can copy them (there are two other nodes, read about them in readme) from cfz folder into custom_nodes folder. After you restart comfy you can find it via cfz keyword.

**Comment by Dwanvea** [comment]
Thanks! I got it shown, and tried applying it but I'm getting this error now "TypeError: 'NoneType' object is not iterable " I changed some places where I put the cfz and couldn't fix it. Happens during the the Lama node. If I set the cfz toggle to true it goes back to giving cudnn error. It seems solvable but I don't know what to do next, sorry for being a noob in this.

Edit: I tried putting the cfz cudnn toggle at various places in the workflow, but I'm still getting the same errors.

**Comment by patientx** [comment]
I installed and tried the node to my comfyui-zluda with everything default, using a rx 6800, all three examples on the node pack works, instantly. No errors at all. What is your gpu, and which install you used, normal install.bat or install-n.bat , either way this node shouldn't have problems with either, it is very old.

**Comment by Dwanvea** [comment]
Thank you for trying ! I have RX 5700, hip 5.7.1, zluda version 3.7.2 (with 3.8.4 and below until 3.7.2 I get errors). Where do you put the cfz toggle in the workflow?

**Comment by patientx** [comment]
> Thank you for trying ! I have RX 5700, hip 5.7.1, zluda version 3.7.2 (with 3.8.4 and below until 3.7.2 I get errors). Where do you put the cfz toggle in the workflow?

That's the thing, it is not needed with this node. You have another problem. But if you must, open the default workflow with cudnn toggle between model and ksampler generate something with sd15 or xl then load your workflow with the node. That way cudnn would be disabled for the rest of that comfy run BUT it seems that's not the problem with your setup.

**Comment by Dwanvea** [comment]
very interesting. If I run CFZ in a separate workflow then add the lama, the error it gives doesn't even change. Here is the full thing :

" The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
File "code/__torch__/saicinpainting/training/trainers/default.py", line 13, in forward
masked_img = torch.mul(img, torch.rsub(mask, 1, 1))
input = torch.cat([masked_img, mask], 1)
_1 = torch.mul(mask, (_0).forward(input, ))
~~~~~~~~~~~ <--- HERE
_2 = torch.mul(torch.rsub(mask, 1, 1), img)
return torch.add(_1, _2, alpha=1)
File "code/__torch__/saicinpainting/training/modules/ffc.py", line 9, in forward
def forward(self: __torch__.saicinpainting.training.modules.ffc.FFCResNetGenerator,
input: Tensor) -> Tensor:
return (self.model).forward(input, )
~~~~~~~~~~~~~~~~~~~ <--- HERE
class FFC_BN_ACT(Module):
__parameters__ = []
File "code/__torch__/torch/nn/modules/container/___torch_mangle_818.py", line 78, in forward
_32 = getattr(self, "1")
_33 = (getattr(self, "0")).forward(input, )
_34 = (_31).forward((_32).forward(_33, ), )
~~~~~~~~~~~~ <--- HERE
_35 = (_29).forward((_30).forward(_34, ), )
_36, _37, = _35
File "code/__torch__/saicinpainting/training/modules/ffc.py", line 25, in forward
_1 = self.bn_g
_2 = self.act_l
_3 = (self.bn_l).forward((self.ffc).forward(argument_1, ), )
~~~~~~~~~~~~~~~~~ <--- HERE
_4 = (_2).forward(_3, )
_5 = (_1).forward()
File "code/__torch__/saicinpainting/training/modules/ffc.py", line 43, in forward
argument_1: Tensor) -> Tensor:
_7 = self.convg2l
_8 = (self.convl2l).forward(argument_1, )
~~~~~~~~~~~~~~~~~~~~~ <--- HERE
_9 = (_7).forward()
input = torch.add(_8, CONSTANTS.c0, alpha=1)
File "code/__torch__/torch/nn/modules/conv.py", line 11, in forward
_0 = self.weight
_1 = torch.reflection_pad2d(argument_1, [0, 0, 0, 0])
_2 = torch._convolution(_1, _0, None, [1, 1], [0, 0], [1, 1], False, [0, 0], 1, False, False, True, True)
~~~~~~~~~~~~~~~~~~ <--- HERE
return _2
class ConvTranspose2d(Module):

Traceback of TorchScript, original code (most recent call last):
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/conv.py(394): _conv_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/conv.py(399): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/root/home/code/lama/saicinpainting/training/modules/ffc.py(221): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/root/home/code/lama/saicinpainting/training/modules/ffc.py(252): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/container.py(119): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/root/home/code/lama/saicinpainting/training/modules/ffc.py(367): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/root/home/code/lama/saicinpainting/training/trainers/default.py(83): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/jit/_trace.py(940): trace_module
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/jit/_trace.py(742): trace
bin/to_jit.py(46): main
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/core/utils.py(160): run_job
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/hydra.py(105): run
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/utils.py(371): <lambda>
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/utils.py(211): run_and_report
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/utils.py(368): _run_hydra
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/main.py(53): decorated_main
bin/to_jit.py(59): <module>
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR "


from cmd window : " [CUDNN_TOGGLE] torch.backends.cudnn.enabled set to False
E:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\comfyui-lama-remover\ckpts\big-lama.pt
!!! Exception during processing !!! 'NoneType' object is not iterable
Traceback (most recent call last):
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 361, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 236, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 208, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 197, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\comfyui-lama-remover\nodes\remover.py", line 110, in lama_remover_IMG
    for image, mask in zip(images, masks):
TypeError: 'NoneType' object is not iterable

Prompt executed in 4.19 seconds
got prompt
[CUDNN_TOGGLE] torch.backends.cudnn.enabled set to False
E:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\comfyui-lama-remover\ckpts\big-lama.pt
input image size :(1536, 2688)
Prepare the imput images
input mask size :(1536, 2688)
Prepare the imput masks
!!! Exception during processing !!! The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/saicinpainting/training/trainers/default.py", line 13, in forward
    masked_img = torch.mul(img, torch.rsub(mask, 1, 1))
    input = torch.cat([masked_img, mask], 1)
    _1 = torch.mul(mask, (_0).forward(input, ))
                          ~~~~~~~~~~~ <--- HERE
    _2 = torch.mul(torch.rsub(mask, 1, 1), img)
    return torch.add(_1, _2, alpha=1)
  File "code/__torch__/saicinpainting/training/modules/ffc.py", line 9, in forward
  def forward(self: __torch__.saicinpainting.training.modules.ffc.FFCResNetGenerator,
    input: Tensor) -> Tensor:
    return (self.model).forward(input, )
            ~~~~~~~~~~~~~~~~~~~ <--- HERE
class FFC_BN_ACT(Module):
  __parameters__ = []
  File "code/__torch__/torch/nn/modules/container/___torch_mangle_818.py", line 78, in forward
    _32 = getattr(self, "1")
    _33 = (getattr(self, "0")).forward(input, )
    _34 = (_31).forward((_32).forward(_33, ), )
                         ~~~~~~~~~~~~ <--- HERE
    _35 = (_29).forward((_30).forward(_34, ), )
    _36, _37, = _35
  File "code/__torch__/saicinpainting/training/modules/ffc.py", line 25, in forward
    _1 = self.bn_g
    _2 = self.act_l
    _3 = (self.bn_l).forward((self.ffc).forward(argument_1, ), )
                              ~~~~~~~~~~~~~~~~~ <--- HERE
    _4 = (_2).forward(_3, )
    _5 = (_1).forward()
  File "code/__torch__/saicinpainting/training/modules/ffc.py", line 43, in forward
    argument_1: Tensor) -> Tensor:
    _7 = self.convg2l
    _8 = (self.convl2l).forward(argument_1, )
          ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _9 = (_7).forward()
    input = torch.add(_8, CONSTANTS.c0, alpha=1)
  File "code/__torch__/torch/nn/modules/conv.py", line 11, in forward
    _0 = self.weight
    _1 = torch.reflection_pad2d(argument_1, [0, 0, 0, 0])
    _2 = torch._convolution(_1, _0, None, [1, 1], [0, 0], [1, 1], False, [0, 0], 1, False, False, True, True)
         ~~~~~~~~~~~~~~~~~~ <--- HERE
    return _2
class ConvTranspose2d(Module):

Traceback of TorchScript, original code (most recent call last):
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/conv.py(394): _conv_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/conv.py(399): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/root/home/code/lama/saicinpainting/training/modules/ffc.py(221): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/root/home/code/lama/saicinpainting/training/modules/ffc.py(252): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/container.py(119): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/root/home/code/lama/saicinpainting/training/modules/ffc.py(367): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/root/home/code/lama/saicinpainting/training/trainers/default.py(83): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/jit/_trace.py(940): trace_module
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/jit/_trace.py(742): trace
bin/to_jit.py(46): main
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/core/utils.py(160): run_job
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/hydra.py(105): run
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/utils.py(371): <lambda>
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/utils.py(211): run_and_report
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/utils.py(368): _run_hydra
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/main.py(53): decorated_main
bin/to_jit.py(59): <module>
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

Traceback (most recent call last):
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 361, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 236, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 208, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Stable Diffusion\ComfyUI-Zluda\execution.py", line 197, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\comfyui-lama-remover\nodes\remover.py", line 146, in lama_remover_IMG
    result = mylama(pt_image, pt_mask)
  File "E:\Stable Diffusion\ComfyUI-Zluda\custom_nodes\comfyui-lama-remover\lama\model.py", line 32, in __call__
    result = self.model(image, mask)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/saicinpainting/training/trainers/default.py", line 13, in forward
    masked_img = torch.mul(img, torch.rsub(mask, 1, 1))
    input = torch.cat([masked_img, mask], 1)
    _1 = torch.mul(mask, (_0).forward(input, ))
                          ~~~~~~~~~~~ <--- HERE
    _2 = torch.mul(torch.rsub(mask, 1, 1), img)
    return torch.add(_1, _2, alpha=1)
  File "code/__torch__/saicinpainting/training/modules/ffc.py", line 9, in forward
  def forward(self: __torch__.saicinpainting.training.modules.ffc.FFCResNetGenerator,
    input: Tensor) -> Tensor:
    return (self.model).forward(input, )
            ~~~~~~~~~~~~~~~~~~~ <--- HERE
class FFC_BN_ACT(Module):
  __parameters__ = []
  File "code/__torch__/torch/nn/modules/container/___torch_mangle_818.py", line 78, in forward
    _32 = getattr(self, "1")
    _33 = (getattr(self, "0")).forward(input, )
    _34 = (_31).forward((_32).forward(_33, ), )
                         ~~~~~~~~~~~~ <--- HERE
    _35 = (_29).forward((_30).forward(_34, ), )
    _36, _37, = _35
  File "code/__torch__/saicinpainting/training/modules/ffc.py", line 25, in forward
    _1 = self.bn_g
    _2 = self.act_l
    _3 = (self.bn_l).forward((self.ffc).forward(argument_1, ), )
                              ~~~~~~~~~~~~~~~~~ <--- HERE
    _4 = (_2).forward(_3, )
    _5 = (_1).forward()
  File "code/__torch__/saicinpainting/training/modules/ffc.py", line 43, in forward
    argument_1: Tensor) -> Tensor:
    _7 = self.convg2l
    _8 = (self.convl2l).forward(argument_1, )
          ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _9 = (_7).forward()
    input = torch.add(_8, CONSTANTS.c0, alpha=1)
  File "code/__torch__/torch/nn/modules/conv.py", line 11, in forward
    _0 = self.weight
    _1 = torch.reflection_pad2d(argument_1, [0, 0, 0, 0])
    _2 = torch._convolution(_1, _0, None, [1, 1], [0, 0], [1, 1], False, [0, 0], 1, False, False, True, True)
         ~~~~~~~~~~~~~~~~~~ <--- HERE
    return _2
class ConvTranspose2d(Module):

Traceback of TorchScript, original code (most recent call last):
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/conv.py(394): _conv_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/conv.py(399): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/root/home/code/lama/saicinpainting/training/modules/ffc.py(221): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/root/home/code/lama/saicinpainting/training/modules/ffc.py(252): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/container.py(119): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/root/home/code/lama/saicinpainting/training/modules/ffc.py(367): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/root/home/code/lama/saicinpainting/training/trainers/default.py(83): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/jit/_trace.py(940): trace_module
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/jit/_trace.py(742): trace
bin/to_jit.py(46): main
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/core/utils.py(160): run_job
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/hydra.py(105): run
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/utils.py(371): <lambda>
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/utils.py(211): run_and_report
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/utils.py(368): _run_hydra
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/main.py(53): decorated_main
bin/to_jit.py(59): <module>
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR


Prompt executed in 2.38 seconds"

**Comment by Dwanvea** [comment]
Well, I managed to solve the problem with claude sonnet. I described my issue and gave it the error I posted above and it said the problem lies within " custom_nodes\comfyui-lama-remover\nodes\remover.py " Then I gave it the Python code of the said node. It generated a fix for it. Replacing that py with the code below in notepad fixed my problem. It ran in the CPU.

" from PIL import ImageOps, ImageFilter
import torch
from ..utils import cropimage, padimage, padmask, tensor2pil, pil2tensor, cropimage, pil2comfy
from ..lama import model
from torchvision import transforms

# Disable cuDNN for ZLUDA compatibility
torch.backends.cudnn.enabled = False
torch.backends.cudnn.benchmark = False

class LamaRemover:
    def __init__(self):
        # Initialize the model once as a class attribute to avoid repeated loading
        self.mylama = None
    
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "images": ("IMAGE",),
                "masks": ("MASK",),
                "mask_threshold":("INT", {"default": 250, "min": 0, "max": 255, "step": 1, "display": "slider"}),
                "gaussblur_radius": ("INT", {"default": 8, "min": 0, "max": 20, "step": 1, "display": "slider"}),
                "invert_mask": ("BOOLEAN", {"default": False}),
            },
        }
    
    CATEGORY = "LamaRemover"
    RETURN_NAMES = ("images",)
    RETURN_TYPES = ("IMAGE",)
    FUNCTION = "lama_remover"

    def _get_model(self):
        # Lazy loading of the model
        if self.mylama is None:
            # Disable cuDNN before model initialization
            torch.backends.cudnn.enabled = False
            self.mylama = model.BigLama()
            
            # Force model to CPU if it's a TorchScript model having issues with ZLUDA
            if hasattr(self.mylama, 'model'):
                try:
                    # Try to move model to CPU to avoid cuDNN issues
                    self.mylama.model = self.mylama.model.cpu()
                except:
                    pass
                
                # Disable cuDNN on modules if possible
                for module in self.mylama.model.modules():
                    if hasattr(module, 'use_cudnn'):
                        module.use_cudnn = False
        return self.mylama

    def lama_remover(self, images, masks, mask_threshold, gaussblur_radius, invert_mask):
        mylama = self._get_model()
        ten2pil = transforms.ToPILImage()

        results=[]
        
        for image, mask in zip(images, masks):
            ori_image = tensor2pil(image)
            print(f"input image size :{ori_image.size}")

            w, h = ori_image.size
            p_image = padimage(ori_image)
            pt_image = pil2tensor(p_image)

            mask = mask.unsqueeze(0)
            ori_mask = ten2pil(mask)
            ori_mask = ori_mask.convert('L')
            print(f"input mask size :{ori_mask.size}")

            p_mask = padmask(ori_mask)

            if p_mask.size != p_image.size:
                print("resize mask")
                p_mask = p_mask.resize(p_image.size)

            # invert mask
            # 反转遮罩
            if not invert_mask:
                p_mask = ImageOps.invert(p_mask)
            
            # gaussian Blur
            # 高斯模糊遮罩（模糊的是白色）
            p_mask = p_mask.filter(ImageFilter.GaussianBlur(radius=gaussblur_radius))

            # mask_threshold
            # 遮罩阈值，越大越强
            gray = p_mask.point(lambda x: 0 if x>mask_threshold else 255)

            pt_mask = pil2tensor(gray)

            # lama
            # lama模型
            # Force CPU execution to avoid cuDNN issues with ZLUDA
            pt_image_cpu = pt_image.cpu() if pt_image.is_cuda else pt_image
            pt_mask_cpu = pt_mask.cpu() if pt_mask.is_cuda else pt_mask
            
            with torch.backends.cudnn.flags(enabled=False, benchmark=False):
                result = mylama(pt_image_cpu, pt_mask_cpu)
                # Move result back to original device if needed
                if pt_image.is_cuda:
                    result = result.cuda()

            img_result = ten2pil(result)

            # crop into the original size
            # 裁剪成输入大小
            x, y = img_result.size
            if x > w or y > h:
                img_result = cropimage(img_result, w, h)

            # turn to comfyui tensor
            # 变成comfyui格式（i,h,w,c）
            i = pil2comfy(img_result)
            results.append(i)
       
        return (torch.cat(results, dim=0),)



class LamaRemoverIMG:
    def __init__(self):
        # Initialize the model once as a class attribute to avoid repeated loading
        self.mylama = None
    
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "images": ("IMAGE",),
                "masks": ("IMAGE",),
                "mask_threshold":("INT", {"default": 250, "min": 0, "max": 255, "step": 1, "display": "slider"}),
                "gaussblur_radius": ("INT", {"default": 8, "min": 0, "max": 20, "step": 1, "display": "slider"}),
                "invert_mask": ("BOOLEAN", {"default": False}),
            },
        }
    
    CATEGORY = "LamaRemover"
    RETURN_NAMES = ("images",)
    RETURN_TYPES = ("IMAGE",)
    FUNCTION = "lama_remover_IMG"

    def _get_model(self):
        # Lazy loading of the model
        if self.mylama is None:
            # Disable cuDNN before model initialization
            torch.backends.cudnn.enabled = False
            self.mylama = model.BigLama()
            
            # Force model to CPU if it's a TorchScript model having issues with ZLUDA
            if hasattr(self.mylama, 'model'):
                try:
                    # Try to move model to CPU to avoid cuDNN issues
                    self.mylama.model = self.mylama.model.cpu()
                except:
                    pass
                
                # Disable cuDNN on modules if possible
                for module in self.mylama.model.modules():
                    if hasattr(module, 'use_cudnn'):
                        module.use_cudnn = False
        return self.mylama

    def lama_remover_IMG(self, images, masks, mask_threshold, gaussblur_radius, invert_mask):
        mylama = self._get_model()
        ten2pil = transforms.ToPILImage()

        results=[]
        
        for image, mask in zip(images, masks):
            ori_image = tensor2pil(image)
            print(f"input image size :{ori_image.size}")

            w, h = ori_image.size
            p_image = padimage(ori_image)
            pt_image = pil2tensor(p_image)

            mask = mask.movedim(0, -1).movedim(0,-1)
            ori_mask = ten2pil(mask)
            ori_mask = ori_mask.convert('L')
            print(f"input mask size :{ori_mask.size}")

            p_mask = padmask(ori_mask)

            if p_mask.size != p_image.size:
                print("resize mask")
                p_mask = p_mask.resize(p_image.size)

            # invert mask
            # 反转遮罩
            if not invert_mask:
                p_mask = ImageOps.invert(p_mask)

            # gaussian Blur
            # 高斯模糊遮罩（模糊的是黑色所以需要反转操作）
            p_mask = p_mask.filter(ImageFilter.GaussianBlur(radius=gaussblur_radius))

            # mask_threshold
            # 遮罩阈值，越大越强
            gray = p_mask.point(lambda x: 0 if x>mask_threshold else 255)

            pt_mask = pil2tensor(gray)

            # lama
            # lama模型
            # Force CPU execution to avoid cuDNN issues with ZLUDA
            pt_image_cpu = pt_image.cpu() if pt_image.is_cuda else pt_image
            pt_mask_cpu = pt_mask.cpu() if pt_mask.is_cuda else pt_mask
            
            with torch.backends.cudnn.flags(enabled=False, benchmark=False):
                result = mylama(pt_image_cpu, pt_mask_cpu)
                # Move result back to original device if needed
                if pt_image.is_cuda:
                    result = result.cuda()

            img_result = ten2pil(result)

            # crop into the original size
            # 裁剪成输入大小
            x, y = img_result.size
            if x > w or y > h:
                img_result = cropimage(img_result, w, h)

            # turn to comfyui tensor
            # 变成comfyui格式（i,h,w,c）
            i = pil2comfy(img_result)
            results.append(i)
       
        return (torch.cat(results, dim=0),)

NODE_CLASS_MAPPINGS = {
    "LamaRemover": LamaRemover,
    "LamaRemoverIMG": LamaRemoverIMG
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "LamaRemover": "Big lama Remover",
    "LamaRemoverIMG": "Big lama Remover(IMG)"
}"

I don't understand what the problem was but maybe you can :D Anyways, I can use the node now, thank you again for taking your time to help this issue.
