### ISSUE TITLE
CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by LightningFlexors** [patientx/ComfyUI-Zluda#184]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

succesfully generating using comfyui

### Actual Behavior

CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### Steps to Reproduce

not sure

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 7
- **Node Type:** CLIPTextEncode
- **Exception Type:** RuntimeError
- **Exception Message:** CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
## Stack Trace

  File "F:\DF2\ComfyUI-Zluda\execution.py", line 361, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\execution.py", line 236, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\execution.py", line 208, in _map_node_over_list
    process_inputs(input_dict, i)

  File "F:\DF2\ComfyUI-Zluda\execution.py", line 197, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\comfy\sd.py", line 166, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\comfy\sd.py", line 228, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\comfy\sd1_clip.py", line 682, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\comfy\sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\comfy\sd1_clip.py", line 288, in encode
    return self(tokens)
           ^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\comfy\sd1_clip.py", line 261, in forward
    outputs = self.transformer(None, attention_mask_model, embeds=embeds, num_tokens=num_tokens, intermediate_output=intermediate_output, final_layer_norm_intermediate=self.layer_norm_hidden_state, dtype=torch.float32)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\comfy\text_encoders\t5.py", line 249, in forward
    return self.encoder(x, attention_mask=attention_mask, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\comfy\text_encoders\t5.py", line 217, in forward
    x, past_bias = l(x, mask, past_bias, optimized_attention)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\comfy\text_encoders\t5.py", line 188, in forward
    x, past_bias = self.layer[0](x, mask, past_bias, optimized_attention)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\comfy\text_encoders\t5.py", line 175, in forward
    output, past_bias = self.SelfAttention(self.layer_norm(x), mask=mask, past_bias=past_bias, optimized_attention=optimized_attention)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\comfy\text_encoders\t5.py", line 152, in forward
    q = self.q(x)
        ^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\comfy\ops.py", line 84, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\DF2\ComfyUI-Zluda\comfy\ops.py", line 80, in forward_comfy_cast_weights
    return torch.nn.functional.linear(input, weight, bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


## System Information
- **ComfyUI Version:** 0.3.41
- **Arguments:** main.py --auto-launch --use-quad-cross-attention --reserve-vram 0.9
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.7.0+cu118
## Devices

- **Name:** cuda:0 AMD Radeon RX 6800 XT [ZLUDA] : native
  - **Type:** cuda
  - **VRAM Total:** 17163091968
  - **VRAM Free:** 5518351872
  - **Torch VRAM Total:** 11385438208
  - **Torch VRAM Free:** 14048768

## Logs

2025-06-17T16:08:31.096963 - [START] Security scan2025-06-17T16:08:31.096963 - 
2025-06-17T16:08:31.731819 - [DONE] Security scan2025-06-17T16:08:31.731819 - 
2025-06-17T16:08:31.733820 - ## ComfyUI-Manager: installing dependencies. (GitPython)2025-06-17T16:08:31.733820 - 
2025-06-17T16:08:37.034482 - ## ComfyUI-Manager: installing dependencies done.2025-06-17T16:08:37.034482 - 
2025-06-17T16:08:37.035484 - ** ComfyUI startup time:2025-06-17T16:08:37.036484 -  2025-06-17T16:08:37.036484 - 2025-06-17 16:08:37.0352025-06-17T16:08:37.036484 - 
2025-06-17T16:08:37.036484 - ** Platform:2025-06-17T16:08:37.036484 -  2025-06-17T16:08:37.036484 - Windows2025-06-17T16:08:37.036484 - 
2025-06-17T16:08:37.036484 - ** Python version:2025-06-17T16:08:37.037483 -  2025-06-17T16:08:37.037483 - 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]2025-06-17T16:08:37.037483 - 
2025-06-17T16:08:37.037483 - ** Python executable:2025-06-17T16:08:37.037483 -  2025-06-17T16:08:37.037483 - F:\DF2\ComfyUI-Zluda\venv\Scripts\python.exe2025-06-17T16:08:37.037483 - 
2025-06-17T16:08:37.038483 - ** ComfyUI Path:2025-06-17T16:08:37.038483 -  2025-06-17T16:08:37.038483 - F:\DF2\ComfyUI-Zluda2025-06-17T16:08:37.038483 - 
2025-06-17T16:08:37.038483 - ** ComfyUI Base Folder Path:2025-06-17T16:08:37.038483 -  2025-06-17T16:08:37.039483 - F:\DF2\ComfyUI-Zluda2025-06-17T16:08:37.039483 - 
2025-06-17T16:08:37.039483 - ** User directory:2025-06-17T16:08:37.039483 -  2025-06-17T16:08:37.039483 - F:\DF2\ComfyUI-Zluda\user2025-06-17T16:08:37.039483 - 
2025-06-17T16:08:37.040484 - ** ComfyUI-Manager config path:2025-06-17T16:08:37.040484 -  2025-06-17T16:08:37.040484 - F:\DF2\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini2025-06-17T16:08:37.040484 - 
2025-06-17T16:08:37.040484 - ** Log path:2025-06-17T16:08:37.041484 -  2025-06-17T16:08:37.041484 - F:\DF2\ComfyUI-Zluda\user\comfyui.log2025-06-17T16:08:37.041484 - 
2025-06-17T16:08:37.813885 - 
Prestartup times for custom nodes:
2025-06-17T16:08:37.814887 -    7.2 seconds: F:\DF2\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
2025-06-17T16:08:37.815886 - 
2025-06-17T16:08:39.296889 - Checkpoint files will always be loaded safely.
2025-06-17T16:08:40.238477 - 
  ::  Checking package versions...2025-06-17T16:08:40.239477 - 
2025-06-17T16:08:40.242475 - Found pydantic: 2.11.7, pydantic-settings: 2.9.12025-06-17T16:08:40.242475 - 
2025-06-17T16:08:40.310477 -   ::  Pydantic packages are compatible, skipping reinstall2025-06-17T16:08:40.310477 - 
2025-06-17T16:08:40.311477 - Installed version of comfyui-frontend-package: 1.21.72025-06-17T16:08:40.311477 - 
2025-06-17T16:08:40.314476 - Installed version of comfyui-workflow-templates: 0.1.282025-06-17T16:08:40.314476 - 
2025-06-17T16:08:40.315475 - Installed version of av: 14.4.02025-06-17T16:08:40.315475 - 
2025-06-17T16:08:40.316476 - Installed version of comfyui-embedded-docs: 0.2.22025-06-17T16:08:40.316476 - 
2025-06-17T16:08:40.316476 -   ::  Package version check complete.2025-06-17T16:08:40.317476 - 
2025-06-17T16:08:40.317476 - 
  ::  ------------------------ ZLUDA -----------------------  ::  2025-06-17T16:08:40.317476 - 
2025-06-17T16:08:40.317476 -   ::  Triton core imported successfully2025-06-17T16:08:40.318476 - 
2025-06-17T16:08:40.318476 -   ::  Running Triton kernel test...2025-06-17T16:08:40.319476 - 
2025-06-17T16:09:01.230281 - Using HIP SDK Clang.2025-06-17T16:09:01.230281 - 
2025-06-17T16:09:01.977624 -   ::  Triton test failed: Command '['C:\\Program Files\\AMD\\ROCm\\6.2\\bin\\clang.exe', 'C:\\Users\\STRIDE~1\\AppData\\Local\\Temp\\tmpt6jtnsmg\\main.c', '-O3', '-shared', '-Wno-psabi', '-o', 'C:\\Users\\STRIDE~1\\AppData\\Local\\Temp\\tmpt6jtnsmg\\hip_utils.cp311-win_amd64.pyd', '-LF:\\DF2\\ComfyUI-Zluda\\venv\\libs', '-LC:\\Program Files\\AMD\\ROCm\\6.2\\lib', '-IF:\\DF2\\ComfyUI-Zluda\\venv\\Lib\\site-packages\\triton\\backends\\amd\\include', '-IC:\\Users\\STRIDE~1\\AppData\\Local\\Temp\\tmpt6jtnsmg', '-IC:\\Users\\Strider_Hien\\AppData\\Local\\Programs\\Python\\Python311\\Include']' returned non-zero exit status 1.2025-06-17T16:09:01.977624 - 
2025-06-17T16:09:01.978624 -   ::  Triton available but failed verification2025-06-17T16:09:01.978624 - 
2025-06-17T16:09:02.029136 -   ::  Patching ONNX Runtime for ZLUDA — disabling CUDA EP.2025-06-17T16:09:02.029136 - 
2025-06-17T16:09:02.029136 -   ::  Using ZLUDA with device: AMD Radeon RX 6800 XT [ZLUDA]2025-06-17T16:09:02.029136 - 
2025-06-17T16:09:02.029136 -   ::  Applying core ZLUDA patches...2025-06-17T16:09:02.030136 - 
2025-06-17T16:09:02.030136 -   ::  Triton optimizations skipped (not available)2025-06-17T16:09:02.030136 - 
2025-06-17T16:09:02.030136 -   ::  Configuring PyTorch backends...2025-06-17T16:09:02.031136 - 
2025-06-17T16:09:02.031136 -   ::  Disabled CUDA flash attention2025-06-17T16:09:02.031136 - 
2025-06-17T16:09:02.031136 -   ::  Enabled math attention fallback2025-06-17T16:09:02.032137 - 
2025-06-17T16:09:02.032137 -   ::  ZLUDA initialization complete2025-06-17T16:09:02.032137 - 
2025-06-17T16:09:02.032137 -   ::  ------------------------ ZLUDA -----------------------  ::  
2025-06-17T16:09:02.032137 - 
2025-06-17T16:09:02.039136 - Total VRAM 16368 MB, total RAM 49074 MB
2025-06-17T16:09:02.039136 - pytorch version: 2.7.0+cu118
2025-06-17T16:09:02.040136 - Set vram state to: NORMAL_VRAM
2025-06-17T16:09:02.040136 - Device: cuda:0 AMD Radeon RX 6800 XT [ZLUDA] : native
2025-06-17T16:09:02.331137 - Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
2025-06-17T16:09:03.830375 - Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
2025-06-17T16:09:03.830375 - ComfyUI version: 0.3.41
2025-06-17T16:09:03.852374 - ComfyUI frontend version: 1.21.7
2025-06-17T16:09:03.853374 - [Prompt Server] web root: F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\comfyui_frontend_package\static
2025-06-17T16:09:04.835658 - ### Loading: ComfyUI-Manager (V3.33.1)
2025-06-17T16:09:04.836657 - [ComfyUI-Manager] network_mode: public
2025-06-17T16:09:05.182656 - ### ComfyUI Revision: 4450 [6bb28517] | Released on '2025-06-17'
2025-06-17T16:09:05.203629 - 
Import times for custom nodes:
2025-06-17T16:09:05.203629 -    0.0 seconds: F:\DF2\ComfyUI-Zluda\custom_nodes\cfz_vae_loader.py
2025-06-17T16:09:05.203629 -    0.0 seconds: F:\DF2\ComfyUI-Zluda\custom_nodes\websocket_image_save.py
2025-06-17T16:09:05.204630 -    0.0 seconds: F:\DF2\ComfyUI-Zluda\custom_nodes\cfz_cudnn.toggle.py
2025-06-17T16:09:05.204630 -    0.0 seconds: F:\DF2\ComfyUI-Zluda\custom_nodes\ComfyUI-deepcache
2025-06-17T16:09:05.204630 -    0.0 seconds: F:\DF2\ComfyUI-Zluda\custom_nodes\cfz_patcher.py
2025-06-17T16:09:05.205630 -    0.6 seconds: F:\DF2\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
2025-06-17T16:09:05.205630 - 
2025-06-17T16:09:05.314629 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-06-17T16:09:05.328628 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-06-17T16:09:05.380629 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-06-17T16:09:05.455772 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-06-17T16:09:05.500769 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-06-17T16:09:05.538768 - Context impl SQLiteImpl.
2025-06-17T16:09:05.539768 - Will assume non-transactional DDL.
2025-06-17T16:09:05.543769 - No target revision found.
2025-06-17T16:09:05.556769 - Starting server

2025-06-17T16:09:05.557769 - To see the GUI go to: http://127.0.0.1:8188
2025-06-17T16:09:09.926318 - FETCH ComfyRegistry Data: 5/892025-06-17T16:09:09.927317 - 
2025-06-17T16:09:13.610793 - FETCH ComfyRegistry Data: 10/892025-06-17T16:09:13.610793 - 
2025-06-17T16:09:17.325836 - FETCH ComfyRegistry Data: 15/892025-06-17T16:09:17.325836 - 
2025-06-17T16:09:21.030864 - FETCH ComfyRegistry Data: 20/892025-06-17T16:09:21.030864 - 
2025-06-17T16:09:25.258000 - FETCH ComfyRegistry Data: 25/892025-06-17T16:09:25.259001 - 
2025-06-17T16:09:29.536110 - FETCH ComfyRegistry Data: 30/892025-06-17T16:09:29.536110 - 
2025-06-17T16:09:33.316766 - FETCH ComfyRegistry Data: 35/892025-06-17T16:09:33.317768 - 
2025-06-17T16:09:37.052841 - FETCH ComfyRegistry Data: 40/892025-06-17T16:09:37.052841 - 
2025-06-17T16:09:40.892017 - FETCH ComfyRegistry Data: 45/892025-06-17T16:09:40.892017 - 
2025-06-17T16:09:44.712560 - FETCH ComfyRegistry Data: 50/892025-06-17T16:09:44.712560 - 
2025-06-17T16:09:48.496665 - FETCH ComfyRegistry Data: 55/892025-06-17T16:09:48.496665 - 
2025-06-17T16:09:52.935117 - FETCH ComfyRegistry Data: 60/892025-06-17T16:09:52.935117 - 
2025-06-17T16:09:58.097363 - FETCH ComfyRegistry Data: 65/892025-06-17T16:09:58.097363 - 
2025-06-17T16:10:01.944741 - FETCH ComfyRegistry Data: 70/892025-06-17T16:10:01.945742 - 
2025-06-17T16:10:05.871168 - FETCH ComfyRegistry Data: 75/892025-06-17T16:10:05.871168 - 
2025-06-17T16:10:09.774023 - FETCH ComfyRegistry Data: 80/892025-06-17T16:10:09.774023 - 
2025-06-17T16:10:14.143594 - FETCH ComfyRegistry Data: 85/892025-06-17T16:10:14.143594 - 
2025-06-17T16:10:17.823923 - FETCH ComfyRegistry Data [DONE]2025-06-17T16:10:17.823923 - 
2025-06-17T16:10:17.935924 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2025-06-17T16:10:17.952923 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-06-17T16:10:17.952923 - 2025-06-17T16:10:18.107491 -  [DONE]2025-06-17T16:10:18.107491 - 
2025-06-17T16:10:18.165491 - [ComfyUI-Manager] All startup tasks have been completed.
2025-06-17T16:15:06.962975 - got prompt
2025-06-17T16:15:07.025974 - Using split attention in VAE
2025-06-17T16:15:07.027975 - Using split attention in VAE
2025-06-17T16:15:07.187975 - VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
2025-06-17T16:15:19.512945 - Requested to load WanTEModel
2025-06-17T16:15:19.521945 - loaded completely 9.5367431640625e+25 10835.4765625 True
2025-06-17T16:15:19.530945 - CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
2025-06-17T16:21:25.008417 - !!! Exception during processing !!! CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
2025-06-17T16:21:25.017418 - Traceback (most recent call last):
  File "F:\DF2\ComfyUI-Zluda\execution.py", line 361, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\execution.py", line 236, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\execution.py", line 208, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\DF2\ComfyUI-Zluda\execution.py", line 197, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\comfy\sd.py", line 166, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\comfy\sd.py", line 228, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\comfy\sd1_clip.py", line 682, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\comfy\sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\comfy\sd1_clip.py", line 288, in encode
    return self(tokens)
           ^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\comfy\sd1_clip.py", line 261, in forward
    outputs = self.transformer(None, attention_mask_model, embeds=embeds, num_tokens=num_tokens, intermediate_output=intermediate_output, final_layer_norm_intermediate=self.layer_norm_hidden_state, dtype=torch.float32)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\comfy\text_encoders\t5.py", line 249, in forward
    return self.encoder(x, attention_mask=attention_mask, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\comfy\text_encoders\t5.py", line 217, in forward
    x, past_bias = l(x, mask, past_bias, optimized_attention)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\comfy\text_encoders\t5.py", line 188, in forward
    x, past_bias = self.layer[0](x, mask, past_bias, optimized_attention)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\comfy\text_encoders\t5.py", line 175, in forward
    output, past_bias = self.SelfAttention(self.layer_norm(x), mask=mask, past_bias=past_bias, optimized_attention=optimized_attention)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\comfy\text_encoders\t5.py", line 152, in forward
    q = self.q(x)
        ^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\comfy\ops.py", line 84, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\DF2\ComfyUI-Zluda\comfy\ops.py", line 80, in forward_comfy_cast_weights
    return torch.nn.functional.linear(input, weight, bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

2025-06-17T16:21:25.021417 - Prompt executed in 378.05 seconds


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.

Workflow too large. Please manually upload the workflow from local file system.


## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

**Comment by Dwanvea** [comment]
I had this issue, I removed caches first and by using patchzluda2.bat and giving it the link for [zluda 3.7.2 ](https://github.com/lshqqytiger/ZLUDA/releases/download/rel.4f12e8cfe9fa53bd29637c0bfe6fc88494d2b10f/ZLUDA-windows-amd64.zip) had fixed the issue for me. 

Edit : I'm on hip 5.7.1

**Comment by LightningFlexors** [comment]
> I had this issue, I removed caches first and by using patchzluda2.bat and giving it the link for [zluda 3.7.2 ](https://github.com/lshqqytiger/ZLUDA/releases/download/rel.4f12e8cfe9fa53bd29637c0bfe6fc88494d2b10f/ZLUDA-windows-amd64.zip) had fixed the issue for me.
> 
> Edit : I'm on hip 5.7.1

the cmd says that patchzluda2.bat is specifically for HIP 6.x ????!
I have manualle put zldua 3.7.2 into the comfyu folder and now i don't get cublas error but the progress is stopping at 55% and it stops inside the CMD, leaving me back to the previos non-comfyui.bat situation. i also have HIP 5.7.1 and delted pip cache before manualle implementing zluda 3.7.2

after VAE loa device message it stopps

>got prompt
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Press any key . . .
F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda>

i'm not sure if there is something crazy going on ....
if i put zluda 3.7.2 into the comfyui folder and use patchzluda.bat ... the folder deletes itself and i'm not able to use comfyui.bat again!

new error, now it's not cublas.. i went back to 3.9.5 because the lower versions didn't work:

>FETCH ComfyRegistry Data: 5/89
got prompt
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
FETCH ComfyRegistry Data: 10/89
FETCH ComfyRegistry Data: 15/89
Exception Code: 0xC0000005
0x00007FFA9B193ECB, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFA9ABE0000) + 0x5B3ECB byte(s), ?_rowwise_prune@native@at@@YA?AV?$tuple@VTensor@at@@V12@@std@@AEBVTensor@2@0W4ScalarType@c10@@@Z() + 0x30B byte(s)
0x00007FFA9B1946CF, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFA9ABE0000) + 0x5B46CF byte(s), ?_local_scalar_dense_cpu@native@at@@YA?AVScalar@c10@@AEBVTensor@2@@Z() + 0x3F byte(s)
0x00007FFA9BD1EE5E, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFA9ABE0000) + 0x113EE5E byte(s), ?where_outf@cpu@at@@YAAEAVTensor@2@AEBV32@00AEAV32@@Z() + 0x22FE byte(s)
0x00007FFA9BCF5921, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFA9ABE0000) + 0x1115921 byte(s), ?bucketize_outf@cpu@at@@YAAEAVTensor@2@AEBV32@0_N1AEAV32@@Z() + 0x50421 byte(s)
0x00007FFA9B8E6494, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFA9ABE0000) + 0xD06494 byte(s), ?call@_local_scalar_dense@_ops@at@@SA?AVScalar@c10@@AEBVTensor@3@@Z() + 0x154 byte(s)
0x00007FFA9B19485F, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFA9ABE0000) + 0x5B485F byte(s), ?item@native@at@@YA?AVScalar@c10@@AEBVTensor@2@@Z() + 0x17F byte(s)
0x00007FFA9BFEEDEE, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFA9ABE0000) + 0x140EDEE byte(s), ?where@compositeimplicitautograd@at@@YA?AVTensor@2@AEBV32@AEBVScalar@c10@@1@Z() + 0x3D3E byte(s)
0x00007FFA9BFCEE11, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFA9ABE0000) + 0x13EEE11 byte(s), ?broadcast_to_symint@compositeimplicitautograd@at@@YA?AVTensor@2@AEBV32@V?$ArrayRef@VSymInt@c10@@@c10@@@Z() + 0x364A1 byte(s)
0x00007FFA9B7ADBA4, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFA9ABE0000) + 0xBCDBA4 byte(s), ?call@item@_ops@at@@SA?AVScalar@c10@@AEBVTensor@3@@Z() + 0x154 byte(s)
0x00007FFA9C3FC5D3, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFA9ABE0000) + 0x181C5D3 byte(s), ??$item@E@Tensor@at@@QEBAEXZ() + 0x13 byte(s)
0x00007FFB9C8D1B87, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_python.dll(0x00007FFB9C0E0000) + 0x7F1B87 byte(s), ?load@?$type_caster@VTensor@at@@X@detail@pybind11@@QEAA_NVhandle@3@_N@Z() + 0x2B7 byte(s)
0x00007FFB9C5083E0, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_python.dll(0x00007FFB9C0E0000) + 0x4283E0 byte(s), ?isMainPyInterpreter@@YA_NXZ() + 0x3BF0 byte(s)
0x00007FFB9E6AD2D2, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x2D2D2 byte(s), _PyLong_Frexp() + 0x2B2 byte(s)
0x00007FFB9E6AD319, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x2D319 byte(s), _PyLong_Frexp() + 0x2F9 byte(s)
0x00007FFB9E774D1D, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0xF4D1D byte(s), PyObject_CallObject() + 0x431 byte(s)
0x00007FFB9E6D1F7F, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x51F7F byte(s), _PyEval_EvalFrameDefault() + 0x535F byte(s)
0x00007FFB9E6CAE64, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x4AE64 byte(s), _PyFunction_Vectorcall() + 0x1A4 byte(s)
0x00007FFB9E7532CD, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0xD32CD byte(s), _PyLong_New() + 0x3A9 byte(s)
0x00007FFB9E6B4B04, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x34B04 byte(s), PySequence_GetItem() + 0x40 byte(s)
0x00007FFB9C913404, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_python.dll(0x00007FFB9C0E0000) + 0x833404 byte(s), ?getTHPMemoryFormat@utils@torch@@YAPEAU_object@@W4MemoryFormat@c10@@@Z() + 0x29C4 byte(s)
0x00007FFB9C9145F3, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_python.dll(0x00007FFB9C0E0000) + 0x8345F3 byte(s), ?getTHPMemoryFormat@utils@torch@@YAPEAU_object@@W4MemoryFormat@c10@@@Z() + 0x3BB3 byte(s)
0x00007FFB9C91297B, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_python.dll(0x00007FFB9C0E0000) + 0x83297B byte(s), ?getTHPMemoryFormat@utils@torch@@YAPEAU_object@@W4MemoryFormat@c10@@@Z() + 0x1F3B byte(s)
0x00007FFB9C586778, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\torch_python.dll(0x00007FFB9C0E0000) + 0x4A6778 byte(s), ??0?$THPPointer@UTHPGenerator@@@@QEAA@$$QEAV0@@Z() + 0x298D8 byte(s)
0x00007FFB9E6F75C6, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x775C6 byte(s), _PyArg_Parse_SizeT() + 0x86 byte(s)
0x00007FFB9E7750C4, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0xF50C4 byte(s), _PyObject_Call() + 0xAC byte(s)
0x00007FFBE945C611, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\safetensors\_safetensors_rust.pyd(0x00007FFBE9420000) + 0x3C611 byte(s), PyInit__safetensors_rust() + 0x18841 byte(s)
0x00007FFBE9440969, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\safetensors\_safetensors_rust.pyd(0x00007FFBE9420000) + 0x20969 byte(s)
0x00007FFBE942F276, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\safetensors\_safetensors_rust.pyd(0x00007FFBE9420000) + 0xF276 byte(s)
0x00007FFBE9422A32, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\safetensors\_safetensors_rust.pyd(0x00007FFBE9420000) + 0x2A32 byte(s)
0x00007FFBE942C112, F:\DF2\ComfyUI-Zluda\ComfyUI-Zluda\venv\Lib\site-packages\safetensors\_safetensors_rust.pyd(0x00007FFBE9420000) + 0xC112 byte(s)
0x00007FFB9E6AF8FE, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x2F8FE byte(s), _Py_HashDouble() + 0x11F2 byte(s)
0x00007FFB9E6CC13B, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x4C13B byte(s), PyObject_Vectorcall() + 0x5EB byte(s)
0x00007FFB9E6CD423, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x4D423 byte(s), _PyEval_EvalFrameDefault() + 0x803 byte(s)
0x00007FFB9E6CAE64, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x4AE64 byte(s), _PyFunction_Vectorcall() + 0x1A4 byte(s)
0x00007FFB9E715C25, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x95C25 byte(s), PyIter_Send() + 0x1E61 byte(s)
0x00007FFB9E774C6A, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0xF4C6A byte(s), PyObject_CallObject() + 0x37E byte(s)
0x00007FFB9E6D1F7F, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x51F7F byte(s), _PyEval_EvalFrameDefault() + 0x535F byte(s)
0x00007FFB9E6CAE64, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x4AE64 byte(s), _PyFunction_Vectorcall() + 0x1A4 byte(s)
0x00007FFB9E774CF3, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0xF4CF3 byte(s), PyObject_CallObject() + 0x407 byte(s)
0x00007FFB9E6D1F7F, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x51F7F byte(s), _PyEval_EvalFrameDefault() + 0x535F byte(s)
0x00007FFB9E6CAE64, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x4AE64 byte(s), _PyFunction_Vectorcall() + 0x1A4 byte(s)
0x00007FFB9E715C7F, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0x95C7F byte(s), PyIter_Send() + 0x1EBB byte(s)
0x00007FFB9E775073, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0xF5073 byte(s), _PyObject_Call() + 0x5B byte(s)
0x00007FFB9E732AA0, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0xB2AA0 byte(s), PyInterpreterState_Delete() + 0x3B4 byte(s)
0x00007FFB9E732A06, C:\Users\Strider_Hien\AppData\Local\Programs\Python\Python311\python311.dll(0x00007FFB9E680000) + 0xB2A06 byte(s), PyInterpreterState_Delete() + 0x31A byte(s)
0x00007FFC15EC1BB2, C:\Windows\System32\ucrtbase.dll(0x00007FFC15EA0000) + 0x21BB2 byte(s), _configthreadlocale() + 0x92 byte(s)
0x00007FFC16E07374, C:\Windows\System32\KERNEL32.DLL(0x00007FFC16DF0000) + 0x17374 byte(s), BaseThreadInitThunk() + 0x14 byte(s)
0x00007FFC1807CC91, C:\Windows\SYSTEM32\ntdll.dll(0x00007FFC18030000) + 0x4CC91 byte(s), RtlUserThreadStart() + 0x21 byte(s)

**Comment by Dwanvea** [comment]
>  " patchzluda2.bat is specifically for HIP 6.x ????!" 

That doesn't mean it's for 6 only. It's a manual patcher. 

> I have manualle put zldua 3.7.2 into the comfyu folder and now i don't get cublas error but the progress is stopping at 55% and it stops inside the CMD, leaving me back to the previos non-comfyui.bat situation.

Zluda 3.7.2 doesn't support hip 6. 

I wouldn't have both hip versions installed simultaneously; that's asking for trouble. You have to make your pick.

When I had this problem, I had deleted everything, including the GPU drivers. With DDU I reverted to adrenaline 25.4.1. Did a clean install of 5.7.1 and patched its libs ( because RX 5700 aka "gfx1010" is not officially supported, you need to do that as well, if your GPU is not supported). then I pacthed the zluda. Thats step by step how I managed to get it working. 

I tried running comfy in between the steps but the error was still the same until patching zluda. Btw every guide out there states you shouldn't have both HIP versions installed, before proceeding, try deleting one of them. Ensure PATH is set for your desired version of HIP👍

**Comment by LightningFlexors** [comment]
did you remove pip cache ?

**Comment by Dwanvea** [comment]
when I said Everything I meant it :D I deleted everything related to comfy so I could install it from scratch. So I deleted and re-installed python as well.

**Comment by 90FOKUS** [comment]
Using patchzluda2.bat worked for me to fix the cuda error. Now when generating though the image cant be displayed due to "Numpy is not available". I already deleted Numpy and reinstalled it but that didnt help, anyone knows how to fix that?

**Comment by Geekyboi6117** [comment]
> Using patchzluda2.bat worked for me to fix the cuda error. Now when generating though the image cant be displayed due to "Numpy is not available". I already deleted Numpy and reinstalled it but that didnt help, anyone knows how to fix that?

1.   activate venv 
2.   run install-n  even if you had installed 
3.  run patchzluda2 and chose latest stable build not nightly. idk ishqtiger says use nightly and paste custom 6.2 folder . did that but nightly build always fails. i ran stable build .
4. run comfyui-n 
5. enjoy 50% slow speed then old install method and unstable :( .
6. advise : use old method for now . triton , zluda and custom libs of gpus below 6000 series have issues

**Comment by WakeUpMorty** [comment]
Hi, so i got this error too, only way to remove it is to delete venv and install.bat again + you need to remove nodes that is not working that give you that error. For me it was 3d generations and chat ai. 

As i get it, after they updated comfy/python/Zluda most of nodes are broken (for me) as i understand it. Maybe in some time it will be resolved.
