### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by TeraBitGaming** [patientx/ComfyUI-Zluda#192]
I've gone through the motions, following the instructions and doing everything required, but i ran into issue after issue. The first big one about CUDA_VISIBLE_DEVICES i managed to solve by downgrading my drivers, but I don't know how to solve the current issue; I'm on a 9070xt, with the 6.2 rocm installed. I've supposedly successfully used the patcher2.bat, but now I'm getting this error when trying to start up comfyui:

`*** Starting the Comfyui-ZLUDA for the first time, please be patient...

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-06-23 23:15:16.925
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\Users\[my username]\Desktop\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: C:\Users\[my username]\Desktop\ComfyUI-Zluda
** ComfyUI Base Folder Path: C:\Users\[my username]\Desktop\ComfyUI-Zluda
** User directory: C:\Users\[my username]\Desktop\ComfyUI-Zluda\user
** ComfyUI-Manager config path: C:\Users\[my username]\Desktop\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: C:\Users\[my username]\Desktop\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   2.4 seconds: C:\Users\[my username]\Desktop\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Warning, you are using an old pytorch version and some ckpt/pt files might be loaded unsafely. Upgrading to 2.4 or above is recommended.

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.0
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.22.2
Installed version of comfyui-workflow-templates: 0.1.29
Installed version of av: 14.4.0
Installed version of comfyui-embedded-docs: 0.2.2
  ::  Package version check complete.
  ::  CUDA device detected: None
***--------------------------------------------------------***

Traceback (most recent call last):
  File "C:\Users\[my username]\Desktop\ComfyUI-Zluda\main.py", line 129, in <module>
    import execution
  File "C:\Users\[my username]\Desktop\ComfyUI-Zluda\execution.py", line 14, in <module>
    import comfy.model_management
  File "C:\Users\[my username]\Desktop\ComfyUI-Zluda\comfy\model_management.py", line 222, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\[my username]\Desktop\ComfyUI-Zluda\comfy\model_management.py", line 173, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[my username]\Desktop\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
    _lazy_init()
  File "C:\Users\[my username]\Desktop\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available`

I'm sure I fucked something up, but i can't tell what.

**Comment by patientx** [comment]
> The first big one about CUDA_VISIBLE_DEVICES i managed to solve by downgrading my drivers,

Why ? The new installer I specifically say use latest drivers... why downgrade drivers ? we are already using latest zluda etc... if anything your problem could be about libraries being needed , lower gpu's need libs but the newest stuff also needs them ... look at 

https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.2.4

there are libs for your gpu, read the instructions there. also read the instructions with the installation here, if you want you can read this 
"https://github.com/patientx/ComfyUI-Zluda/issues/188" follow new method and make sure you did every step, make sure you put libraries correctly.

**Comment by TeraBitGaming** [comment]
my issue ended up not being the downgraded drivers; i was using the 6.2 version and i set an environment variable called "CUDA_VISIBLE_DEVICES" since it errored out at that not being available; that error went away after downgrading my drivers, and the error i was experiencing here went away after i changed the environment variable to 0 (though removing it entirely is also an option).
