### ISSUE TITLE
cudnn_status: miopenStatusUnknownError

### ISSUE THREAD

**Issue by showerosu** [patientx/ComfyUI-Zluda#194]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

whenever trying to generate an image it gives me RuntimeError: CUDNN_BACKEND_OPERATIONGRAPH_DESCRIPTOR: cudnnFinalize FailedmiopenStatusInternalError cudnn_status: miopenStatusUnknownError
I'm running a 9070 xt (is this just not supported yet?), with stability matrix I have gone through the new installation steps from scratch multiple times, pls help

### Logs

```powershell
"prompt_id": "229b4bc9-2018-49a1-ab46-bd643e73655d",
  "node_id": "Sampler",
  "node_type": "KSampler",
  "executed": [
    "EmptyLatentImage",
    "NegativeCLIP_Base",
    "CheckpointLoader_Base",
    "PositiveCLIP_Base"
  ],
  "exception_message": "CUDNN_BACKEND_OPERATIONGRAPH_DESCRIPTOR: cudnnFinalize FailedmiopenStatusInternalError cudnn_status: miopenStatusUnknownError\n",
  "exception_type": "RuntimeError",
  "traceback": [
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\execution.py\u0022, line 361, in execute\n    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\execution.py\u0022, line 236, in get_output_data\n    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\execution.py\u0022, line 208, in _map_node_over_list\n    process_inputs(input_dict, i)\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\execution.py\u0022, line 197, in process_inputs\n    results.append(getattr(obj, func)(**inputs))\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\nodes.py\u0022, line 1516, in sample\n    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\nodes.py\u0022, line 1483, in common_ksampler\n    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\sample.py\u0022, line 45, in sample\n    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\samplers.py\u0022, line 1139, in sample\n    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\samplers.py\u0022, line 1029, in sample\n    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\samplers.py\u0022, line 1014, in sample\n    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\patcher_extension.py\u0022, line 111, in execute\n    return self.original(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\samplers.py\u0022, line 982, in outer_sample\n    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\samplers.py\u0022, line 965, in inner_sample\n    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\patcher_extension.py\u0022, line 111, in execute\n    return self.original(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\samplers.py\u0022, line 744, in sample\n    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\venv\\Lib\\site-packages\\torch\\utils\\_contextlib.py\u0022, line 116, in decorate_context\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\k_diffusion\\sampling.py\u0022, line 209, in sample_euler_ancestral\n    denoised = model(x, sigmas[i] * s_in, **extra_args)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\samplers.py\u0022, line 396, in __call__\n    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\samplers.py\u0022, line 945, in __call__\n    return self.predict_noise(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\samplers.py\u0022, line 948, in predict_noise\n    return sampling_function(self.inner_model, x, timestep, self.conds.get(\u0022negative\u0022, None), self.conds.get(\u0022positive\u0022, None), self.cfg, model_options=model_options, seed=seed)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\samplers.py\u0022, line 376, in sampling_function\n    out = calc_cond_batch(model, conds, x, timestep, model_options)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\samplers.py\u0022, line 206, in calc_cond_batch\n    return executor.execute(model, conds, x_in, timestep, model_options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\patcher_extension.py\u0022, line 111, in execute\n    return self.original(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\samplers.py\u0022, line 325, in _calc_cond_batch\n    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\model_base.py\u0022, line 152, in apply_model\n    return comfy.patcher_extension.WrapperExecutor.new_class_executor(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\patcher_extension.py\u0022, line 111, in execute\n    return self.original(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\model_base.py\u0022, line 190, in _apply_model\n    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\venv\\Lib\\site-packages\\torch\\nn\\modules\\module.py\u0022, line 1751, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\venv\\Lib\\site-packages\\torch\\nn\\modules\\module.py\u0022, line 1762, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\ldm\\modules\\diffusionmodules\\openaimodel.py\u0022, line 831, in forward\n    return comfy.patcher_extension.WrapperExecutor.new_class_executor(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\patcher_extension.py\u0022, line 111, in execute\n    return self.original(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\ldm\\modules\\diffusionmodules\\openaimodel.py\u0022, line 873, in _forward\n    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\ldm\\modules\\diffusionmodules\\openaimodel.py\u0022, line 59, in forward_timestep_embed\n    x = layer(x)\n        ^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\venv\\Lib\\site-packages\\torch\\nn\\modules\\module.py\u0022, line 1751, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\venv\\Lib\\site-packages\\torch\\nn\\modules\\module.py\u0022, line 1762, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\comfy\\ops.py\u0022, line 114, in forward\n    return super().forward(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\venv\\Lib\\site-packages\\torch\\nn\\modules\\conv.py\u0022, line 554, in forward\n    return self._conv_forward(input, self.weight, self.bias)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \u0022C:\\Users\\Joseph\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI-Zluda 3\\venv\\Lib\\site-packages\\torch\\nn\\modules\\conv.py\u0022, line 549, in _conv_forward\n    return F.conv2d(\n           ^^^^^^^^^\n"
  ],
  "current_inputs": {
    "model": [
      "\u003Ccomfy.model_patcher.ModelPatcher object at 0x000001811A1F6650\u003E"
    ],
    "seed": [
      899382829
    ],
    "steps": [
      28
    ],
    "cfg": [
      5.0
    ],
    "sampler_name": [
      "euler_ancestral"
    ],
    "scheduler": [
      "normal"
    ],
    "positive": [
      "[[tensor([[[-0.8204, -0.6623,  1.0530,  ...,  0.1084,  0.0610, -0.2731],\n         [-0.1362, -0.5252,  0.1942,  ...,  0.3196, -0.3095,  0.2135],\n         [ 0.4672, -0.0404, -0.4240,  ...,  0.8909,  0.2065, -0.2002],\n         ...,\n         [ 0.1077,  0.0581, -0.3867,  ...,  1.0150, -0.3444,  0.4258],\n         [ 0.1638, -0.0250, -0.1598,  ...,  0.2946, -1.2176, -0.5048],\n         [ 0.1310, -0.0063, -0.0911,  ...,  0.2211, -0.7874, -0.2825]]]), {\u0027pooled_output\u0027: tensor([[-0.2157,  0.8544,  0.1671,  ..., -0.3148, -0.4633,  0.0250]])}]]"
    ],
    "negative": [
      "[[tensor([[[-0.8204, -0.6623,  1.0530,  ...,  0.1084,  0.0610, -0.2731],\n         [ 0.4196, -0.1112,  0.3528,  ..., -0.2548, -0.3425,  0.2761],\n         [-0.0114,  1.3470,  0.1893,  ...,  0.9313, -0.7401, -0.3706],\n         ...,\n         [ 0.1447, -0.0444, -0.1910,  ...,  2.6896,  2.4423,  2.5960],\n         [ 0.1418, -0.0435, -0.1690,  ...,  3.8133,  4.0303, -1.4890],\n         [ 0.1177, -0.0286, -0.1419,  ...,  1.3017,  1.7893,  1.7775]]]), {\u0027pooled_output\u0027: tensor([[ 0.3880,  1.1774,  0.1486,  ..., -0.2298, -0.2531,  0.0887]])}]]"
    ],
    "latent_image": [
      "{\u0027samples\u0027: tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          ...,\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.]],\n\n         [[0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          ...,\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.]],\n\n         [[0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          ...,\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.]],\n\n         [[0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          ...,\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.]]]])}"
    ],
    "denoise": [
      1.0
    ]
  },
  "current_outputs": [
    "Sampler",
    "VAEDecode_1",
    "EmptyLatentImage",
    "NegativeCLIP_Base",
    "CheckpointLoader_Base",
    "PositiveCLIP_Base",
    "SaveImage"
  ],
  "timestamp": 1751103536761
}
```

### Other

running 25.5.1 pro edition adrenaline, windows 10, 5700x3d, 9070xt

**Comment by showerosu** [comment]
this is potentially the actual log you would want, not sure if it's the above one or this
Adding extra search path checkpoints C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\StableDiffusion
Adding extra search path diffusers C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\Diffusers
Adding extra search path loras C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\Lora
Adding extra search path loras C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\LyCORIS
Adding extra search path clip C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\TextEncoders
Adding extra search path clip_vision C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\ClipVision
Adding extra search path embeddings C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\Embeddings
Adding extra search path vae C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\VAE
Adding extra search path vae_approx C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\ApproxVAE
Adding extra search path controlnet C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\ControlNet
Adding extra search path controlnet C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\T2IAdapter
Adding extra search path gligen C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\GLIGEN
Adding extra search path upscale_models C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\ESRGAN
Adding extra search path upscale_models C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\RealESRGAN
Adding extra search path upscale_models C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\SwinIR
Adding extra search path hypernetworks C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\Hypernetwork
Adding extra search path ipadapter C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\IpAdapter
Adding extra search path ipadapter C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\IpAdapters15
Adding extra search path ipadapter C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\IpAdaptersXl
Adding extra search path prompt_expansion C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\PromptExpansion
Adding extra search path ultralytics C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\Ultralytics
Adding extra search path ultralytics_bbox C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\Ultralytics\bbox
Adding extra search path ultralytics_segm C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\Ultralytics\segm
Adding extra search path sams C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\Sams
Adding extra search path diffusion_models C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Models\DiffusionModels
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-06-28 17:35:17.780
** Platform: Windows
** Python version: 3.11.12 (main, Apr  9 2025, 04:03:34) [MSC v.1943 64 bit (AMD64)]
** Python executable: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\venv\Scripts\python.exe
** ComfyUI Path: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3
** ComfyUI Base Folder Path: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3
** User directory: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\user
** ComfyUI-Manager config path: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\user\default\ComfyUI-Manager\config.ini
** Log path: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\user\comfyui.log

Prestartup times for custom nodes:
   2.6 seconds: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.23.4
Installed version of comfyui-workflow-templates: 0.1.30
Installed version of av: 14.4.0
Installed version of comfyui-embedded-docs: 0.2.3
  ::  Package version check complete.

  ::  ------------------------ ZLUDA -----------------------  ::  
  ::  Triton core imported successfully
  ::  Running Triton kernel test...
  ::  Triton kernel test passed successfully
  ::  Triton initialized successfully
  ::  Patching ONNX Runtime for ZLUDA — disabling CUDA EP.
  ::  Using ZLUDA with device: AMD Radeon RX 9070 XT [ZLUDA]
  ::  Applying core ZLUDA patches...
  ::  Initializing Triton optimizations
  ::  Configuring Triton device properties...
  ::  Triton device properties configured
  ::  Flash attention components found
  ::  AMD flash attention enabled successfully
  ::  Configuring PyTorch backends...
  ::  Disabled CUDA flash attention
  ::  Enabled math attention fallback
  ::  ZLUDA initialization complete
  ::  ------------------------ ZLUDA -----------------------  ::  

Total VRAM 16304 MB, total RAM 32690 MB
pytorch version: 2.7.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 9070 XT [ZLUDA] : native
Using sage attention
Python version: 3.11.12 (main, Apr  9 2025, 04:03:34) [MSC v.1943 64 bit (AMD64)]
ComfyUI version: 0.3.43
ComfyUI frontend version: 1.23.4
[Prompt Server] web root: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\venv\Lib\site-packages\comfyui_frontend_package\static
### Loading: ComfyUI-Manager (V3.33.3)
[ComfyUI-Manager] network_mode: public
[ComfyUI-Manager] Since --preview-method is set, ComfyUI-Manager's preview method feature will be ignored.
### ComfyUI Revision: 4505 [14864643] | Released on '2025-06-28'

Import times for custom nodes:
   0.0 seconds: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\custom_nodes\cfz_cudnn.toggle.py
   0.0 seconds: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\custom_nodes\cfz_vae_loader.py
   0.0 seconds: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\custom_nodes\cfz_patcher.py
   0.0 seconds: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\custom_nodes\ComfyUI-deepcache
   0.5 seconds: C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\custom_nodes\ComfyUI-Manager

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Context impl SQLiteImpl.
Will assume non-transactional DDL.
No target revision found.
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH ComfyRegistry Data: 5/90
FETCH ComfyRegistry Data: 10/90
FETCH ComfyRegistry Data: 15/90
FETCH ComfyRegistry Data: 20/90
FETCH ComfyRegistry Data: 25/90
FETCH ComfyRegistry Data: 30/90
FETCH ComfyRegistry Data: 35/90
FETCH ComfyRegistry Data: 40/90
FETCH ComfyRegistry Data: 45/90
FETCH ComfyRegistry Data: 50/90
FETCH ComfyRegistry Data: 55/90
FETCH ComfyRegistry Data: 60/90
FETCH ComfyRegistry Data: 65/90
FETCH ComfyRegistry Data: 70/90
FETCH ComfyRegistry Data: 75/90
FETCH ComfyRegistry Data: 80/90
FETCH ComfyRegistry Data: 85/90
FETCH ComfyRegistry Data: 90/90
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Requested to load SDXLClipModel
loaded completely 9.5367431640625e+25 1560.802734375 True
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
Requested to load SDXL
loaded completely 12721.20830078125 4897.0483474731445 True
MIOpen(HIP): Error [Compile] 'hiprtcCompileProgram(prog.get(), c_options.size(), c_options.data())' naive_conv.cpp: HIPRTC_ERROR_COMPILATION (6)
MIOpen(HIP): Error [BuildHip] HIPRTC status = HIPRTC_ERROR_COMPILATION (6), source file: naive_conv.cpp
MIOpen(HIP): Warning [BuildHip] warning: HIPRTC error log empty
MIOpen Error: D:/ML/amdgpu/repositories/MIOpen/src/hipoc/hipoc_program.cpp:299: Code object build failed. Source: naive_conv.cpp
  0%|          | 0/28 [00:00<?, ?it/s]
!!! Exception during processing !!! CUDNN_BACKEND_OPERATIONGRAPH_DESCRIPTOR: cudnnFinalize FailedmiopenStatusInternalError cudnn_status: miopenStatusUnknownError
Traceback (most recent call last):
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\execution.py", line 361, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\execution.py", line 236, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\execution.py", line 208, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\execution.py", line 197, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\nodes.py", line 1516, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\nodes.py", line 1483, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\sample.py", line 45, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\samplers.py", line 1139, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\samplers.py", line 1029, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\samplers.py", line 1014, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\samplers.py", line 982, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\samplers.py", line 965, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\samplers.py", line 744, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\k_diffusion\sampling.py", line 209, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\samplers.py", line 396, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\samplers.py", line 945, in __call__
    return self.predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\samplers.py", line 948, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\samplers.py", line 376, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\samplers.py", line 206, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\samplers.py", line 325, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\model_base.py", line 152, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\model_base.py", line 190, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 831, in forward
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 873, in _forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 59, in forward_timestep_embed
    x = layer(x)
        ^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\comfy\ops.py", line 114, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\venv\Lib\site-packages\torch\nn\modules\conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joseph\AppData\Roaming\StabilityMatrix\Packages\ComfyUI-Zluda 3\venv\Lib\site-packages\torch\nn\modules\conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: CUDNN_BACKEND_OPERATIONGRAPH_DESCRIPTOR: cudnnFinalize FailedmiopenStatusInternalError cudnn_status: miopenStatusUnknownError

Prompt executed in 4.32 seconds

**Comment by patientx** [comment]
I see you are using stability matrix, do they started using the updated setup now ? 

Do you have 

`set MIOPEN_FIND_MODE=2`
`set MIOPEN_LOG_LEVEL=3`

on your starter batch like our official comfyui-n.bat (if they are not using it) ? It is hard for me to find the problem when you can pass the triton tests and fail there ... 

FOR TEMPORARY SOLUTION : 
use cudnn toggle node and disable it at any earlier part of your workflow. (for example between model - ksampler or lora, or between clip to prompt etc) It would keep it disabled in that comfy run , or if you use the node again and set it enabled.

**Comment by showerosu** [comment]
the temporary solution worked for me, however it's a consistent 1.27s/it at 1024x1024
is this speed to be expected or is something not activating properly 
or is just disabling cudnn stopping any of the optimizers from working
either way is there anything i can do to get this to work properly? or just faster?

**Comment by patientx** [comment]
did you get the libs from here : https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.2.4
they are needed for the old gpus AND very new ones like yours, to be honest I hear nobody with the newest 9000 series is happy with the performance, as you can read in that git repo, the libs are unoptimized atm... normally your gpu would be supported by the rocm itself and you won't need this but they didn't release it officially yet.

 OR 

you can try native route here : 

https://github.com/patientx/ComfyUI-Zluda/issues/170

I have a mini guide for some gpu's there but unfortunately not your gpu. In that thread you would have to use the first git repo not the one I wrote a guide for.

**Comment by showerosu** [comment]
i didn't have those libs already, downloaded them and chucked them where they needed to go but didn't change anything, unfortunately can't do anything more because sleep but would a fresh install fix it you think?

**Comment by patientx** [comment]
yes try a fresh install and put those libraries after hip addon is added.

**Comment by x98company** [comment]
is work for me put those libraries  [rocm.gfx1201.for.hip.skd.6.2.4-no-optimized.7z](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/download/v0.6.2.4/rocm.gfx1201.for.hip.skd.6.2.4-no-optimized.7z)

![Image](https://github.com/user-attachments/assets/c5d51460-7dd2-4fd1-bf43-77c09c90d387)

**Comment by showerosu** [comment]
update: after uninstalling hipsdk 6.2.4 i reinstalled, added the extension for this zluda package and then added the gfx 1201 unoptimized library it now can run with cudnn if i run the comfyui-n within the packages folder, still can't use cudnn if i run it through stability matrix interface, weirdly enough the stability matrix without cudnn works faster????? the speeds are still absolute dogshit for both though, through stability matrix i get 1.25s/it and if i run it from the package it is 1.52s/it. I don't even know if there is anything to do here anymore or if something is still not working correctly, my model im using is sdxl if that matters

**Comment by patientx** [comment]
AGAIN the libs for your gpu are not really good atm. Wait for amd to add them to hip natively. Sad but this the truth. Look at the x98company's screenshot above he seems to be getting that speed for sd1.5 @ 1024x1024 , so yes bad performance.

**Comment by showerosu** [comment]
yep, thank you for all of your help, i'll close this issue now
