### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by ghostbirdlary** [patientx/ComfyUI-Zluda#201]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

just to preface, i have zero experience with this kind of stuff, i just want to locally generate images :/

i manage to install and run it ok, but it picks up integrated graphics, and then i did the HIP_VISABLE_DEVICES=1 and then it came out with the error RuntimeError: No CUDA GPUs are available.

### Logs

```powershell

```

### Other

C:\Users\hbak9\ComfyUI-Zluda>comfyui.bat
*** Checking and updating to new version if possible
Already up to date.

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-07-01 00:15:34.226
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\Users\hbak9\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: C:\Users\hbak9\ComfyUI-Zluda
** ComfyUI Base Folder Path: C:\Users\hbak9\ComfyUI-Zluda
** User directory: C:\Users\hbak9\ComfyUI-Zluda\user
** ComfyUI-Manager config path: C:\Users\hbak9\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: C:\Users\hbak9\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   2.3 seconds: C:\Users\hbak9\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Warning, you are using an old pytorch version and some ckpt/pt files might be loaded unsafely. Upgrading to 2.4 or above is recommended.

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.23.4
Installed version of comfyui-workflow-templates: 0.1.30
Installed version of av: 14.4.0
Installed version of comfyui-embedded-docs: 0.2.3
  ::  Package version check complete.
  ::  CUDA device detected: None
***--------------------------------------------------------***

Traceback (most recent call last):
  File "C:\Users\hbak9\ComfyUI-Zluda\main.py", line 132, in <module>
    import execution
  File "C:\Users\hbak9\ComfyUI-Zluda\execution.py", line 14, in <module>
    import comfy.model_management
  File "C:\Users\hbak9\ComfyUI-Zluda\comfy\model_management.py", line 222, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hbak9\ComfyUI-Zluda\comfy\model_management.py", line 173, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hbak9\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
    _lazy_init()
  File "C:\Users\hbak9\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
Press any key to continue . . .

**Comment by patientx** [comment]
Which gpu

**Comment by ghostbirdlary** [comment]
9070xt

**Comment by patientx** [comment]
get the libraries for your gpu.

**Comment by ghostbirdlary** [comment]
i think i have it, its this right? im on windows

C:\Program Files\AMD\ROCm\5.7

![Image](https://github.com/user-attachments/assets/8cc3cc98-3f17-4fcb-8d84-2b6e0a358b8d)

**Comment by SlapOLantern** [comment]
I am also having this exact same error and I have the same GPU, the 9070 XT. I also have those folders.

**Comment by patientx** [comment]
we don't have libraries for 9070xt for hip 5.7  , so use new install method and read the instructions.

**Comment by ghostbirdlary** [comment]
so start over and use 6.2.4?

**Comment by ghostbirdlary** [comment]
ok i think i installed the other version correctly and now i get this 


C:\Users\hbak9\ComfyUI-Zluda>comfyui.bat
*** Checking and updating to new version if possible
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 43 (delta 14), reused 8 (delta 8), pack-reused 20 (from 3)
Unpacking objects: 100% (43/43), 54.98 KiB | 439.00 KiB/s, done.
From https://github.com/patientx/ComfyUI-Zluda
   a824674b..ac99b100  master     -> origin/master
Updating a824674b..ac99b100
Fast-forward
 README.md                            |  5 +++
 comfy/k_diffusion/sampling.py        | 73 +++++++++++++++++++++---------------
 comfy/ops.py                         |  9 +++--
 comfy_extras/nodes_custom_sampler.py | 52 ++++++++++++++++++++++++-
 comfy_extras/nodes_load_3d.py        | 20 +++++++++-
 comfy_extras/nodes_perpneg.py        |  7 ++++
 comfy_extras/nodes_tcfg.py           | 71 +++++++++++++++++++++++++++++++++++
 nodes.py                             |  1 +
 requirements.txt                     |  2 +-
 9 files changed, 201 insertions(+), 39 deletions(-)
 create mode 100644 comfy_extras/nodes_tcfg.py

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-07-02 05:32:29.513
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\Users\hbak9\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: C:\Users\hbak9\ComfyUI-Zluda
** ComfyUI Base Folder Path: C:\Users\hbak9\ComfyUI-Zluda
** User directory: C:\Users\hbak9\ComfyUI-Zluda\user
** ComfyUI-Manager config path: C:\Users\hbak9\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: C:\Users\hbak9\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   2.5 seconds: C:\Users\hbak9\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Warning, you are using an old pytorch version and some ckpt/pt files might be loaded unsafely. Upgrading to 2.4 or above is recommended.

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.23.4
Installed version of comfyui-workflow-templates: 0.1.30

comfyui-workflow-templates outdated. Upgraded to 0.1.31.
Installed version of av: 14.4.0
Installed version of comfyui-embedded-docs: 0.2.3
  ::  Package version check complete.
C:\Users\hbak9\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py:118: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ..\c10\cuda\CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
  ::  CUDA device detected: None
***--------------------------------------------------------***

Traceback (most recent call last):
  File "C:\Users\hbak9\ComfyUI-Zluda\main.py", line 132, in <module>
    import execution
  File "C:\Users\hbak9\ComfyUI-Zluda\execution.py", line 14, in <module>
    import comfy.model_management
  File "C:\Users\hbak9\ComfyUI-Zluda\comfy\model_management.py", line 222, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hbak9\ComfyUI-Zluda\comfy\model_management.py", line 173, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hbak9\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
    _lazy_init()
  File "C:\Users\hbak9\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
Press any key to continue . . .

**Comment by patientx** [comment]
Your installation is wrong, you should have latest torch installed so this warning "Warning, you are using an old pytorch version and some ckpt/pt files might be loaded unsafely. Upgrading to 2.4 or above is recommended." Shouldn't appear if you have installed it correctly

**Comment by ghostbirdlary** [comment]
this is the correct pytorch download place correct? i download this and update to 25.1.1 which is above 24.0 and i still get error

![Image](https://github.com/user-attachments/assets/0bc85df2-0a45-4f9d-a815-c4332e2e0d8e)

C:\Users\hbak9>python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\hbak9\appdata\local\programs\python\python311\lib\site-packages (24.0)
Collecting pip
  Using cached pip-25.1.1-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-25.1.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0
Successfully installed pip-25.1.1

C:\Users\hbak9>cd ComfyUI-Zluda

C:\Users\hbak9\ComfyUI-Zluda>comfyui.bat
*** Checking and updating to new version if possible
Already up to date.

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-07-02 13:41:34.485
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\Users\hbak9\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: C:\Users\hbak9\ComfyUI-Zluda
** ComfyUI Base Folder Path: C:\Users\hbak9\ComfyUI-Zluda
** User directory: C:\Users\hbak9\ComfyUI-Zluda\user
** ComfyUI-Manager config path: C:\Users\hbak9\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: C:\Users\hbak9\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   1.6 seconds: C:\Users\hbak9\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Warning, you are using an old pytorch version and some ckpt/pt files might be loaded unsafely. Upgrading to 2.4 or above is recommended.

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.23.4
Installed version of comfyui-workflow-templates: 0.1.31
Installed version of av: 14.4.0
Installed version of comfyui-embedded-docs: 0.2.3
  ::  Package version check complete.
C:\Users\hbak9\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py:118: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ..\c10\cuda\CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
  ::  CUDA device detected: None
***--------------------------------------------------------***

Traceback (most recent call last):
  File "C:\Users\hbak9\ComfyUI-Zluda\main.py", line 132, in <module>
    import execution
  File "C:\Users\hbak9\ComfyUI-Zluda\execution.py", line 14, in <module>
    import comfy.model_management
  File "C:\Users\hbak9\ComfyUI-Zluda\comfy\model_management.py", line 222, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hbak9\ComfyUI-Zluda\comfy\model_management.py", line 173, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hbak9\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
    _lazy_init()
  File "C:\Users\hbak9\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
Press any key to continue . . .

**Comment by patientx** [comment]
WHY ARE YOU DOWNLOADING / INSTALLING PYTORCH manually ? Just follow the guide. Add your gpu's library as instructed, add the necessary hip addon in the correct place and everything installs and works ...

**Comment by ghostbirdlary** [comment]
sorry, i have no experience with this kind of stuff.
 i didnt see how to make pytorch update otherwise. do you have any idea what i did wrong to make that error? because i thought i was doing it correctly but apparently im doing something wrong.

**Comment by TheActualJeff** [comment]
I was having the same issue until I ran patchzluda2.bat and used this https://github.com/lshqqytiger/ZLUDA/releases/download/rel.5e717459179dc272b7d7d23391f0fad66c7459cf/ZLUDA-windows-rocm6-amd64.zip link when the patch asked for it.

Seems to be working now.

**Comment by patientx** [comment]
> sorry, i have no experience with this kind of stuff. i didnt see how to make pytorch update otherwise. do you have any idea what i did wrong to make that error? because i thought i was doing it correctly but apparently im doing something wrong.

Just follow the installer guide step by step here more focused one : https://github.com/patientx/ComfyUI-Zluda/issues/188

Do the preinstall part then move onto new install method

**Comment by ghostbirdlary** [comment]
should i get rid of some stuff i installed by doing the old steps or should it be fine?

**Comment by patientx** [comment]
> should i get rid of some stuff i installed by doing the old steps or should it be fine?

Start from scratch , delete previous install folder etc. And please do every step. This works for everyone, people insist it doesn't for days even weeks then later they come back and say "yeah , I didn't do that part "assumed" it wasn't important." ... They do that and suddenly it works ...

**Comment by quanzs538** [comment]
> 我应该通过执行旧步骤来删除我安装的一些东西，还是应该没问题？

安说明文件一步一步安装肯定没问题,你安装就有问题,不要偷懒,不要减少步骤

**Comment by ghostbirdlary** [comment]
ok, i thought i got it working, following the steps, but when i tried to generate the image for the basic text to image for a test i get this error. i even disabled integrated graphics, as someone said that would fix it but it did not.

[ComfyUI-Manager] All startup tasks have been completed.
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load SD1ClipModel
loaded completely 14401.2 235.84423828125 True

rocBLAS error: Cannot read C:\Program Files\AMD\ROCm\6.2\bin\/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1201

rocBLAS error: Could not initialize Tensile host:
regex_error(error_backref): The expression contained an invalid back reference.
Press any key to continue . . .

**Comment by ghostbirdlary** [comment]
should i open a new issue, since this is kind of a different issue or just stay in this one?

**Comment by patientx** [comment]
Isn't it still the same error ... Is it still " CUDA device detected: None " or do you see a device identification ? AND are you sure you got your libraries for your gpu ? As instructed in this step : 

from [likelovewant Repository](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.2.4) (for hip 6.2.4)

Go to folder "C:\Program Files\AMD\ROCm\5.7\bin\rocblas", (or 6.2 if you have installed that) there would be a "library" folder, backup the files inside to somewhere else.
Open your downloaded optimized library archive and put them inside the library folder (overwriting if necessary): "C:\Program Files\AMD\ROCm\5.7\bin\rocblas\library" (or 6.2 if you have installed that)
There could be a rocblas.dll file in the archive as well, if it is present then copy it inside "C:\Program Files\AMD\ROCm\5.7\bin\rocblas" (or 6.2 if you have installed that)

I think your gpu needs this libraries : https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/download/v0.6.2.4/rocm.gfx1201.for.hip.skd.6.2.4-no-optimized.7z

**Comment by ghostbirdlary** [comment]
i think its working now, thanks for the help :)
