### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by L1SM0K** [patientx/ComfyUI-Zluda#236]
I have this problem, im using an rx6650xt

Microsoft Windows [Versión 10.0.26100.4770]
(c) Microsoft Corporation. Todos los derechos reservados.

C:\Users\Alexx>cd ComfyUI-Zluda

C:\Users\Alexx\ComfyUI-Zluda>comfyui.bat
*** Checking and updating to new version if possible
Already up to date.

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-07-31 20:06:59.834
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\Users\Alexx\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: C:\Users\Alexx\ComfyUI-Zluda
** ComfyUI Base Folder Path: C:\Users\Alexx\ComfyUI-Zluda
** User directory: C:\Users\Alexx\ComfyUI-Zluda\user
** ComfyUI-Manager config path: C:\Users\Alexx\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: C:\Users\Alexx\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   2.2 seconds: C:\Users\Alexx\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Warning, you are using an old pytorch version and some ckpt/pt files might be loaded unsafely. Upgrading to 2.4 or above is recommended.

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.23.4
Installed version of comfyui-workflow-templates: 0.1.44
Installed version of av: 15.0.0
Installed version of comfyui-embedded-docs: 0.2.4
  ::  Package version check complete.
C:\Users\Alexx\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py:118: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ..\c10\cuda\CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
  ::  CUDA device detected: None
***--------------------------------------------------------***

Traceback (most recent call last):
  File "C:\Users\Alexx\ComfyUI-Zluda\main.py", line 147, in <module>
    import execution
  File "C:\Users\Alexx\ComfyUI-Zluda\execution.py", line 15, in <module>
    import comfy.model_management
  File "C:\Users\Alexx\ComfyUI-Zluda\comfy\model_management.py", line 234, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alexx\ComfyUI-Zluda\comfy\model_management.py", line 184, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alexx\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
    _lazy_init()
  File "C:\Users\Alexx\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
Presione una tecla para continuar . . .

**Comment by patientx** [comment]
If you have an integrated GPU by AMD (e.g. AMD Radeon(TM) Graphics) you need to add HIP_VISIBLE_DEVICES=1 to your environment variables. Other possible variables to use : ROCR_VISIBLE_DEVICES=1 HCC_AMDGPU_TARGET=1 . This basically tells it to use 1st gpu -this number could be different if you have multiple gpu's- Otherwise it will default to using your iGPU, which will most likely not work. This behavior is caused by a bug in the ROCm-driver.

these can be tried by putting them on comfyui-n.bat (make a copy and use them)
Try putting the command(s) on top of the file, after "@echo off"

set HIP_VISIBLE_DEVICES=1
set ROCR_VISIBLE_DEVICES=1
set HCC_AMDGPU_TARGET=1

you don't need all of them , these are alternative commands for the task.

**Comment by Geekyboi6117** [comment]
had this in my bucket of problems . 
1 run patchzluda2 (you should have romc 6.2) 
2 use latest stable build not nightly .(you are using comfyui.bat which means triton not  install . good  because new install method is extremly buggy. most issues open now are of this)
3 after patching with latest zluda stable build re run install.bat (if you had pip cache then you can del venv . or else del venv will download many packages and take time...)
hope that helps

**Comment by L1SM0K** [comment]
Thanks to both, sadly i tried both things and still have the same problem, i dont have an integrated gpu, only the rx6650xt

**Comment by matjav1234** [comment]
I'm having exactly the same error since Comfy-UI updated today

**Comment by patientx** [comment]
To try once again , I removed everything and did a complete re-install , this includes deleting zluda / triton / miopen caches and deleting pip cache also.

Of course I uninstalled hip 6.2 as well and after that even made sure there is no "C:\Program Files\AMD\ROCm" folder or anything under it, just deleted remaining files.

I have an rx 6800 which doesn't require libraries other than that everything should be identical , 

- I am using windows 10. 
- Python 3.11.9.
- Installed hip 6.2 THEN re-downloaded the addon from the available url's for "installing everything from a new users perspective" sake, put it into the hip folder. MADE SURE the path's are correctly set by going into enviromental variables and checking both HIP_PATH, HIP_PATH_62 (both should be C:\Program Files\AMD\ROCm\6.2) on system variables and MADE SURE there is an entry on "Path" in system variables below those mentioned,  "C:\Program Files\AMD\ROCm\6.2\bin"
- CLONED THE comfyui-zluda folder to OUTSIDE a user directory. NEVER use windows , desktop , program files, user ... directories. Use C:\ or if you have D:\ , yes clone directly into the main folder on the drive so it would be c:\comfyui-zluda\ when cloned for example. 
-Used "install-n.bat" and after the app first started WHILE RECOGNISING my gpu CORRECTLY 

Total VRAM 16368 MB, total RAM 32690 MB
pytorch version: 2.7.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6800 [ZLUDA] : native
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention

I closed it, copied "libs" folder from "C:\Users\myusername\AppData\Local\Programs\Python\Python311" (that would be 310 if you are using python 3.10 or 3.12 etc. BUT remember I suggest using at least 3.11 for a while now.)

Re-run comfyui-zluda , and this is the complete startup log : 

--------------------------------------------------
*** Checking and updating to new version if possible
Already up to date.

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-08-02 15:22:28.736
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: D:\sd\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: D:\sd\ComfyUI-Zluda
** ComfyUI Base Folder Path: D:\sd\ComfyUI-Zluda
** User directory: D:\sd\ComfyUI-Zluda\user
** ComfyUI-Manager config path: D:\sd\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: D:\sd\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   3.0 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.23.4
Installed version of comfyui-workflow-templates: 0.1.45
Installed version of av: 15.0.0
Installed version of comfyui-embedded-docs: 0.2.4
  ::  Package version check complete.

  ::  ------------------------ ZLUDA -----------------------  ::
  ::  Triton core imported successfully
  ::  Running Triton kernel test...
Using HIP SDK Clang.
In file included from D:\idm-temp\temp\tmpau61v5lh\main.c:8:
In file included from C:\Users\myusername\AppData\Local\Programs\Python\Python311\Include\Python.h:87:
C:\Users\myusername\AppData\Local\Programs\Python\Python311\Include\cpython/pytime.h:184:12: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility]
  184 |     struct timeval *tv,
      |            ^
C:\Users\myusername\AppData\Local\Programs\Python\Python311\Include\cpython/pytime.h:190:12: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility]
  190 |     struct timeval *tv,
      |            ^
2 warnings generated.
Using HIP SDK Clang.
In file included from D:\idm-temp\temp\tmpjul7ui0z\main.c:4:
In file included from C:\Users\myusername\AppData\Local\Programs\Python\Python311\Include\Python.h:87:
C:\Users\myusername\AppData\Local\Programs\Python\Python311\Include\cpython/pytime.h:184:12: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility]
  184 |     struct timeval *tv,
      |            ^
C:\Users\myusername\AppData\Local\Programs\Python\Python311\Include\cpython/pytime.h:190:12: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility]
  190 |     struct timeval *tv,
      |            ^
2 warnings generated.
Compilation is in progress. Please wait...
Compilation is in progress. Please wait...
Compilation is in progress. Please wait...
Compilation is in progress. Please wait...
Compilation is in progress. Please wait...
Compilation is in progress. Please wait...
Compilation is in progress. Please wait...
  ::  Triton kernel test passed successfully
  ::  Triton initialized successfully
  ::  Patching ONNX Runtime for ZLUDA — disabling CUDA EP.
  ::  Using ZLUDA with device: AMD Radeon RX 6800 [ZLUDA]
  ::  Applying core ZLUDA patches...
  ::  Initializing Triton optimizations
  ::  Configuring Triton device properties...
  ::  Triton device properties configured
  ::  Flash attention components found
  ::  AMD flash attention enabled successfully
  ::  Configuring PyTorch backends...
  ::  Disabled CUDA flash attention
  ::  Enabled math attention fallback
  ::  ZLUDA initialization complete
  ::  ------------------------ ZLUDA -----------------------  ::

Total VRAM 16368 MB, total RAM 32690 MB
pytorch version: 2.7.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6800 [ZLUDA] : native
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
ComfyUI version: 0.3.48
ComfyUI frontend version: 1.23.4
[Prompt Server] web root: D:\sd\ComfyUI-Zluda\venv\Lib\site-packages\comfyui_frontend_package\static
### Loading: ComfyUI-Manager (V3.35)
[ComfyUI-Manager] network_mode: public
### ComfyUI Revision: 4695 [9a7b5128] | Released on '2025-08-02'

Import times for custom nodes:
   0.0 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\cfz_cudnn.toggle.py
   0.0 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\cfz_vae_loader.py
   0.0 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\cfz_patcher.py
   0.0 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\ComfyUI-deepcache
   0.5 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Context impl SQLiteImpl.
Will assume non-transactional DDL.
No target revision found.
Starting server

To see the GUI go to: http://127.0.0.1:8188
------------------------------------------------

as you can see it compiles a bit at triton test stage, and after it completes it is ready to run, I loaded the default workflow, put an sd 1.5 model and started generating. AGAIN it compiles a bit more - does it with each model type at least once-

My point is : if you follow every step , make sure that the path's are correctly set up, visual studio correctly set up, the libraries for your gpu correctly copied -if necessary- , the "libs" folder correctly copied from the python directory into venv of comfyui-zluda, EVERYTHING SHOULD WORK.

**Comment by Geekyboi6117** [comment]
> To try once again , I removed everything and did a complete re-install , this includes deleting zluda / triton / miopen caches and deleting pip cache also.
> 
> Of course I uninstalled hip 6.2 as well and after that even made sure there is no "C:\Program Files\AMD\ROCm" folder or anything under it, just deleted remaining files.
> 
> I have an rx 6800 which doesn't require libraries other than that everything should be identical ,
> 
> * I am using windows 10.
> * Python 3.11.9.
> * Installed hip 6.2 THEN re-downloaded the addon from the available url's for "installing everything from a new users perspective" sake, put it into the hip folder. MADE SURE the path's are correctly set by going into enviromental variables and checking both HIP_PATH, HIP_PATH_62 (both should be C:\Program Files\AMD\ROCm\6.2) on system variables and MADE SURE there is an entry on "Path" in system variables below those mentioned,  "C:\Program Files\AMD\ROCm\6.2\bin"
> * CLONED THE comfyui-zluda folder to OUTSIDE a user directory. NEVER use windows , desktop , program files, user ... directories. Use C:\ or if you have D:\ , yes clone directly into the main folder on the drive so it would be c:\comfyui-zluda\ when cloned for example.
>   -Used "install-n.bat" and after the app first started WHILE RECOGNISING my gpu CORRECTLY
> 
> Total VRAM 16368 MB, total RAM 32690 MB pytorch version: 2.7.0+cu118 Set vram state to: NORMAL_VRAM Device: cuda:0 AMD Radeon RX 6800 [ZLUDA] : native Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
> 
> I closed it, copied "libs" folder from "C:\Users\myusername\AppData\Local\Programs\Python\Python311" (that would be 310 if you are using python 3.10 or 3.12 etc. BUT remember I suggest using at least 3.11 for a while now.)
> 
> Re-run comfyui-zluda , and this is the complete startup log :
> 
> *** Checking and updating to new version if possible Already up to date.
> 
> [START] Security scan [DONE] Security scan
> 
> ## ComfyUI-Manager: installing dependencies done.
> ** ComfyUI startup time: 2025-08-02 15:22:28.736 ** Platform: Windows ** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr 2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] ** Python executable: D:\sd\ComfyUI-Zluda\venv\Scripts\python.exe ** ComfyUI Path: D:\sd\ComfyUI-Zluda ** ComfyUI Base Folder Path: D:\sd\ComfyUI-Zluda ** User directory: D:\sd\ComfyUI-Zluda\user ** ComfyUI-Manager config path: D:\sd\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini ** Log path: D:\sd\ComfyUI-Zluda\user\comfyui.log
> 
> Prestartup times for custom nodes: 3.0 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
> 
> Checkpoint files will always be loaded safely.
> 
> :: Checking package versions... Found pydantic: 2.11.7, pydantic-settings: 2.10.1 :: Pydantic packages are compatible, skipping reinstall Installed version of comfyui-frontend-package: 1.23.4 Installed version of comfyui-workflow-templates: 0.1.45 Installed version of av: 15.0.0 Installed version of comfyui-embedded-docs: 0.2.4 :: Package version check complete.
> 
> :: ------------------------ ZLUDA ----------------------- :: :: Triton core imported successfully :: Running Triton kernel test... Using HIP SDK Clang. In file included from D:\idm-temp\temp\tmpau61v5lh\main.c:8: In file included from C:\Users\myusername\AppData\Local\Programs\Python\Python311\Include\Python.h:87: C:\Users\myusername\AppData\Local\Programs\Python\Python311\Include\cpython/pytime.h:184:12: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility] 184 | struct timeval *tv, | ^ C:\Users\myusername\AppData\Local\Programs\Python\Python311\Include\cpython/pytime.h:190:12: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility] 190 | struct timeval *tv, | ^ 2 warnings generated. Using HIP SDK Clang. In file included from D:\idm-temp\temp\tmpjul7ui0z\main.c:4: In file included from C:\Users\myusername\AppData\Local\Programs\Python\Python311\Include\Python.h:87: C:\Users\myusername\AppData\Local\Programs\Python\Python311\Include\cpython/pytime.h:184:12: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility] 184 | struct timeval *tv, | ^ C:\Users\myusername\AppData\Local\Programs\Python\Python311\Include\cpython/pytime.h:190:12: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility] 190 | struct timeval *tv, | ^ 2 warnings generated. Compilation is in progress. Please wait... Compilation is in progress. Please wait... Compilation is in progress. Please wait... Compilation is in progress. Please wait... Compilation is in progress. Please wait... Compilation is in progress. Please wait... Compilation is in progress. Please wait... :: Triton kernel test passed successfully :: Triton initialized successfully :: Patching ONNX Runtime for ZLUDA — disabling CUDA EP. :: Using ZLUDA with device: AMD Radeon RX 6800 [ZLUDA] :: Applying core ZLUDA patches... :: Initializing Triton optimizations :: Configuring Triton device properties... :: Triton device properties configured :: Flash attention components found :: AMD flash attention enabled successfully :: Configuring PyTorch backends... :: Disabled CUDA flash attention :: Enabled math attention fallback :: ZLUDA initialization complete :: ------------------------ ZLUDA ----------------------- ::
> 
> Total VRAM 16368 MB, total RAM 32690 MB pytorch version: 2.7.0+cu118 Set vram state to: NORMAL_VRAM Device: cuda:0 AMD Radeon RX 6800 [ZLUDA] : native Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr 2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] ComfyUI version: 0.3.48 ComfyUI frontend version: 1.23.4 [Prompt Server] web root: D:\sd\ComfyUI-Zluda\venv\Lib\site-packages\comfyui_frontend_package\static
> 
> ### Loading: ComfyUI-Manager (V3.35)
> [ComfyUI-Manager] network_mode: public
> 
> ### ComfyUI Revision: 4695 [[9a7b512](https://github.com/patientx/ComfyUI-Zluda/commit/9a7b512852811be1a72e1fc6d11d3e506c9f90ae)] | Released on '2025-08-02'
> Import times for custom nodes: 0.0 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\cfz_cudnn.toggle.py 0.0 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\cfz_vae_loader.py 0.0 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\websocket_image_save.py 0.0 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\cfz_patcher.py 0.0 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\ComfyUI-deepcache 0.5 seconds: D:\sd\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
> 
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json Context impl SQLiteImpl. Will assume non-transactional DDL. No target revision found. Starting server
> 
> ## To see the GUI go to: http://127.0.0.1:8188
> as you can see it compiles a bit at triton test stage, and after it completes it is ready to run, I loaded the default workflow, put an sd 1.5 model and started generating. AGAIN it compiles a bit more - does it with each model type at least once-
> 
> My point is : if you follow every step , make sure that the path's are correctly set up, visual studio correctly set up, the libraries for your gpu correctly copied -if necessary- , the "libs" folder correctly copied from the python directory into venv of comfyui-zluda, EVERYTHING SHOULD WORK.

well made it to run with new install method  (very difficult) . last error i had was a GET engine execution failed . and some deepseeking told me it was releated to fp16 and fp32 precision . set to fp32 (rx6600 this is too much) it ran but 70% slower then old install method idk why... so removed venv and ran with simple install which is much stable around 7 sec for 512x512 img on eular+ kerras .... hey patientx can you further guide me with new install method .  why it is so slow ?

**Comment by Geekyboi6117** [comment]
> Thanks to both, sadly i tried both things and still have the same problem, i dont have an integrated gpu, only the rx6650xt

del venv , clear zluda.db cache . IMPORTANT 

1. run patchzluda2 with latest stable build. that doesnt work try nightly

which install method are you using btw?

**Comment by patientx** [comment]
> well made it to run with new install method (very difficult) . last error i had was a GET engine execution failed . and some deepseeking told me it was releated to fp16 and fp32 precision . set to fp32 (rx6600 this is too much) it ran but 70% slower then old install method idk why... so removed venv and ran with simple install which is much stable around 7 sec for 512x512 img on eular+ kerras .... hey patientx can you further guide me with new install method . why it is so slow ?

I started this fork with rx 6600, everything including wan -albeit very low resolutions with small framecount- works with the new setup, I started using it while I had an 6600, I acquired an rx 6800 recently. Look at old issues etc. Can't remember every solution to a problem out of my head , sorry.  disabling cudnn might solve vae issues, check the cfz cudnn toggle node which gets installed when you install comfy.

**Comment by Geekyboi6117** [comment]
> > well made it to run with new install method (very difficult) . last error i had was a GET engine execution failed . and some deepseeking told me it was releated to fp16 and fp32 precision . set to fp32 (rx6600 this is too much) it ran but 70% slower then old install method idk why... so removed venv and ran with simple install which is much stable around 7 sec for 512x512 img on eular+ kerras .... hey patientx can you further guide me with new install method . why it is so slow ?
> 
> I started this fork with rx 6600, everything including wan -albeit very low resolutions with small framecount- works with the new setup, I started using it while I had an 6600, I acquired an rx 6800 recently. Look at old issues etc. Can't remember every solution to a problem out of my head , sorry. disabling cudnn might solve vae issues, check the cfz cudnn toggle node which gets installed when you install comfy.

new install method works . but even at ksampler stage before vae decode. speed is very slow compared to old install method . what could be the issue? should i del triton and zluda  cache and reinstall ?

**Comment by patientx** [comment]
again disable cudnn via the toggle node , sometimes before the vae or even before the model loading, and once you do that in a session, until you restart comfy it persists.

**Comment by TheActualJeff** [comment]
> again disable cudnn via the toggle node , sometimes before the vae or even before the model loading, and once you do that in a session, until you restart comfy it persists.

I discovered this purely by accident. HiresFix / Upscale nodes were painfully slow in the new install method, then I put a "CFZ CUDNN Toggle" node before the Hiresfix / Upscale node and set it to false. Now it takes about 10 seconds for a Hiresfix / Upscale node to finish on my 6900XT.

**Comment by Doranos** [comment]
I have a 6800 XT, with no integrated graphics, and spent the last 5 days trying to get ComfyUI working while getting a mix of "RuntimeError: CUDA unknown error" and "RuntimeError: No CUDA GPUs are available" errors. I tested everything written here, #188
 and another similar issue. I tried with a full reinstall, including my OS, which also would not work, and then moved on to sd.next-zluda, which worked immediately. Now sure that my system is doing something very stupid, i tried stupid solutions. Long story short ComfyUI does not like my card and i have to use "set HIP_VISIBLE_DEVICES=0" in order for ComfyUI to acknowledge the existence of my 6800xt.

**Comment by matjav1234** [comment]
I just installed and this is the log I got, can you help me?

---------------------------------------------------------------
* COMFYUI-ZLUDA INSTALL (for HIP 6.2.4 with MIOPEN and Triton)*
---------------------------------------------------------------

 ::  20:41:10  ::  - Setting up the virtual enviroment
 ::  20:41:15  ::  - Virtual enviroment activation
 ::  20:41:15  ::  - Updating the pip package

 ::  20:41:18  ::  Beginning installation ...

 ::  20:41:18  ::  - Installing required packages
 ::  20:42:32  ::  - Installing torch for AMD GPUs (First file is 2.7 GB, please be patient)
 ::  20:43:51  ::  - Installing onnxruntime (required by some nodes)
 ::  20:43:55  ::  - (temporary numpy fix)
 ::  20:44:02  ::  - Detecting Python version and installing appropriate triton package
 ::  20:44:02  ::  - Python 3.11 detected, installing triton for 3.11
Collecting triton==3.4.0+gita9c80202
  Downloading https://github.com/lshqqytiger/triton/releases/download/a9c80202/triton-3.4.0+gita9c80202-cp311-cp311-win_amd64.whl (25.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.7/25.7 MB 23.2 MB/s  0:00:01
Collecting setuptools>=40.8.0 (from triton==3.4.0+gita9c80202)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools, triton
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.5.0
    Uninstalling setuptools-65.5.0:
      Successfully uninstalled setuptools-65.5.0
Successfully installed setuptools-80.9.0 triton-3.4.0+gita9c80202
HTTP Error 429: Too Many Requests
Failed to download or parse patch from URL 'https://raw.githubusercontent.com/sfinktah/amd-torch/refs/heads/main/patches/triton-3.4.0+gita9c80202-cp311-cp311-win_amd64.patch'
HTTP Error 429: Too Many Requests
Failed to download or parse patch from URL 'https://raw.githubusercontent.com/sfinktah/amd-torch/refs/heads/main/patches/torch-2.7.0+cu118-cp311-cp311-win_amd64.patch'
 ::  20:44:17  ::  - Installing flash-attention
 ::  20:44:19  ::  - Installing and patching sage-attention

 ::  20:44:21  ::  Custom node(s) installation ...

:: 20:44:21  ::  - Installing CFZ Nodes (description in readme on github)
 ::  20:44:21  ::  - Installing Comfyui Manager
 ::  20:44:27  ::  - Installing ComfyUI-deepcache
 ::  20:44:28  ::  - Copying python libs
C:\Users\matja.DESKTOP-HNC68BI\AppData\Local\Programs\Python\Python311\libs\python3.lib
C:\Users\matja.DESKTOP-HNC68BI\AppData\Local\Programs\Python\Python311\libs\python311.lib
C:\Users\matja.DESKTOP-HNC68BI\AppData\Local\Programs\Python\Python311\libs\_tkinter.lib
3 archivo(s) copiado(s)

 ::  20:44:28  ::  - Patching ZLUDA
 ::  20:44:29  ::  - ZLUDA 3.9.5 nightly patched for HIP SDK 6.2.4 with miopen and triton-flash attention.

.....................................................
*** Installation is completed in 00:03:19,20 .
*** You can use "comfyui-n.bat" to start the app later.
*** It is advised to make a copy of "comfyui-n.bat" and modify it to your liking so when updating later it won't cause problems.
*** You can use -- "--use-pytorch-cross-attention" , "--use-quad-cross-attention" , "--use-flash-attention" or "--use-sage-attention"
.....................................................

*** Starting the Comfyui-ZLUDA for the first time, please be patient...

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies. (GitPython)
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-08-07 20:44:44.312
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: D:\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: D:\ComfyUI-Zluda
** ComfyUI Base Folder Path: D:\ComfyUI-Zluda
** User directory: D:\ComfyUI-Zluda\user
** ComfyUI-Manager config path: D:\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: D:\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
  15.6 seconds: D:\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "D:\ComfyUI-Zluda\main.py", line 145, in <module>
    import comfy.utils
  File "D:\ComfyUI-Zluda\comfy\utils.py", line 20, in <module>
    import torch
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\torch\__init__.py", line 270, in <module>
    _load_dll_libraries()
  File "D:\ComfyUI-Zluda\venv\Lib\site-packages\torch\__init__.py", line 266, in _load_dll_libraries
    raise err
OSError: [WinError 126] No se puede encontrar el módulo especificado. Error loading "D:\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\cudnn64_9.dll" or one of its dependencies.

**Comment by merewolf** [comment]
EDIT: Solved the issue. Turns out I followed the instruction to the letter except the part where it said to reboot the PC after adding path to PATH environmental variable 🤦‍♂️ [matjav1234](https://github.com/matjav1234) maybe you have the same issue?


Same issue as user above me. I have 7800xt. After running install.bat when I run comfyui.bat I get

Traceback (most recent call last):
  File "C:\Users\Roman\Projects\ComfyUI-Zluda\main.py", line 145, in <module>
    import comfy.utils
  File "C:\Users\Roman\Projects\ComfyUI-Zluda\comfy\utils.py", line 20, in <module>
    import torch
  File "C:\Users\Roman\Projects\ComfyUI-Zluda\venv\Lib\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Roman\Projects\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.

**Comment by matjav1234** [comment]
thanks for the answers! I could solve the proble, but what I had to do is install an older graphics card driver (I have Radeon 6700XT), I downgraded the driver to 25.2.1 and it worked.

**Comment by hpx380x** [comment]
i have this error "amd its brain pain"   
-------------------------------------------

File "G:\Data\Packages\ComfyUI-Zluda\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 59, in forward_timestep_embed
    x = layer(x)
        ^^^^^^^^
  File "G:\Data\Packages\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Data\Packages\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Data\Packages\ComfyUI-Zluda\comfy\ops.py", line 143, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Data\Packages\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Data\Packages\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: CUDNN_BACKEND_OPERATIONGRAPH_DESCRIPTOR: cudnnFinalize FailedmiopenStatusInternalError cudnn_status: miopenStatusUnknownError
