### ISSUE TITLE
Upscale Latent to VAE Decode error

### ISSUE THREAD

**Issue by snake-dude** [patientx/ComfyUI-Zluda#239]
I am trying to use Upscale Latent By node in between two KSamplers

Upscale Latent By node upscale_method set to bislerp and scale_by set to default of 1.50

Failing on VAE Decode after second KSampler

Error Message:
CUDNN_BACKEND_OPERATIONGRAPH_DESCRIPTOR: cudnnFinalize FailedmiopenStatusInternalError cudnn_status: miopenStatusUnknownError

2025-08-03T02:38:57.285006 - got prompt
2025-08-03T02:38:57.296022 - Requested to load SDXL
2025-08-03T02:38:58.982173 - loaded completely 12808.4240725708 4897.0483474731445 True
2025-08-03T02:39:03.395226 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:04<00:00,  1.47s/it]2025-08-03T02:39:03.395726 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:04<00:00,  1.47s/it]2025-08-03T02:39:03.395726 - 
2025-08-03T02:39:03.419740 - Requested to load SDXL
2025-08-03T02:39:03.986281 - loaded completely 10343.066260070802 4897.0483474731445 True
2025-08-03T02:39:16.443845 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:12<00:00,  4.15s/it]2025-08-03T02:39:16.443845 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:12<00:00,  4.15s/it]2025-08-03T02:39:16.443845 - 
2025-08-03T02:39:22.871566 - !!! Exception during processing !!! CUDNN_BACKEND_OPERATIONGRAPH_DESCRIPTOR: cudnnFinalize FailedmiopenStatusInternalError cudnn_status: miopenStatusUnknownError
2025-08-03T02:39:22.872569 - Traceback (most recent call last):
  File "G:\ComfyUI\ComfyUI-Zluda\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "G:\ComfyUI\ComfyUI-Zluda\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\nodes.py", line 295, in decode
    images = vae.decode(samples["samples"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\comfy\sd.py", line 592, in decode
    out = self.process_output(self.first_stage_model.decode(samples, **vae_options).to(self.output_device).float())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\comfy\ldm\models\autoencoder.py", line 205, in decode
    dec = self.decoder(dec, **decoder_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\comfy\ldm\modules\diffusionmodules\model.py", line 723, in forward
    h = self.up[i_level].upsample(h)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\comfy\ldm\modules\diffusionmodules\model.py", line 114, in forward
    x = self.conv(x)
        ^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\comfy\ops.py", line 114, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: CUDNN_BACKEND_OPERATIONGRAPH_DESCRIPTOR: cudnnFinalize FailedmiopenStatusInternalError cudnn_status: miopenStatusUnknownError

**Comment by patientx** [comment]
disable cudnn with cfz cudnn toggle node (it should be false) in somewhere before the vae decode -for example put it between latent and vae decode on the last vae- or you can actually set the value on any other workflow etc, it would stay that way at that comfy run. Also make sure you are using tiled vae decoding AND encoding if acceptable.

**Comment by snake-dude** [comment]
I am very new to image generation
Not sure exactly what the difference between tiled and non tiled decode and encode is

I tried using the vae encoding
Not sure if I piped incorrectly but I got this error

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:08<00:00,  4.29s/it]
[CUDNN_TOGGLE] torch.backends.cudnn.enabled set to False
Requested to load AutoencoderKL
loaded completely 242.30722656249964 159.55708122253418 True
Compilation is in progress. Please wait...
Prompt executed in 24.71 seconds
got prompt
Requested to load SDXL
loaded completely 12691.823760070802 4897.0483474731445 True
  9%|███████▌                                                                           | 2/22 [00:04<00:44,  2.21s/it]
Processing interrupted
Prompt executed in 6.25 seconds
got prompt
100%|██████████████████████████████████████████████████████████████████████████████████| 22/22 [00:32<00:00,  1.47s/it]
Requested to load SDXL
loaded completely 10276.358135070801 4897.0483474731445 True
100%|██████████████████████████████████████████████████████████████████████████████████| 11/11 [00:54<00:00,  4.98s/it]
[CUDNN_TOGGLE] torch.backends.cudnn.enabled set to False
!!! Exception during processing !!! 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "G:\ComfyUI\ComfyUI-Zluda\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "G:\ComfyUI\ComfyUI-Zluda\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI-Zluda\nodes.py", line 343, in encode
    t = vae.encode(pixels[:,:,:,:3])
                   ~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

The important part to me is that I can now use the Upscale Latent By

I added the cfz cudnn toggle node between my second sampler and the vae decode by attaching the latent pipe from the samper to the cfz cudnn toggle node and the pipe from the toggle to the vae decode

**Comment by patientx** [comment]
only one toggle is enough and it seems to be working , can you share your workflow so I can try ? 
If I try with sdxl and comfy's own upscale latent by node it works for me without errors. 

Meanwhile here is how it is done with the default workflow, I kept "vae decode" for you to see, instead of "vae decode" node, use "vae decode (tiled)" node as it is in the image. this reduces memory usage very much.

<img width="1547" height="774" alt="Image" src="https://github.com/user-attachments/assets/4ead88b5-1383-472b-8aa3-105110a4fad0" />

**Comment by snake-dude** [comment]
Placing the cfz cudnn toggle before the decode node has fixed my original issue.
This was my workflow when attempting to use the vae encode node.
Removing the encode and running it seemed to have no negative effects.

<img width="2252" height="1063" alt="Image" src="https://github.com/user-attachments/assets/c77775b2-4870-424f-bf6b-7ddfc3476f31" />

**Comment by YAY-3M-TA3** [comment]
Well, I guess other than making the final image look worse... Final Detail is blurry

**Comment by NaviVoid** [comment]
> disable cudnn with cfz cudnn toggle node (it should be false) in somewhere before the vae decode -for example put it between latent and vae decode on the last vae- or you can actually set the value on any other workflow etc, it would stay that way at that comfy run. Also make sure you are using tiled vae decoding AND encoding if acceptable.

I have updated driver to 25.8.1 and cleaned compilation cache, then set TRITON_OVERRIDE_ARCH=gfx1100 cause the detection failed (I'm using 7900gre), and now somehow disabling cudnn is not required.
