### ISSUE TITLE
I've tried nearly everything, help please?

### ISSUE THREAD

**Issue by tedarulefi** [patientx/ComfyUI-Zluda#246]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

Hey! Basically, I've been trying to make this work for about 5 or 6 hours now (18:00 to 23:30), and I finally decided to try and get help here, I didn't really want to make an account but I guess I have no choice.

I did try mostly everything I could with my RX 580, except fresh reinstalling windows (which, I will admit, I did give a thought just for the sake of having this work, purely out of spite 😅).

Below are the logs of 3 different attempts (torch 2.3, no torch 2.3, and smallest model, no vram with torch 2.3 [the webui straight up doesn't launch if I don't have torch 2.3 installed instead of 2.2.1, I have tried fixes, but none really worked], if you need any info just ask me!)

Btw, these are the things I have tried (can try again if necessary):
- Reinstalling everything (ComfyUI ZLUDA, ROCm Libs & DLLs, AMD Software and Drivers) (some I have tried multiple times)
- Searching this github and others for users with similar issues
- Following the tutorial (multiple times)
- Extensively google searching about issues (dozens of times)
- Changing checkpoints 
- Disabling LORAs
- Swapping from torch 2.2.1 to 2.3 to 2.4.1
- Disabling custom nodes
- Clearing cache (multiple times)
- Changing arguments and 
- Googling & reading the logs and errors
- Other stuff I don't remember right now

### Logs

```powershell
## ComfyUI-Manager: installing dependencies done.
[2025-08-06 22:56:22.015] ** ComfyUI startup time: 2025-08-06 22:56:22.015
[2025-08-06 22:56:22.016] ** Platform: Windows
[2025-08-06 22:56:22.016] ** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
[2025-08-06 22:56:22.017] ** Python executable: C:\Users\thefi\AI\ComfyUI-Zluda\venv\Scripts\python.exe
[2025-08-06 22:56:22.017] ** ComfyUI Path: C:\Users\thefi\AI\ComfyUI-Zluda
[2025-08-06 22:56:22.017] ** ComfyUI Base Folder Path: C:\Users\thefi\AI\ComfyUI-Zluda
[2025-08-06 22:56:22.018] ** User directory: C:\Users\thefi\AI\ComfyUI-Zluda\user
[2025-08-06 22:56:22.018] ** ComfyUI-Manager config path: C:\Users\thefi\AI\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
[2025-08-06 22:56:22.020] ** Log path: C:\Users\thefi\AI\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
[2025-08-06 22:56:23.363]    3.8 seconds: C:\Users\thefi\AI\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2025-08-06 22:56:23.363] 
[2025-08-06 22:56:29.578] Warning, you are using an old pytorch version and some ckpt/pt files might be loaded unsafely. Upgrading to 2.4 or above is recommended.
[2025-08-06 22:56:29.682] 
  ::  Checking package versions...
[2025-08-06 22:56:29.685] Found pydantic: 2.11.7, pydantic-settings: 2.10.1
[2025-08-06 22:56:30.221]   ::  Pydantic packages are compatible, skipping reinstall
[2025-08-06 22:56:30.222] Installed version of comfyui-frontend-package: 1.23.4
[2025-08-06 22:56:30.226] Installed version of comfyui-workflow-templates: 0.1.51
[2025-08-06 22:56:30.227] Installed version of av: 15.0.0
[2025-08-06 22:56:30.229] Installed version of comfyui-embedded-docs: 0.2.4
[2025-08-06 22:56:30.229]   ::  Package version check complete.
[2025-08-06 22:56:32.361] 
***----------------------ZLUDA-----------------------------***
[2025-08-06 22:56:32.361]   ::  Patching ONNX Runtime for ZLUDA — disabling CUDA EP.
[2025-08-06 22:56:32.361]   ::  ZLUDA detected, disabling non-supported functions.      
[2025-08-06 22:56:32.361]   ::  CuDNN, flash_sdp, mem_efficient_sdp disabled.           
[2025-08-06 22:56:32.362]   ::  Using ZLUDA with device: AMD Radeon RX 580 2048SP [ZLUDA]
[2025-08-06 22:56:32.362] ***--------------------------------------------------------***
[2025-08-06 22:56:32.362] 
[2025-08-06 22:56:33.310] Total VRAM 8192 MB, total RAM 23953 MB
[2025-08-06 22:56:33.320] pytorch version: 2.3.1+cu118
[2025-08-06 22:56:33.335] Set vram state to: NORMAL_VRAM
[2025-08-06 22:56:33.336] Device: cuda:0 AMD Radeon RX 580 2048SP [ZLUDA] : native
[2025-08-06 22:56:36.292] Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
[2025-08-06 22:56:46.786] Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
[2025-08-06 22:56:46.786] ComfyUI version: 0.3.49
[2025-08-06 22:56:46.817] ComfyUI frontend version: 1.23.4
[2025-08-06 22:56:46.819] [Prompt Server] web root: C:\Users\thefi\AI\ComfyUI-Zluda\venv\Lib\site-packages\comfyui_frontend_package\static
[2025-08-06 22:56:50.001] ### Loading: ComfyUI-Manager (V3.35)
[2025-08-06 22:56:50.002] [ComfyUI-Manager] network_mode: public
[2025-08-06 22:56:50.676] ### ComfyUI Revision: 4738 [8795ae98] | Released on '2025-08-06'
[2025-08-06 22:56:50.985] 
Import times for custom nodes:
[2025-08-06 22:56:50.985]    0.0 seconds: C:\Users\thefi\AI\ComfyUI-Zluda\custom_nodes\websocket_image_save.py
[2025-08-06 22:56:50.986]    0.0 seconds: C:\Users\thefi\AI\ComfyUI-Zluda\custom_nodes\ComfyUI-deepcache
[2025-08-06 22:56:50.986]    1.1 seconds: C:\Users\thefi\AI\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2025-08-06 22:56:50.986] 
[2025-08-06 22:56:51.055] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2025-08-06 22:56:51.069] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2025-08-06 22:56:51.137] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2025-08-06 22:56:51.167] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2025-08-06 22:56:51.305] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2025-08-06 22:56:51.934] Context impl SQLiteImpl.
[2025-08-06 22:56:51.934] Will assume non-transactional DDL.
[2025-08-06 22:56:51.937] No target revision found.
[2025-08-06 22:56:51.953] Starting server

[2025-08-06 22:56:51.954] To see the GUI go to: http://127.0.0.1:8188
[2025-08-06 22:56:56.606] FETCH ComfyRegistry Data: 5/93
[2025-08-06 22:57:00.783] FETCH ComfyRegistry Data: 10/93
[2025-08-06 22:57:04.629] FETCH ComfyRegistry Data: 15/93
[2025-08-06 22:57:08.822] FETCH ComfyRegistry Data: 20/93
[2025-08-06 22:57:13.004] FETCH ComfyRegistry Data: 25/93
[2025-08-06 22:57:17.033] FETCH ComfyRegistry Data: 30/93
[2025-08-06 22:57:17.312] got prompt
[2025-08-06 22:57:17.313] Failed to validate prompt for output 10:
[2025-08-06 22:57:17.313] * CheckpointLoaderSimple 4:
[2025-08-06 22:57:17.314]   - Value not in list: ckpt_name: 'indigoComic_v10withvae.safetensors' not in []
[2025-08-06 22:57:17.314] Output will be ignored
[2025-08-06 22:57:17.314] invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
[2025-08-06 22:57:21.251] FETCH ComfyRegistry Data: 35/93
[2025-08-06 22:57:25.210] FETCH ComfyRegistry Data: 40/93
[2025-08-06 22:57:29.214] FETCH ComfyRegistry Data: 45/93
[2025-08-06 22:57:33.371] FETCH ComfyRegistry Data: 50/93
[2025-08-06 22:57:37.488] FETCH ComfyRegistry Data: 55/93
[2025-08-06 22:57:43.224] FETCH ComfyRegistry Data: 60/93
[2025-08-06 22:57:47.159] FETCH ComfyRegistry Data: 65/93
[2025-08-06 22:57:52.359] FETCH ComfyRegistry Data: 70/93
[2025-08-06 22:57:56.688] FETCH ComfyRegistry Data: 75/93
[2025-08-06 22:58:00.091] got prompt
[2025-08-06 22:58:00.544] model weight dtype torch.float16, manual cast: None
[2025-08-06 22:58:00.639] model_type EPS
[2025-08-06 22:58:01.022] FETCH ComfyRegistry Data: 80/93
[2025-08-06 22:58:06.436] FETCH ComfyRegistry Data: 85/93
[2025-08-06 22:58:10.992] Using split attention in VAE
[2025-08-06 22:58:10.993] Using split attention in VAE
[2025-08-06 22:58:11.833] FETCH ComfyRegistry Data: 90/93
[2025-08-06 22:58:12.185] VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
[2025-08-06 22:58:12.302] CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
[2025-08-06 22:58:15.308] FETCH ComfyRegistry Data [DONE]
[2025-08-06 22:58:15.479] [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
[2025-08-06 22:58:15.505] FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[2025-08-06 22:58:15.711] [ComfyUI-Manager] All startup tasks have been completed.
[2025-08-06 22:58:16.074] Requested to load SD1ClipModel
[2025-08-06 22:58:16.211] loaded completely 6323.2 235.84423828125 True
[2025-08-06 23:06:28.776] Requested to load BaseModel
[2025-08-06 23:06:29.261] loaded completely 5529.44072265625 1639.406135559082 True
[2025-08-06 23:11:57.187] !!! Exception during processing !!! CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2025-08-06 23:11:57.190] Traceback (most recent call last):
  File "C:\Users\thefi\AI\ComfyUI-Zluda\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Users\thefi\AI\ComfyUI-Zluda\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\nodes.py", line 1521, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\nodes.py", line 1488, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\sample.py", line 45, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\samplers.py", line 1143, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\samplers.py", line 1033, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\samplers.py", line 1018, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\samplers.py", line 986, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\samplers.py", line 955, in inner_sample
    if latent_image is not None and torch.count_nonzero(latent_image) > 0: #Don't shift the empty latent image.
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


[2025-08-06 23:11:57.193] Prompt executed in 00:13:57
^^^^^^^^^^^^^^^^^
With PyTorch 2.3.0
Without PyTorch 2.3.0 (2.2.1)
vvvvvvvvvvvvvvvvv
## ComfyUI-Manager: installing dependencies done.
[2025-08-06 22:26:59.313] ** ComfyUI startup time: 2025-08-06 22:26:59.313
[2025-08-06 22:26:59.313] ** Platform: Windows
[2025-08-06 22:26:59.314] ** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
[2025-08-06 22:26:59.314] ** Python executable: C:\Users\thefi\AI\ComfyUI-Zluda\venv\Scripts\python.exe
[2025-08-06 22:26:59.315] ** ComfyUI Path: C:\Users\thefi\AI\ComfyUI-Zluda
[2025-08-06 22:26:59.315] ** ComfyUI Base Folder Path: C:\Users\thefi\AI\ComfyUI-Zluda
[2025-08-06 22:26:59.315] ** User directory: C:\Users\thefi\AI\ComfyUI-Zluda\user
[2025-08-06 22:26:59.316] ** ComfyUI-Manager config path: C:\Users\thefi\AI\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
[2025-08-06 22:26:59.316] ** Log path: C:\Users\thefi\AI\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
[2025-08-06 22:27:00.651]    3.8 seconds: C:\Users\thefi\AI\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2025-08-06 22:27:00.651] 
[2025-08-06 22:27:04.885] Traceback (most recent call last):
[2025-08-06 22:27:04.885]   File "C:\Users\thefi\AI\ComfyUI-Zluda\main.py", line 145, in <module>
[2025-08-06 22:27:04.886]     import comfy.utils
[2025-08-06 22:27:04.886]   File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\utils.py", line 24, in <module>
[2025-08-06 22:27:04.887]     import safetensors.torch
[2025-08-06 22:27:04.887]   File "C:\Users\thefi\AI\ComfyUI-Zluda\venv\Lib\site-packages\safetensors\torch.py", line 439, in <module>
[2025-08-06 22:27:04.888]     torch.uint64: 8,
[2025-08-06 22:27:04.888]     ^^^^^^^^^^^^
[2025-08-06 22:27:04.890]   File "C:\Users\thefi\AI\ComfyUI-Zluda\venv\Lib\site-packages\torch\__init__.py", line 1938, in __getattr__
[2025-08-06 22:27:04.890]     raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
[2025-08-06 22:27:04.891] AttributeError: module 'torch' has no attribute 'uint64'



-----
Using args --disable-cuda-malloc, clearing cache and using start-tunableop-novram.bat (smallest model I had) (torch 2.3): 
vvvvvv
## ComfyUI-Manager: installing dependencies done.
[2025-08-06 23:30:25.988] ** ComfyUI startup time: 2025-08-06 23:30:25.988
[2025-08-06 23:30:25.989] ** Platform: Windows
[2025-08-06 23:30:25.990] ** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
[2025-08-06 23:30:25.991] ** Python executable: C:\Users\thefi\AI\ComfyUI-Zluda\venv\Scripts\python.exe
[2025-08-06 23:30:25.991] ** ComfyUI Path: C:\Users\thefi\AI\ComfyUI-Zluda
[2025-08-06 23:30:25.991] ** ComfyUI Base Folder Path: C:\Users\thefi\AI\ComfyUI-Zluda
[2025-08-06 23:30:25.991] ** User directory: C:\Users\thefi\AI\ComfyUI-Zluda\user
[2025-08-06 23:30:25.992] ** ComfyUI-Manager config path: C:\Users\thefi\AI\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
[2025-08-06 23:30:25.992] ** Log path: C:\Users\thefi\AI\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
[2025-08-06 23:30:27.239]    3.6 seconds: C:\Users\thefi\AI\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2025-08-06 23:30:27.239] 
[2025-08-06 23:30:28.714] Warning, you are using an old pytorch version and some ckpt/pt files might be loaded unsafely. Upgrading to 2.4 or above is recommended.
[2025-08-06 23:30:28.726] 
  ::  Checking package versions...
[2025-08-06 23:30:28.728] Found pydantic: 2.11.7, pydantic-settings: 2.10.1
[2025-08-06 23:30:28.817]   ::  Pydantic packages are compatible, skipping reinstall
[2025-08-06 23:30:28.818] Installed version of comfyui-frontend-package: 1.23.4
[2025-08-06 23:30:28.821] Installed version of comfyui-workflow-templates: 0.1.51
[2025-08-06 23:30:28.822] Installed version of av: 15.0.0
[2025-08-06 23:30:28.823] Installed version of comfyui-embedded-docs: 0.2.4
[2025-08-06 23:30:28.823]   ::  Package version check complete.
[2025-08-06 23:30:29.797] 
***----------------------ZLUDA-----------------------------***
[2025-08-06 23:30:29.797]   ::  Patching ONNX Runtime for ZLUDA — disabling CUDA EP.
[2025-08-06 23:30:29.797]   ::  ZLUDA detected, disabling non-supported functions.      
[2025-08-06 23:30:29.798]   ::  CuDNN, flash_sdp, mem_efficient_sdp disabled.           
[2025-08-06 23:30:29.798]   ::  Using ZLUDA with device: AMD Radeon RX 580 2048SP [ZLUDA]
[2025-08-06 23:30:29.798] ***--------------------------------------------------------***
[2025-08-06 23:30:29.798] 
[2025-08-06 23:30:30.138] Total VRAM 8192 MB, total RAM 23953 MB
[2025-08-06 23:30:30.138] pytorch version: 2.3.1+cu118
[2025-08-06 23:30:30.139] Set vram state to: NO_VRAM
[2025-08-06 23:30:30.139] Device: cuda:0 AMD Radeon RX 580 2048SP [ZLUDA] : native
[2025-08-06 23:30:30.483] Using pytorch attention
[2025-08-06 23:30:32.476] Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
[2025-08-06 23:30:32.476] ComfyUI version: 0.3.49
[2025-08-06 23:30:32.503] ComfyUI frontend version: 1.23.4
[2025-08-06 23:30:32.505] [Prompt Server] web root: C:\Users\thefi\AI\ComfyUI-Zluda\venv\Lib\site-packages\comfyui_frontend_package\static
[2025-08-06 23:30:33.394] ### Loading: ComfyUI-Manager (V3.35)
[2025-08-06 23:30:33.395] [ComfyUI-Manager] network_mode: public
[2025-08-06 23:30:34.011] ### ComfyUI Revision: 4738 [8795ae98] | Released on '2025-08-06'
[2025-08-06 23:30:34.237] 
Import times for custom nodes:
[2025-08-06 23:30:34.237]    0.0 seconds: C:\Users\thefi\AI\ComfyUI-Zluda\custom_nodes\websocket_image_save.py
[2025-08-06 23:30:34.237]    0.0 seconds: C:\Users\thefi\AI\ComfyUI-Zluda\custom_nodes\ComfyUI-deepcache
[2025-08-06 23:30:34.237]    0.8 seconds: C:\Users\thefi\AI\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2025-08-06 23:30:34.238] 
[2025-08-06 23:30:34.343] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2025-08-06 23:30:34.365] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2025-08-06 23:30:34.398] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2025-08-06 23:30:34.449] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2025-08-06 23:30:34.519] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2025-08-06 23:30:34.682] Context impl SQLiteImpl.
[2025-08-06 23:30:34.682] Will assume non-transactional DDL.
[2025-08-06 23:30:34.683] No target revision found.
[2025-08-06 23:30:34.697] Starting server

[2025-08-06 23:30:34.697] To see the GUI go to: http://127.0.0.1:8188
[2025-08-06 23:30:37.545] got prompt
[2025-08-06 23:30:37.619] model weight dtype torch.float16, manual cast: None
[2025-08-06 23:30:37.621] model_type EPS
[2025-08-06 23:30:37.995] Using pytorch attention in VAE
[2025-08-06 23:30:37.997] Using pytorch attention in VAE
[2025-08-06 23:30:38.119] VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
[2025-08-06 23:30:38.187] Requested to load SD1ClipModel
[2025-08-06 23:30:38.192] loaded completely 9.5367431640625e+25 235.84423828125 True
[2025-08-06 23:30:38.193] CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float16
[2025-08-06 23:30:38.913] Requested to load BaseModel
[2025-08-06 23:30:38.928] loaded partially 9.5367431640625e-08 0.0 0
[2025-08-06 23:30:39.725] FETCH ComfyRegistry Data: 5/93
[2025-08-06 23:30:43.743] FETCH ComfyRegistry Data: 10/93
[2025-08-06 23:30:47.917] FETCH ComfyRegistry Data: 15/93
[2025-08-06 23:30:52.107] FETCH ComfyRegistry Data: 20/93
[2025-08-06 23:30:56.315] FETCH ComfyRegistry Data: 25/93
[2025-08-06 23:31:00.283] FETCH ComfyRegistry Data: 30/93
[2025-08-06 23:31:04.156] FETCH ComfyRegistry Data: 35/93
[2025-08-06 23:31:08.161] FETCH ComfyRegistry Data: 40/93
[2025-08-06 23:31:12.342] FETCH ComfyRegistry Data: 45/93
[2025-08-06 23:31:17.125] FETCH ComfyRegistry Data: 50/93
[2025-08-06 23:31:21.196] FETCH ComfyRegistry Data: 55/93
[2025-08-06 23:31:25.422] FETCH ComfyRegistry Data: 60/93
[2025-08-06 23:31:29.335] FETCH ComfyRegistry Data: 65/93
[2025-08-06 23:31:34.271] FETCH ComfyRegistry Data: 70/93
[2025-08-06 23:31:38.837] FETCH ComfyRegistry Data: 75/93
[2025-08-06 23:31:43.112] FETCH ComfyRegistry Data: 80/93
[2025-08-06 23:31:47.438] FETCH ComfyRegistry Data: 85/93
[2025-08-06 23:31:51.836] FETCH ComfyRegistry Data: 90/93
[2025-08-06 23:31:54.822] FETCH ComfyRegistry Data [DONE]
[2025-08-06 23:31:54.997] [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
[2025-08-06 23:31:55.018] FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[2025-08-06 23:31:55.224] [ComfyUI-Manager] All startup tasks have been completed.
[2025-08-06 23:36:33.684] !!! Exception during processing !!! CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2025-08-06 23:36:33.686] Traceback (most recent call last):
  File "C:\Users\thefi\AI\ComfyUI-Zluda\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Users\thefi\AI\ComfyUI-Zluda\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\nodes.py", line 1521, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\nodes.py", line 1488, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\sample.py", line 45, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\samplers.py", line 1143, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\samplers.py", line 1033, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\samplers.py", line 1018, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\samplers.py", line 986, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\samplers.py", line 955, in inner_sample
    if latent_image is not None and torch.count_nonzero(latent_image) > 0: #Don't shift the empty latent image.
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


[2025-08-06 23:36:33.689] Prompt executed in 356.14 seconds
---
torch 2.4.1 
vvvv

---
I can provide more logs if necessary (such as if I use cuda launch blocking=1)
```

### Other

System Info:
- I use a RX 580 8GB 2048SP
- I have a Ryzen 5 4600g processor
- 24GB ram
- Using Windows 11

--

General Info: 
- I have tried to install ZLUDA before with these tutorials: [this](https://www.youtube.com/watch?v=X4V3ppyb3zs&pp=0gcJCfwAo7VqN5tD) & [this too](https://www.youtube.com/watch?v=8POW3G6itcE) and a few others I couldn't find, which means **there might be other files doing this.** I can look up any files you ask w/ everything (that app that lets you search your entire disk drive)

- By changing pytorch versions (2.2.1 > 2.3), the WebUI could be opened, but would give errors upon trying to generate anything. Without this, I would get "[2025-08-06 22:27:04.891] AttributeError: module 'torch' has no attribute 'uint64'" (it's in logs) 

Sorry for the amount of info, I wanted to be as detailed as possible!

**Comment by patientx** [comment]
For older amd gpu's you would need to use torch 2.2.1 which is installed via "install-for-older-amd.bat" older torches won't work / keep causing problems. 

So forget about using latest stuff, clean everything and install via that one.

For the libraries this could work better than the alternatives :
 `https://www.mediafire.com/file/boobrm5vjg7ev50/rocBLAS-HIP5.7.1-win%2528old_gpu%2529.rar/file`

Install hip 5.7.1 , use those libraries to copy over as instructed in readme.

```
Go to folder "C:\Program Files\AMD\ROCm\5.7\bin\rocblas", there would be a "library" folder, backup the files inside to somewhere else.
Open your downloaded optimized library archive and put them inside the library folder (overwriting if necessary): "C:\Program Files\AMD\ROCm\5.7\bin\rocblas\library"
There could be a rocblas.dll file in the archive as well, if it is present then copy it inside "C:\Program Files\AMD\ROCm\5.7\bin\rocblas"
```

Besides that the errors you are seeing are all "out of memory" errors, see this part at the end "RuntimeError: CUDA error: out of memory" 

This is optional : 

Also there could be another problem for you, you have an apu 4600g, which also has a gpu on its own, you would have to make sure only 580 is used, make a copy of "comfyui.bat" , and go into your copy and add these lines (actually only the first should be enough but we are using every alternative) after `set VENV_DIR=./venv` line. The "1" could also be "0" , try with 1 , check the device identified when comfy is starting up , if no mention of 580, change it 0 then.

```
set HIP_VISIBLE_DEVICES=1
set ROCR_VISIBLE_DEVICES=1 
set HCC_AMDGPU_TARGET=1 
```

After that save the file and use it to run comfy.

**Comment by tedarulefi** [comment]
Okay, I'll be doing this and get back to you soon! (if I don't respond after that,  it's because it's currently 4:15am)

**Comment by tedarulefi** [comment]
Okay so, still getting those errors from before (the ones I mentioned that are why I switched to 2.3.1):

## ComfyUI-Manager: installing dependencies done.
[2025-08-07 04:38:14.754] ** ComfyUI startup time: 2025-08-07 04:38:14.754
[2025-08-07 04:38:14.755] ** Platform: Windows
[2025-08-07 04:38:14.756] ** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
[2025-08-07 04:38:14.756] ** Python executable: C:\Users\thefi\AI\ComfyUI-Zluda\venv\Scripts\python.exe
[2025-08-07 04:38:14.757] ** ComfyUI Path: C:\Users\thefi\AI\ComfyUI-Zluda
[2025-08-07 04:38:14.757] ** ComfyUI Base Folder Path: C:\Users\thefi\AI\ComfyUI-Zluda
[2025-08-07 04:38:14.758] ** User directory: C:\Users\thefi\AI\ComfyUI-Zluda\user
[2025-08-07 04:38:14.758] ** ComfyUI-Manager config path: C:\Users\thefi\AI\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
[2025-08-07 04:38:14.760] ** Log path: C:\Users\thefi\AI\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
[2025-08-07 04:38:15.988]    3.6 seconds: C:\Users\thefi\AI\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2025-08-07 04:38:15.988] 
[2025-08-07 04:38:17.430] Traceback (most recent call last):
[2025-08-07 04:38:17.430]   File "C:\Users\thefi\AI\ComfyUI-Zluda\main.py", line 145, in <module>
[2025-08-07 04:38:17.431]     import comfy.utils
[2025-08-07 04:38:17.431]   File "C:\Users\thefi\AI\ComfyUI-Zluda\comfy\utils.py", line 24, in <module>
[2025-08-07 04:38:17.432]     import safetensors.torch
[2025-08-07 04:38:17.432]   File "C:\Users\thefi\AI\ComfyUI-Zluda\venv\Lib\site-packages\safetensors\torch.py", line 439, in <module>
[2025-08-07 04:38:17.432]     torch.uint64: 8,
[2025-08-07 04:38:17.433]     ^^^^^^^^^^^^
[2025-08-07 04:38:17.435]   File "C:\Users\thefi\AI\ComfyUI-Zluda\venv\Lib\site-packages\torch\__init__.py", line 1938, in __getattr__
[2025-08-07 04:38:17.436]     raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
[2025-08-07 04:38:17.436] AttributeError: module 'torch' has no attribute 'uint64'

This error is why I had switched, by the way, to torch 2.3.1 if I forgot to explain it on the previous messages. These githubs are the only thing I could find online about this error.

https://github.com/EleutherAI/lm-evaluation-harness/issues/2199
https://github.com/pytorch/pytorch/issues/58734

Any idea of how to fix it? 

edit: I did everything you mentioned by the way (installed the libraries, added the things, etc.), the log error just stops there and sends me back to regular command prompt or 'press any key to continue...' when I try to run it. 

Copied the .bat file and made sure that one was =0 and the other was =1 to make sure one will detect the GPU.

<img width="1104" height="584" alt="Image" src="https://github.com/user-attachments/assets/6ef9f4a1-9d4f-4aa1-936a-d8d1b156c321" />

<img width="716" height="512" alt="Image" src="https://github.com/user-attachments/assets/8036bca0-a8b0-4086-8ae2-a6863ff475f3" />

<img width="787" height="407" alt="Image" src="https://github.com/user-attachments/assets/dabc0bd3-01aa-4ae7-a2c7-e567450142b6" />

**Comment by patientx** [comment]
try this, an older version of safetensors package which supposed to work with older torch's 
open commandline , go to the comfyui-zluda folder then run these one by one 

```
venv\scripts\activate
pip install safetensors==0.3.3
```

then try again.

**Comment by advanced-lvl-up** [comment]
Ok.  i got around to it, and installed the latest version of ComfyUI-Zluda fork (using the auto-installer). and this recreates your "uint64" problem for sure.  So i guess it's a newer issue .  If i have time, will try and compare a working version to the newer version, and hopefully help you solve it. We'll see.

**Comment by tedarulefi** [comment]
I went and did a few tests with this: 

> try this, an older version of safetensors package which supposed to work with older torch's open commandline , go to the comfyui-zluda folder then run these one by one
> 
> ```
> venv\scripts\activate
> pip install safetensors==0.3.3
> ```
> 
> then try again.

and it worked almost perfectly! More logs were printed, which is always welcome, but it didn't quite launch. It said something about an error with transformers incompatibility with safetensors, and I'm on my way to recreate the fix I did to get it working. I will basically reinstall, and will redo all the steps I did to report which one got me to the webui.

Back in a few minutes!

**Comment by advanced-lvl-up** [comment]
Yes, confirmed.   it is indeed transformers and safetensors:
`pip install --force-reinstall transformers==4.51.3 safetensors==0.5.3`

That command should solve it and give you a baseline sanity check.
And in your case, you may need this too, unless you already have 2.2.1 installed, of course.
`pip uninstall torch torchvision torchaudio`
`pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu118`

That should do it!  lets us know if you have further issues.

The final step after confirming it works, is to install a custom tensile / rocblas library.
Mind you, there are quite a few broken ones out there.  There's a much newer, open source fix for the rx580 library on my Github page.   And it's also a bit incomplete, but it generally works for all fp16, fp32, and bf16 + other common datatypes.  Common workflows (sdxl , Flux Schnell, Wan and other DiT based models)  will run at +50% to +200% speed in most tasks, without crashing and memory leaks.

For image to vid and advanced workflows you'll need to modify a few lines in the "/ComfyUI-Zluda/comfy/sd.py", to force tiled VAE encode.  Because it's bugged for older archs.  I'll write a post about this fix sometime, it's actually quite simple.

-------------------------------------------

A quick review of the exact steps i took from the beginning, in case anyone out there still has trouble.
so you need HIP SDK 5.7.1,  plus all the usual Windows base dependencies, like python and VisualC Runtimes, etc. (you already have them.)

ComfyUI-Zluda fork from this repo.

run "install-for-older-amd.bat" batch file from the ComfyUI-Zluda folder.
and then finally the "pip install --force-reinstall transformers==4.51.3 safetensors==0.5.3" i talked about before.

As of today those are the baseline steps for gfx803 (rx480 rx580), etc.
Will likely be changed, fixed, and broken again in the future. This sort of thing happens all the time no matter which GPU you use.

**Comment by tedarulefi** [comment]
That worked!! Thank you!! I think it might have been a version-specific transformers bug, considering I tried a few older versions (e.g. 0.3.3 safetensors with 4.37.1 transformers and it worked), but newer versions always are better.

I already have a rocblas librar,y but I probably will check out the rx580 library you made since the other ones are probably older. Once again, thank you! This saved me hours of headache.

I might take a bit to close because I want to see if there will be any problems on generating the images (maybe library errors, who knows?), will report back soon!

**Comment by patientx** [comment]
adding those to the installer for older gpus.

**Comment by tedarulefi** [comment]
It worked!! Thank you everyone! Sorry for the big delay, I had to fix some troubles with numpy.

Closing the thread now!
