### ISSUE TITLE
VAEDecode - miopenStatusUnknownError

### ISSUE THREAD

**Issue by ArtXGH** [patientx/ComfyUI-Zluda#253]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

Specification:
# 8060S
# install-n.bat (replaced suitable torch, torchaudio, torchvision for 8060S i.e. https://github.com/scottt/rocm-TheRock/releases/tag/v6.5.0rc-pytorch-gfx110x)
# comfyui-n.bat (add - set HIP_VISIBLE_DEVICES=0 + replace - --use-split-cross-attention)
# tried to patchzluda-n.bat again to ensure everything is smooth
# tried clean uninstall and re-install zluda
------------------------------------------------------------------------------------------------------------------------
1) comfyui-n.bat:
# Working great and fast for any t2i ;
# Error occurs for all video generation AI model ;
# sage attention error ;

2) comfyui.bat:
# Working great and fast for any t2i ;
# MiOpen Error occurs for all video generation AI model at final step ;
# sage attention error ;

Any idea? Pls help, thanks.

### Logs

```powershell
Requested to load LTXV
loaded completely 9.5367431640625e+25 3667.902587890625 True
Requested to load MochiTEModel_
loaded completely 9.5367431640625e+25 9083.38671875 True
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
FETCH ComfyRegistry Data: 50/93
FETCH ComfyRegistry Data: 55/93
FETCH ComfyRegistry Data: 60/93
  3%|██▊                                                                                | 1/30 [00:00<00:17,  1.67it/s]FETCH ComfyRegistry Data: 65/93
  7%|█████▌                                                                             | 2/30 [00:06<01:44,  3.73s/it]FETCH ComfyRegistry Data: 70/93
FETCH ComfyRegistry Data: 75/93
 10%|████████▎                                                                          | 3/30 [00:12<02:07,  4.70s/it]FETCH ComfyRegistry Data: 80/93
 13%|███████████                                                                        | 4/30 [00:18<02:14,  5.16s/it]FETCH ComfyRegistry Data: 85/93
 17%|█████████████▊                                                                     | 5/30 [00:24<02:15,  5.43s/it]FETCH ComfyRegistry Data: 90/93
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [02:52<00:00,  5.74s/it]
Requested to load VideoVAE
loaded completely 67079.32138671874 1599.096866607666 True
MIOpen Error: D:/jam/TheRock/ml-libs/MIOpen/src/ocl/convolutionocl.cpp:275: No suitable algorithm was found to execute the required convolution
!!! Exception during processing !!! miopenStatusUnknownError
Traceback (most recent call last):
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\nodes.py", line 295, in decode
    images = vae.decode(samples["samples"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\comfy\sd.py", line 593, in decode
    out = self.process_output(self.first_stage_model.decode(samples, **vae_options).to(self.output_device).float())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\comfy\ldm\lightricks\vae\causal_video_autoencoder.py", line 1091, in decode
    return self.decoder(self.per_channel_statistics.un_normalize(x), timestep=timestep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\comfy\ldm\lightricks\vae\causal_video_autoencoder.py", line 461, in forward
    sample = checkpoint_fn(up_block)(sample, causal=self.causal)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\comfy\ldm\lightricks\vae\causal_video_autoencoder.py", line 588, in forward
    hidden_states = resnet(hidden_states, causal=causal, timestep=timestep_embed)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\comfy\ldm\lightricks\vae\causal_video_autoencoder.py", line 854, in forward
    hidden_states = self.conv1(hidden_states, causal=causal)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\comfy\ldm\lightricks\vae\causal_conv3d.py", line 60, in forward
    x = self.conv(x)
        ^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\comfy\ops.py", line 128, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\conv.py", line 725, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\ComfyUIEVOX2\ComfyUI-Zluda\venv\Lib\site-packages\torch\nn\modules\conv.py", line 709, in _conv_forward
    return F.conv3d(
           ^^^^^^^^^
RuntimeError: miopenStatusUnknownError

Prompt executed in 213.48 seconds
```

**Comment by patientx** [comment]
try cfz cudnn toggle, maybe between ksampler and vae decode.

**Comment by ArtXGH** [comment]
> try cfz cudnn toggle, maybe between ksampler and vae decode.

U r great! Thanks!! This solved the MiOpen problem, tks. But I notice there is overheat problem ... just keep testing ...
