### ISSUE TITLE
Triton test failed: Triton Error [HIP]:  Code: 209

### ISSUE THREAD

**Issue by FredR000** [patientx/ComfyUI-Zluda#263]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

I followed the steps shown here: https://github.com/patientx/ComfyUI-Zluda/issues/188  
  
At first, I wasn't able to see things like Custom Nodes Manager, or Browse Templates. And of course a basic workflow wouldn't work either.  
  
I did, "Copy "libs" folder from python install directory..."  
I then ran, patchzluda-n.bat  
  
This made progress by giving me the Browse Templates and am able to see the Custom Nodes Manager.  
  
But still I get:  
  
Triton test failed: Triton Error [HIP]:  Code: 209  
And I can't run a basic workflow.  
  
I then tried "Remove visual studio 2022 and install "https://aka.ms/vs/17/release/vs_BuildTools.exe".  
  
Still same result.

### Logs

```powershell
---------------------------------------------------------------
* COMFYUI-ZLUDA INSTALL (for HIP 6.2.4 with MIOPEN and Triton)*
---------------------------------------------------------------

 ::  11:00:30  ::  - Setting up the virtual enviroment
 ::  11:00:30  ::  - Virtual enviroment activation
 ::  11:00:30  ::  - Updating the pip package

 ::  11:00:32  ::  Beginning installation ...

 ::  11:00:32  ::  - Installing required packages
 ::  11:00:33  ::  - Installing torch for AMD GPUs (First file is 2.7 GB, please be patient)
 ::  11:01:18  ::  - Installing onnxruntime (required by some nodes)
 ::  11:01:19  ::  - (temporary numpy fix)
 ::  11:01:25  ::  - Detecting Python version and installing appropriate triton package
 ::  11:01:25  ::  - Detected Python 3.12
 ::  11:01:25  ::  - Python 3.12 detected, installing triton for 3.12
Collecting triton==3.4.0+gita9c80202
  Downloading https://github.com/lshqqytiger/triton/releases/download/a9c80202/triton-3.4.0+gita9c80202-cp312-cp312-win_amd64.whl (25.7 MB)
     ---------------------------------------- 25.7/25.7 MB 11.5 MB/s  0:00:02
Collecting setuptools>=40.8.0 (from triton==3.4.0+gita9c80202)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools, triton
  Attempting uninstall: setuptools
    Found existing installation: setuptools 80.9.0
    Uninstalling setuptools-80.9.0:
      Successfully uninstalled setuptools-80.9.0
  Attempting uninstall: triton
    Found existing installation: triton 3.4.0+gita9c80202
    Uninstalling triton-3.4.0+gita9c80202:
      Successfully uninstalled triton-3.4.0+gita9c80202
Successfully installed setuptools-80.9.0 triton-3.4.0+gita9c80202
total files: 3  total hunks: 6
warning: absolute paths are not allowed (but who cares) - file no.1
stripping absolute path from source name '/tmp/tmp.ghCYbbdut4/unzipped/triton/backends/amd/compiler.py'
warning: absolute paths are not allowed (but who cares) - file no.2
stripping absolute path from source name '/tmp/tmp.ghCYbbdut4/unzipped/triton/compiler/compiler.py'
warning: absolute paths are not allowed (but who cares) - file no.3
stripping absolute path from source name '/tmp/tmp.ghCYbbdut4/unzipped/triton/runtime/build.py'
Loaded patch set: PatchSet(type=plain, items=[Patch(source='tmp/tmp.ghCYbbdut4/unzipped/triton/backends/amd/compiler.py', target='triton/backends/amd/compiler.py'), Patch(source='tmp/tmp.ghCYbbdut4/unzipped/triton/compiler/compiler.py', target='triton/compiler/compiler.py'), Patch(source='tmp/tmp.ghCYbbdut4/unzipped/triton/runtime/build.py', target='triton/runtime/build.py')])
applying patch to 'tmp/tmp.ghCYbbdut4/unzipped/triton/backends/amd/compiler.py'
stripping 4 leading component from 'tmp/tmp.ghCYbbdut4/unzipped/triton/backends/amd/compiler.py'
processing 1/3:  backends/amd/compiler.py
 hunk no.1 for file backends/amd/compiler.py  -- is ready to be patched
 hunk no.2 for file backends/amd/compiler.py  -- is ready to be patched
processing target file backends/amd/compiler.py
hunk 1
hunk 2
successfully patched 1/3:        backends/amd/compiler.py
applying patch to 'tmp/tmp.ghCYbbdut4/unzipped/triton/compiler/compiler.py'
stripping 4 leading component from 'tmp/tmp.ghCYbbdut4/unzipped/triton/compiler/compiler.py'
processing 2/3:  compiler/compiler.py
 hunk no.1 for file compiler/compiler.py  -- is ready to be patched
 hunk no.2 for file compiler/compiler.py  -- is ready to be patched
processing target file compiler/compiler.py
hunk 1
hunk 2
successfully patched 2/3:        compiler/compiler.py
applying patch to 'tmp/tmp.ghCYbbdut4/unzipped/triton/runtime/build.py'
stripping 4 leading component from 'tmp/tmp.ghCYbbdut4/unzipped/triton/runtime/build.py'
processing 3/3:  runtime/build.py
 hunk no.1 for file runtime/build.py  -- is ready to be patched
 hunk no.2 for file runtime/build.py  -- is ready to be patched
processing target file runtime/build.py
hunk 1
hunk 2
successfully patched 3/3:        runtime/build.py
Module 'triton' patched successfully!
inconsistent line ends in patch hunks for /tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_compat.py
inconsistent line ends in patch hunks for /tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_compat.py
inconsistent line ends in patch hunks for /tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_compat.py
inconsistent line ends in patch hunks for /tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_compat.py
inconsistent line ends in patch hunks for /tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_compat.py
inconsistent line ends in patch hunks for /tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_compat.py
inconsistent line ends in patch hunks for /tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/utils.py
inconsistent line ends in patch hunks for /tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/utils.py
total files: 4  total hunks: 15
warning: absolute paths are not allowed (but who cares) - file no.1
stripping absolute path from source name '/tmp/tmp.OOB7NJEiKv/unzipped/torch/_higher_order_ops/triton_kernel_wrap.py'
warning: absolute paths are not allowed (but who cares) - file no.2
stripping absolute path from source name '/tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_compat.py'
warning: absolute paths are not allowed (but who cares) - file no.3
stripping absolute path from source name '/tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_heuristics.py'
warning: absolute paths are not allowed (but who cares) - file no.4
stripping absolute path from source name '/tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/utils.py'
Loaded patch set: PatchSet(type=plain, items=[Patch(source='tmp/tmp.OOB7NJEiKv/unzipped/torch/_higher_order_ops/triton_kernel_wrap.py', target='torch/_higher_order_ops/triton_kernel_wrap.py'), Patch(source='tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_compat.py', target='torch/_inductor/runtime/triton_compat.py'), Patch(source='tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_heuristics.py', target='torch/_inductor/runtime/triton_heuristics.py'), Patch(source='tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/utils.py', target='torch/_inductor/utils.py')])
applying patch to 'tmp/tmp.OOB7NJEiKv/unzipped/torch/_higher_order_ops/triton_kernel_wrap.py'
stripping 4 leading component from 'tmp/tmp.OOB7NJEiKv/unzipped/torch/_higher_order_ops/triton_kernel_wrap.py'
processing 1/4:  _higher_order_ops/triton_kernel_wrap.py
 hunk no.1 for file _higher_order_ops/triton_kernel_wrap.py  -- is ready to be patched
 hunk no.2 for file _higher_order_ops/triton_kernel_wrap.py  -- is ready to be patched
processing target file _higher_order_ops/triton_kernel_wrap.py
hunk 1
hunk 2
successfully patched 1/4:        _higher_order_ops/triton_kernel_wrap.py
applying patch to 'tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_compat.py'
stripping 4 leading component from 'tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_compat.py'
processing 2/4:  _inductor/runtime/triton_compat.py
 hunk no.1 for file _inductor/runtime/triton_compat.py  -- is ready to be patched
 hunk no.2 for file _inductor/runtime/triton_compat.py  -- is ready to be patched
 hunk no.3 for file _inductor/runtime/triton_compat.py  -- is ready to be patched
 hunk no.4 for file _inductor/runtime/triton_compat.py  -- is ready to be patched
 hunk no.5 for file _inductor/runtime/triton_compat.py  -- is ready to be patched
 hunk no.6 for file _inductor/runtime/triton_compat.py  -- is ready to be patched
processing target file _inductor/runtime/triton_compat.py
hunk 1
hunk 2
hunk 3
hunk 4
hunk 5
hunk 6
successfully patched 2/4:        _inductor/runtime/triton_compat.py
applying patch to 'tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_heuristics.py'
stripping 4 leading component from 'tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/runtime/triton_heuristics.py'
processing 3/4:  _inductor/runtime/triton_heuristics.py
 hunk no.1 for file _inductor/runtime/triton_heuristics.py  -- is ready to be patched
 hunk no.2 for file _inductor/runtime/triton_heuristics.py  -- is ready to be patched
 hunk no.3 for file _inductor/runtime/triton_heuristics.py  -- is ready to be patched
 hunk no.4 for file _inductor/runtime/triton_heuristics.py  -- is ready to be patched
 hunk no.5 for file _inductor/runtime/triton_heuristics.py  -- is ready to be patched
processing target file _inductor/runtime/triton_heuristics.py
hunk 1
hunk 2
hunk 3
hunk 4
hunk 5
successfully patched 3/4:        _inductor/runtime/triton_heuristics.py
applying patch to 'tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/utils.py'
stripping 4 leading component from 'tmp/tmp.OOB7NJEiKv/unzipped/torch/_inductor/utils.py'
processing 4/4:  _inductor/utils.py
 hunk no.1 for file _inductor/utils.py  -- is ready to be patched
 hunk no.2 for file _inductor/utils.py  -- is ready to be patched
processing target file _inductor/utils.py
hunk 1
hunk 2
successfully patched 4/4:        _inductor/utils.py
Module 'torch' patched successfully!
 ::  11:01:34  ::  - Installing flash-attention
 ::  11:01:36  ::  - Installing and patching sage-attention

 ::  11:01:36  ::  Custom node(s) installation ...

:: 11:01:36  ::  - Installing CFZ Nodes (description in readme on github)
 ::  11:01:36  ::  - Installing Comfyui Manager
fatal: destination path 'ComfyUI-Manager' already exists and is not an empty directory.
 ::  11:01:36  ::  - Installing ComfyUI-deepcache
fatal: destination path 'ComfyUI-deepcache' already exists and is not an empty directory.
 ::  11:01:36  ::  - Copying python libs
C:\Users\Fred\AppData\Local\Programs\Python\Python312\libs\python3.lib
C:\Users\Fred\AppData\Local\Programs\Python\Python312\libs\python312.lib
C:\Users\Fred\AppData\Local\Programs\Python\Python312\libs\_tkinter.lib
3 File(s) copied

 ::  11:01:36  ::  - Patching ZLUDA
 ::  11:01:37  ::  - ZLUDA 3.9.5 nightly patched for HIP SDK 6.2.4 with miopen and triton-flash attention.

.....................................................
*** Installation is completed in 00:01:07.35 .
*** You can use "comfyui-n.bat" to start the app later.
*** It is advised to make a copy of "comfyui-n.bat" and modify it to your liking so when updating later it won't cause problems.
*** You can use -- "--use-pytorch-cross-attention" , "--use-quad-cross-attention" , "--use-flash-attention" or "--use-sage-attention"
.....................................................

*** Starting the Comfyui-ZLUDA for the first time, please be patient...

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-08-21 11:01:39.224
** Platform: Windows
** Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
** Python executable: C:\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: C:\ComfyUI-Zluda
** ComfyUI Base Folder Path: C:\ComfyUI-Zluda
** User directory: C:\ComfyUI-Zluda\user
** ComfyUI-Manager config path: C:\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: C:\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   1.9 seconds: C:\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
%%% [backported] imported triton knobs

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.25.9
Installed version of comfyui-workflow-templates: 0.1.62
Installed version of av: 15.0.0
Installed version of comfyui-embedded-docs: 0.2.6
  ::  Package version check complete.

  ::  ------------------------ ZLUDA -----------------------  ::
  ::  Auto-detecting AMD GPU architecture for Triton...
  ::  Detected GPU via Windows registry: AMD Radeon RX 9070 XT
  ::  Set TRITON_OVERRIDE_ARCH=gfx1200
  ::  Triton core imported successfully
  ::  Running Triton kernel test...
%%% [info] triton/runtime/build/platform_key: AMD64,Windows,64bit,WindowsPE
  ::  Triton test failed: Triton Error [HIP]:  Code: 209, Messsage: no kernel image is available for execution on the device
  ::  Triton available but failed verification
  ::  Patching ONNX Runtime for ZLUDA — disabling CUDA EP.
  ::  Using ZLUDA with device: AMD Radeon RX 9070 XT [ZLUDA]
  ::  Applying core ZLUDA patches...
  ::  Triton optimizations skipped (not available)
  ::  Configuring PyTorch backends...
  ::  Disabled CUDA flash attention
  ::  Enabled math attention fallback
  ::  ZLUDA initialization complete
  ::  ------------------------ ZLUDA -----------------------  ::

Total VRAM 16304 MB, total RAM 32373 MB
pytorch version: 2.7.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 9070 XT [ZLUDA] : native
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
ComfyUI version: 0.3.51
ComfyUI frontend version: 1.25.9
[Prompt Server] web root: C:\ComfyUI-Zluda\venv\Lib\site-packages\comfyui_frontend_package\static
### Loading: ComfyUI-Manager (V3.36)
[ComfyUI-Manager] network_mode: public
### ComfyUI Revision: 4839 [b717e4f8] | Released on '2025-08-21'

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI-Zluda\custom_nodes\cfz_cudnn.toggle.py
   0.0 seconds: C:\ComfyUI-Zluda\custom_nodes\cfz_vae_loader.py
   0.0 seconds: C:\ComfyUI-Zluda\custom_nodes\cfz_patcher.py
   0.0 seconds: C:\ComfyUI-Zluda\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\ComfyUI-Zluda\custom_nodes\ComfyUI-deepcache
   0.7 seconds: C:\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Context impl SQLiteImpl.
Will assume non-transactional DDL.
No target revision found.
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH ComfyRegistry Data: 5/95
FETCH ComfyRegistry Data: 10/95
FETCH ComfyRegistry Data: 15/95
FETCH ComfyRegistry Data: 20/95
FETCH ComfyRegistry Data: 25/95
FETCH ComfyRegistry Data: 30/95
FETCH ComfyRegistry Data: 35/95
FETCH ComfyRegistry Data: 40/95
FETCH ComfyRegistry Data: 45/95
FETCH ComfyRegistry Data: 50/95
FETCH ComfyRegistry Data: 55/95
FETCH ComfyRegistry Data: 60/95
FETCH ComfyRegistry Data: 65/95
FETCH ComfyRegistry Data: 70/95
FETCH ComfyRegistry Data: 75/95
FETCH ComfyRegistry Data: 80/95
FETCH ComfyRegistry Data: 85/95
FETCH ComfyRegistry Data: 90/95
FETCH ComfyRegistry Data: 95/95
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
[ComfyUI-Manager] The ComfyRegistry cache update is still in progress, so an outdated cache is being used.
FETCH DATA from: C:\ComfyUI-Zluda\user\default\ComfyUI-Manager\cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\ComfyUI-Zluda\user\default\ComfyUI-Manager\cache\746607195_github-stats.json [DONE]
FETCH DATA from: C:\ComfyUI-Zluda\user\default\ComfyUI-Manager\cache\832903789_extras.json [DONE]
FETCH DATA from: C:\ComfyUI-Zluda\user\default\ComfyUI-Manager\cache\1742899825_extension-node-map.json [DONE]
[ComfyUI-Manager] The ComfyRegistry cache update is still in progress, so an outdated cache is being used.
FETCH DATA from: C:\ComfyUI-Zluda\user\default\ComfyUI-Manager\cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\ComfyUI-Zluda\user\default\ComfyUI-Manager\cache\746607195_github-stats.json [DONE]
FETCH DATA from: C:\ComfyUI-Zluda\user\default\ComfyUI-Manager\cache\832903789_extras.json [DONE]
FETCH DATA from: C:\ComfyUI-Zluda\user\default\ComfyUI-Manager\cache\1742899825_extension-node-map.json [DONE]
```

### Other

I'm not using any custom nodes, but haven't taken steps to "disable" them.

Using: 
Radeon RX 9070 XT, 
Ryzen 7 7700X, 
32GB ram

**Comment by Good-luck-Haim** [comment]
set TRITON_OVERRIDE_ARCH=gfx1201

**Comment by patientx** [comment]
Add the line shared above to your comfyui-n.bat (make a copy of the file and use that as launcher ideally, or with every update you would have to delete and re edit the file)

**Comment by roofling** [comment]
I also have a 9070 XT and was running into the Triton error as mentioned by the OP ,where the default is to set the triton architecture to "gfx1200". I was able to generate images though even with that error - the triton optimizations just wouldn't load. Adding the "set TRITON_OVERRIDE_ARCH=gfx1201" to a copy of the comfyui-n.bat fixed my issue and allows Triton to load correctly. So thanks, that fixed my issue. Might be a persistent issue with 9070 XT users where this override is needed?

**Comment by patientx** [comment]
> I also have a 9070 XT and was running into the Triton error as mentioned by the OP ,where the default is to set the triton architecture to "gfx1200". I was able to generate images though even with that error - the triton optimizations just wouldn't load. Adding the "set TRITON_OVERRIDE_ARCH=gfx1201" to a copy of the comfyui-n.bat fixed my issue and allows Triton to load correctly. So thanks, that fixed my issue. Might be a persistent issue with 9070 XT users where this override is needed?

this might be mandatory for most users but I don't know how to make it change to one's gpu model automatically in the batch file. Might add it as a note in the readme.
