### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by N0mad077** [patientx/ComfyUI-Zluda#278]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

Hi, I have a Vega 64 GPU (gfx900), and I was able to get this to work without any issues with HIP SDK 5.7.1. Wanted to try out the HIP SDK 6.2.4 version with all the optimizations that come with it, as the main guide implies that my gpu is still supported. Wiped HIP SDK 5.7.1, installed 6.2.4, checked paths, copied over the HIP SDK Extension, basically followed the guide to the letter three times now using the library `rocblasOct14.7z` and `rocblas.dll` from [here](https://github.com/YellowRoseCx/koboldcpp-rocm/releases/tag/deps-v6.2.0), as [the recommended repo](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.2.4) refers to it for gfx900 gpus. The actual installation using `install-n.bat` and the zluda patch that is called within it all run without errors, but I get the same error every time I start comfy:

> *** Checking and updating to new version if possible
> Already up to date.
> 
> [START] Security scan
> [DONE] Security scan
> ## ComfyUI-Manager: installing dependencies done.
> ** ComfyUI startup time: 2025-08-26 23:48:25.275
> ** Platform: Windows
> ** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
> ** Python executable: G:\ComfyUI-Zluda\venv\Scripts\python.exe
> ** ComfyUI Path: G:\ComfyUI-Zluda
> ** ComfyUI Base Folder Path: G:\ComfyUI-Zluda
> ** User directory: G:\ComfyUI-Zluda\user
> ** ComfyUI-Manager config path: G:\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
> ** Log path: G:\ComfyUI-Zluda\user\comfyui.log
> 
> Prestartup times for custom nodes:
>    2.3 seconds: G:\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
> 
> Checkpoint files will always be loaded safely.
> %%% [backported] imported triton knobs
> 
>   ::  Checking package versions...
> Found pydantic: 2.11.7, pydantic-settings: 2.10.1
>   ::  Pydantic packages are compatible, skipping reinstall
> Installed version of comfyui-frontend-package: 1.25.10
> Installed version of comfyui-workflow-templates: 0.1.66
> Installed version of av: 15.0.0
> Installed version of comfyui-embedded-docs: 0.2.6
>   ::  Package version check complete.
> 
>   ::  ------------------------ ZLUDA -----------------------  ::
>   ::  Triton core imported successfully
>   ::  Enabled cuDNN
>   ::  Running Triton kernel test...
>   ::  Triton test failed: No CUDA GPUs are available
>   ::  Triton available but failed verification
>   ::  CUDA device detected: None
> Traceback (most recent call last):
>   File "G:\ComfyUI-Zluda\main.py", line 147, in <module>
>     import execution
>   File "G:\ComfyUI-Zluda\execution.py", line 15, in <module>
>     import comfy.model_management
>   File "G:\ComfyUI-Zluda\comfy\model_management.py", line 237, in <module>
>     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
>                                   ^^^^^^^^^^^^^^^^^^
>   File "G:\ComfyUI-Zluda\comfy\model_management.py", line 187, in get_torch_device
>     return torch.device(torch.cuda.current_device())
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 1026, in current_device
>     _lazy_init()
>   File "G:\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 372, in _lazy_init
>     torch._C._cuda_init()
> RuntimeError: No CUDA GPUs are available
> Press any key to continue . . .

 `testzluda.py` with the venv activated also fails, and `hipinfo` returns:

> checkHipErrors() HIP API error = 0100 "no ROCm-capable device is detected" from file <C:\constructicon\builds\gfx\eleven\24.20\drivers\compute\hip-tests\samples\1_Utils\hipInfo\hipInfo.cpp>, line 192.

If anyone got their gfx900 gpu to work with 6.2.4, I'd really appreciate some pointers. Any help would be much appreciated, as I really want to try out the optimizations.

### Logs

```powershell

```

**Comment by patientx** [comment]
To be honest some told me it was possible but I haven't seen anyone who successfully did it, I put it in the second section because there are libraries for vega for 6.2.4. You can perhaps try the "legacy" version which doesn't use triton stuff  just 6.2.4  and newer torch ( It might work with non nightly zluda plus older gpu drivers than 25.5.1 , that's just a guess) or go back to 2.2, the old setup :/ sorry but I can't test I only have one gpu.

**Comment by N0mad077** [comment]
> To be honest some told me it was possible but I haven't seen anyone who successfully did it, I put it in the second section because there are libraries for vega for 6.2.4. You can perhaps try the "legacy" version which doesn't use triton stuff just 6.2.4 and newer torch ( It might work with non nightly zluda plus older gpu drivers than 25.5.1 , that's just a guess) or go back to 2.2, the old setup :/ sorry but I can't test I only have one gpu.

Ty for replying! No need to apologize. Would you mind dropping a link for the vega 6.2.4 libraries? Also how would I go about making the installers install non-nightly zluda?

**Comment by patientx** [comment]
we only have this as far as I know , "https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/download/v0.6.2.4/rocm.gfx90c-xnack-.for.hip.skd.6.2.4.7z"

"install-legacy.bat " uses non-nightly zluda, try it. Again not %100 sure.

**Comment by Ashir555** [comment]
I might be wrong here but, install-n it's for triton enabled cards right?, like 6000 series and up.

You should try just with install instead of install-n

**Comment by mlsterpr0** [comment]
Hi,i guess i have similar problem. My gpu is gfx1035 . Amd ryzen 7735hs with 680m (driver - Adrenalin 25.6.1 (WHQL Recommended). First i had virus warning, which stopped the start up of comfyui. After dealing with that and running install-n.bat again, it almost launched, but...:

```
*** Checking and updating to new version if possible
Already up to date.

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-08-30 17:55:13.737
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\COMFY_ZLUDA\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: C:\COMFY_ZLUDA\ComfyUI-Zluda
** ComfyUI Base Folder Path: C:\COMFY_ZLUDA\ComfyUI-Zluda
** User directory: C:\COMFY_ZLUDA\ComfyUI-Zluda\user
** ComfyUI-Manager config path: C:\COMFY_ZLUDA\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: C:\COMFY_ZLUDA\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   2.1 seconds: C:\COMFY_ZLUDA\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.25.11
Installed version of comfyui-workflow-templates: 0.1.70
Installed version of av: 15.1.0
Installed version of comfyui-embedded-docs: 0.2.6
  ::  Package version check complete.

  ::  ------------------------ ZLUDA -----------------------  ::
  ::  Triton core imported successfully
  ::  Enabled cuDNN
  ::  Running Triton kernel test...
  ::  Triton test failed: No CUDA GPUs are available
  ::  Triton available but failed verification
  ::  CUDA device detected: None
Traceback (most recent call last):
  File "C:\COMFY_ZLUDA\ComfyUI-Zluda\main.py", line 148, in <module>
    import execution
  File "C:\COMFY_ZLUDA\ComfyUI-Zluda\execution.py", line 15, in <module>
    import comfy.model_management
  File "C:\COMFY_ZLUDA\ComfyUI-Zluda\comfy\model_management.py", line 237, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "C:\COMFY_ZLUDA\ComfyUI-Zluda\comfy\model_management.py", line 187, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFY_ZLUDA\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 1026, in current_device
    _lazy_init()
  File "C:\COMFY_ZLUDA\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 372, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```
i'm not familiar with all this, but i really did everything according to installation instructions. Hope someone will help :)

**Comment by patientx** [comment]
> i'm not familiar with all this, but i really did everything according to installation instructions. Hope someone will help :)

your gpu didn't have libraries for 6.4 I hope you followed the second option to install comfy. 

Have you installed 6.2 with the addon THEN used the correct libraries for your gpu here : [rocm.gfx1034-gfx1035-gfx1036.for.hip.sdk.6.2.4.7z](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/download/v0.6.2.4/rocm.gfx1034-gfx1035-gfx1036.for.hip.sdk.6.2.4.7z) ? 

EDIT : As I am writing this answer there are now libraries for 6.4 many of the gpu's now , seems like "likelovewant" released them recently. Check here if you want to try 6.4 BUT remember to completely delete the 6.2 hip folder from program files\amd\rocm ... otherwise they would mix, my suggestion first make sure you are using the correct 6.2 hip + addon + libraries THEN if it doesn't work or you want try 6.4, use the new libraries. https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.4.2 , these are new libraries for hip 6.4.2. AGAIN first try 6.2 then if it doesn't work, because I don't know if it would, no one tested them yet,  then try this new ones with 6.4.

**Comment by mlsterpr0** [comment]
> EDIT : As I am writing this answer there are now libraries for 6.4 many of the gpu's now , seems like "likelovewant" released them recently. Check here if you want to try 6.4 BUT remember to completely delete the 6.2 hip folder from program files\amd\rocm ... otherwise they would mix, my suggestion first make sure you are using the correct 6.2 hip + addon + libraries THEN if it doesn't work or you want try 6.4, use the new libraries. https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.4.2 , these are new libraries for hip 6.4.2. AGAIN first try 6.2 then if it doesn't work, because I don't know if it would, no one tested them yet, then try this new ones with 6.4.

Thanks you for reply. Yes, i followed "For GPU's below 6800..." setup, which is 6.2.4 with addon and so on (all steps of course). Only now i realized my gpu is also listed under "For GPU's above 6800..." which is 6.4.2 :) Maybe i should try that too. But at the moment i don't see 7z for gfx1035 under the link you provided, maybe it will appear later...

**Comment by ukromalybot** [comment]
I am trying for 2 days to make gfx906 radeon vii working. i've done dozens of reinstalls. please advice.
Done:
hip 6.2
Instructions for For GPU's below 6800 (VEGA, RX 5000 and remaining 6000's; 6700, 6600 etc) no errors
All paths okay

When running:
```
b:\ComfyUIAMD\ComfyUI-Zluda>zluda\zluda.exe -- venv\Scripts\python main.py --auto-launch --use-quad-cross-attention
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-09-03 06:58:56.378
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: b:\ComfyUIAMD\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: b:\ComfyUIAMD\ComfyUI-Zluda
** ComfyUI Base Folder Path: b:\ComfyUIAMD\ComfyUI-Zluda
** User directory: B:\ComfyUIAMD\ComfyUI-Zluda\user
** ComfyUI-Manager config path: B:\ComfyUIAMD\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: B:\ComfyUIAMD\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   2.9 seconds: B:\ComfyUIAMD\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
%%% [backported] imported triton knobs

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.25.11
Installed version of comfyui-workflow-templates: 0.1.73
Installed version of av: 15.1.0
Installed version of comfyui-embedded-docs: 0.2.6
  ::  Package version check complete.

  ::  ------------------------ ZLUDA -----------------------  ::
  ::  Triton core imported successfully
  ::  Enabled cuDNN
  ::  Running Triton kernel test...
  ::  Triton test failed: No CUDA GPUs are available
  ::  Triton available but failed verification
  ::  CUDA device detected: None
Traceback (most recent call last):
  File "b:\ComfyUIAMD\ComfyUI-Zluda\main.py", line 147, in <module>
    import execution
  File "b:\ComfyUIAMD\ComfyUI-Zluda\execution.py", line 15, in <module>
    import comfy.model_management
  File "b:\ComfyUIAMD\ComfyUI-Zluda\comfy\model_management.py", line 237, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "b:\ComfyUIAMD\ComfyUI-Zluda\comfy\model_management.py", line 187, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "b:\ComfyUIAMD\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 1026, in current_device
    _lazy_init()
  File "b:\ComfyUIAMD\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 372, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

In one of the reinstallation it was successfuly detected with 32 GB VRAM, but sageattention and some other errors were there. So i am keeping reinstalling and testing different things. But now i'm stuck

**Comment by Ashir555** [comment]
> I am trying for 2 days to make gfx906 radeon vii working. i've done dozens of reinstalls. please advice. Done: hip 6.2 Instructions for For GPU's below 6800 (VEGA, RX 5000 and remaining 6000's; 6700, 6600 etc) no errors All paths okay
> 
> When running:

>   ::  ------------------------ ZLUDA -----------------------  ::
>   ::  Triton core imported successfully
>   ::  Enabled cuDNN
>   ::  Running Triton kernel test...
>   ::  Triton test failed: No CUDA GPUs are available
>   ::  Triton available but failed verification
>   ::  CUDA device detected: None

> RuntimeError: No CUDA GPUs are available
> ```

Try running ComfyUI-Zluda without triton

`.\zluda\zluda.exe -- %PYTHON% main.py --use-quad-cross-attention --reserve-vram 0.9 `

**Comment by ukromalybot** [comment]
> > I am trying for 2 days to make gfx906 radeon vii working. i've done dozens of reinstalls. please advice. Done: hip 6.2 Instructions for For GPU's below 6800 (VEGA, RX 5000 and remaining 6000's; 6700, 6600 etc) no errors All paths okay
> > When running:
> 
> > ::  ------------------------ ZLUDA -----------------------  ::
> > ::  Triton core imported successfully
> > ::  Enabled cuDNN
> > ::  Running Triton kernel test...
> > ::  Triton test failed: No CUDA GPUs are available
> > ::  Triton available but failed verification
> > ::  CUDA device detected: None
> 
> > RuntimeError: No CUDA GPUs are available
> 
> Try running ComfyUI-Zluda without triton
> 
> `.\zluda\zluda.exe -- %PYTHON% main.py --use-quad-cross-attention --reserve-vram 0.9 `

```
b:\ComfyUIAMD\ComfyUI-Zluda>.\zluda\zluda.exe -- %PYTHON% main.py --use-quad-cross-attention --reserve-vram 0.9
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-09-03 07:13:11.513
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: b:\ComfyUIAMD\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: b:\ComfyUIAMD\ComfyUI-Zluda
** ComfyUI Base Folder Path: b:\ComfyUIAMD\ComfyUI-Zluda
** User directory: B:\ComfyUIAMD\ComfyUI-Zluda\user
** ComfyUI-Manager config path: B:\ComfyUIAMD\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: B:\ComfyUIAMD\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   4.1 seconds: B:\ComfyUIAMD\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
%%% [backported] imported triton knobs

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.25.11
Installed version of comfyui-workflow-templates: 0.1.73
Installed version of av: 15.1.0
Installed version of comfyui-embedded-docs: 0.2.6
  ::  Package version check complete.

  ::  ------------------------ ZLUDA -----------------------  ::
  ::  Triton core imported successfully
  ::  Enabled cuDNN
  ::  Running Triton kernel test...
  ::  Triton test failed: No CUDA GPUs are available
  ::  Triton available but failed verification
  ::  CUDA device detected: None
Traceback (most recent call last):
  File "b:\ComfyUIAMD\ComfyUI-Zluda\main.py", line 147, in <module>
    import execution
  File "b:\ComfyUIAMD\ComfyUI-Zluda\execution.py", line 15, in <module>
    import comfy.model_management
  File "b:\ComfyUIAMD\ComfyUI-Zluda\comfy\model_management.py", line 237, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "b:\ComfyUIAMD\ComfyUI-Zluda\comfy\model_management.py", line 187, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "b:\ComfyUIAMD\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 1026, in current_device
    _lazy_init()
  File "b:\ComfyUIAMD\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 372, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

b:\ComfyUIAMD\ComfyUI-Zluda>venv\Scripts\activate.bat

(venv) b:\ComfyUIAMD\ComfyUI-Zluda>.\zluda\zluda.exe -- %PYTHON% main.py --use-quad-cross-attention --reserve-vram 0.9
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-09-03 07:14:07.360
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: b:\ComfyUIAMD\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: b:\ComfyUIAMD\ComfyUI-Zluda
** ComfyUI Base Folder Path: b:\ComfyUIAMD\ComfyUI-Zluda
** User directory: B:\ComfyUIAMD\ComfyUI-Zluda\user
** ComfyUI-Manager config path: B:\ComfyUIAMD\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: B:\ComfyUIAMD\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   3.5 seconds: B:\ComfyUIAMD\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
%%% [backported] imported triton knobs

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.25.11
Installed version of comfyui-workflow-templates: 0.1.73
Installed version of av: 15.1.0
Installed version of comfyui-embedded-docs: 0.2.6
  ::  Package version check complete.

  ::  ------------------------ ZLUDA -----------------------  ::
  ::  Triton core imported successfully
  ::  Enabled cuDNN
  ::  Running Triton kernel test...
  ::  Triton test failed: No CUDA GPUs are available
  ::  Triton available but failed verification
  ::  CUDA device detected: None
Traceback (most recent call last):
  File "b:\ComfyUIAMD\ComfyUI-Zluda\main.py", line 147, in <module>
    import execution
  File "b:\ComfyUIAMD\ComfyUI-Zluda\execution.py", line 15, in <module>
    import comfy.model_management
  File "b:\ComfyUIAMD\ComfyUI-Zluda\comfy\model_management.py", line 237, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "b:\ComfyUIAMD\ComfyUI-Zluda\comfy\model_management.py", line 187, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "b:\ComfyUIAMD\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 1026, in current_device
    _lazy_init()
  File "b:\ComfyUIAMD\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 372, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

(venv) b:\ComfyUIAMD\ComfyUI-Zluda>python --version
Python 3.11.9

(venv) b:\ComfyUIAMD\ComfyUI-Zluda>.\zluda\zluda.exe -- python main.py --use-quad-cross-attention --reserve-vram 0.9
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-09-03 07:14:31.176
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: b:\ComfyUIAMD\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: b:\ComfyUIAMD\ComfyUI-Zluda
** ComfyUI Base Folder Path: b:\ComfyUIAMD\ComfyUI-Zluda
** User directory: B:\ComfyUIAMD\ComfyUI-Zluda\user
** ComfyUI-Manager config path: B:\ComfyUIAMD\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: B:\ComfyUIAMD\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   3.3 seconds: B:\ComfyUIAMD\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
%%% [backported] imported triton knobs

  ::  Checking package versions...
Found pydantic: 2.11.7, pydantic-settings: 2.10.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.25.11
Installed version of comfyui-workflow-templates: 0.1.73
Installed version of av: 15.1.0
Installed version of comfyui-embedded-docs: 0.2.6
  ::  Package version check complete.

  ::  ------------------------ ZLUDA -----------------------  ::
  ::  Triton core imported successfully
  ::  Enabled cuDNN
  ::  Running Triton kernel test...
  ::  Triton test failed: No CUDA GPUs are available
  ::  Triton available but failed verification
  ::  CUDA device detected: None
Traceback (most recent call last):
  File "b:\ComfyUIAMD\ComfyUI-Zluda\main.py", line 147, in <module>
    import execution
  File "b:\ComfyUIAMD\ComfyUI-Zluda\execution.py", line 15, in <module>
    import comfy.model_management
  File "b:\ComfyUIAMD\ComfyUI-Zluda\comfy\model_management.py", line 237, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "b:\ComfyUIAMD\ComfyUI-Zluda\comfy\model_management.py", line 187, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "b:\ComfyUIAMD\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 1026, in current_device
    _lazy_init()
  File "b:\ComfyUIAMD\ComfyUI-Zluda\venv\Lib\site-packages\torch\cuda\__init__.py", line 372, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

```
:(

{'torch': '2.7.0+cu118', 'torchvision': '0.22.0+cu118', 'torchaudio': '2.7.0+cu118', 'triton': '3.4.0', 'zluda': 'imported'}

**Comment by ukromalybot** [comment]
One of install without no cuda GPUs error, idk if it will help for people have CUDA error.
```
Installed version of comfyui-embedded-docs: 0.2.6
  ::  Package version check complete.

  ::  ------------------------ ZLUDA -----------------------  ::
  ::  TRITON_OVERRIDE_ARCH already set to: gfx906
  ::  Triton not installed
  ::  ONNX Runtime not installed — skipping patch.
  ::  Using ZLUDA with device: AMD Radeon VII [ZLUDA]
  ::  Applying core ZLUDA patches...
  ::  Triton optimizations skipped (not available)
  ::  Configuring PyTorch backends...
  ::  Disabled CUDA flash attention
  ::  Enabled math attention fallback
  ::  ZLUDA initialization complete
  ::  ------------------------ ZLUDA -----------------------  ::

Total VRAM 32752 MB, total RAM 32653 MB
pytorch version: 2.7.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon VII [ZLUDA] : native
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
torchaudio missing, ACE model will be broken
torchaudio missing, ACE model will be broken
Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
ComfyUI version: 0.3.56
ComfyUI frontend version: 1.25.11
[Prompt Server] web root: b:\ComfyUINEW\ComfyUI\venv\Lib\site-packages\comfyui_frontend_package\static
Traceback (most recent call last):
  File "b:\ComfyUINEW\ComfyUI\nodes.py", line 2129, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "B:\ComfyUINEW\ComfyUI\comfy_extras\nodes_audio.py", line 4, in <module>
    import torchaudio
  File "b:\ComfyUINEW\ComfyUI\venv\Lib\site-packages\torchaudio\__init__.py", line 3, in <module>
    from ._backend import (  # noqa  # usort: skip
  File "b:\ComfyUINEW\ComfyUI\venv\Lib\site-packages\torchaudio\_backend\__init__.py", line 5, in <module>
    from . import utils
  File "b:\ComfyUINEW\ComfyUI\venv\Lib\site-packages\torchaudio\_backend\utils.py", line 8, in <module>
    from torchaudio.io import CodecConfig
  File "b:\ComfyUINEW\ComfyUI\venv\Lib\site-packages\torchaudio\io\__init__.py", line 1, in <module>
    from torio.io import CodecConfig, StreamingMediaDecoder as StreamReader, StreamingMediaEncoder as StreamWriter
ModuleNotFoundError: No module named 'torio'
```
ComfyUI+ Zlulda it's like black magic, you need to practice :D

**Comment by Ashir555** [comment]
Weird because in the same folder I have ComfyUI-Zluda with and WITHOUT Triton, if I need the second I run comfyui they way I told you and it don't invoke Triton, even if is installed...

**Comment by ukromalybot** [comment]
yeah weird, will try some other YT tutorials, maybe it will work :D
Now i have RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by ukromalybot** [comment]
@N0mad077 
> ### Your question
> Hi, I have a Vega 64 GPU (gfx900) running the latest WHQL Adrenaline driver, and I was able to get this to work without any issues with HIP SDK 5.7.1. Wanted to try out the HIP SDK 6.2.4 version with all the optimizations that come with it, as the main guide implies that my gpu is still supported. Wiped HIP SDK 5.7.1, installed 6.2.4, checked paths, copied over the HIP SDK Extension, basically followed the guide to the letter three times now using the library `rocblasOct14.7z` and `rocblas.dll` from [here](https://github.com/YellowRoseCx/koboldcpp-rocm/releases/tag/deps-v6.2.0), as [the recommended repo](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.2.4) refers to it for gfx900 gpus. The actual installation using `install-n.bat` and the zluda patch that is called within it all run without errors, but I get the same error every time I start comfy:


Would you mind and tell me how you were able to install with hip 5.7.1 and make it work?

**Comment by Ashir555** [comment]
> yeah weird, will try some other YT tutorials, maybe it will work :D Now i have RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

You fix that by using patchzluda2.bat

**Comment by ukromalybot** [comment]
I have reinstalled from scratch

patched with https://github.com/lshqqytiger/ZLUDA/releases/download/rel.5e717459179dc272b7d7d23391f0fad66c7459cf/ZLUDA-windows-rocm6-amd64.zip

RuntimeError: No CUDA GPUs are available
My other that didn't made this error is not working. i might broke something...

**Comment by ukromalybot** [comment]
interesting observation if i run
```
@echo off
REM ===============================
REM Launch ComfyUI using AMD MI50
REM via ZLUDA (CUDA shim)
REM ===============================

REM 1. Disable NVIDIA GPUs for this session (optional, safest)
set CUDA_VISIBLE_DEVICES=

REM 2. Enable ZLUDA
set ZLUDA_ENABLE=1

REM 3. Select AMD GPU (0 = first HIP device)
set HIP_VISIBLE_DEVICES=0

REM 4. Make sure nvcuda.dll from ZLUDA is in your venv Scripts folder
REM Copy nvcuda.dll to: b:\ComfyUI\ComfyUI\venv\Scripts\

REM 5. Activate venv
call b:\ComfyUI\ComfyUI\venv\Scripts\activate.bat

REM 6. Run ComfyUI
python main.py

pause

```

RTX 3060 is detected (i have second GPU in my system)

If i run standart comfyui-user.bat
It is giving me cuda error and doesn't see MI50 card

**Comment by Ashir555** [comment]
> I have reinstalled from scratch
> 
> patched with https://github.com/lshqqytiger/ZLUDA/releases/download/rel.5e717459179dc272b7d7d23391f0fad66c7459cf/ZLUDA-windows-rocm6-amd64.zip
> 
> RuntimeError: No CUDA GPUs are available My other that didn't made this error is not working. i might broke something...

You have to use patchzluda2.bat, included in ComfyUI-Zluda folder.

**Comment by ukromalybot** [comment]
@Ashir555 Yes it is asking me for url to paste:
```
===============================================
Custom ZLUDA Patcher (Specifically for HIP 6.x)
===============================================


Type or paste (right click on window to paste) the URL of ZLUDA version you want to download, then press ENTER:
Make sure it is a Windows build (e.g., ends with amd64.zip).
Example URL:
https://github.com/lshqqytiger/ZLUDA/releases/download/rel.d60bddbc870827566b3d2d417e00e1d2d8acc026/ZLUDA-windows-rocm6-amd64.zip

Enter URL:



```

**Comment by Ashir555** [comment]
Try this one.

https://github.com/lshqqytiger/ZLUDA/releases/download/rel.5e717459179dc272b7d7d23391f0fad66c7459cf/ZLUDA-windows-rocm6-amd64.zip

**Comment by ukromalybot** [comment]
@Ashir555 this is the exact one that i patched (https://github.com/patientx/ComfyUI-Zluda/issues/278#issuecomment-3248751366) and afterwards CUDA GPU error

**Comment by patientx** [comment]
No cuda errors mostly occur on using older than 25.5.1 drivers.

**Comment by ukromalybot** [comment]
Radeon VII / MI50 Driver Version 31.0.23013.14001 (Adrenalin 25.3.1) DCH / Win11 64
sooo bad luck for me? :(

**Comment by Ashir555** [comment]
> No cuda errors mostly occur on using older than 25.5.1 drivers.

Actually I update my drivers to v25.8.1 and I don't have CUDA errors, but of course, I have a different GPU.

@ukromalybot Try drivers v25.4.1

**Comment by ukromalybot** [comment]
this was the latest AMD-ID drivers. so i think i am forced to move to linux :(

**Comment by Rando717** [comment]
> this was the latest AMD-ID drivers. so i think i am forced to move to linux :(
>
 @ukromalybot  id drivers as in radeon-id/amernine? Did you try official drivers? 
If not mistaken Polaris/Vega cards are on extended support, only quarterly releases, 25.3.1 is unofficial.
Officially for Radeon VII (Vega 20/gfx906) you can try 25.8.1, 25.5.1, 24.9.1 or older.

You should try doing one step at a time, first make sure hip 6.2 actually works on your card and drivers.
From there pick zluda version that works with your drivers version (rocm6-nighty above v25.5.1 / rocm6 v25.5.1 or above). 
Try comfyui without triton, than try fiddling with triton and extra stuff.

> Radeon VII / MI50 Driver Version 31.0.23013.14001 (Adrenalin 25.3.1) DCH / Win11 64 sooo bad luck for me? :(
>
As I was writing reply I noticed your post #286, so turns out it's MI50 (32 GB) with Radeon VII (16 GB) bios. Gotcha.

@patientx 
Would adding:
```

    "AMD Radeon RX Vega 64": 2048,
    "AMD Radeon RX Vega 56": 2048,
    "AMD Radeon VII": 4096,

```
inside **zluda.py** have any use case for users with vega10/20 (gfx900/gfx906) GCN5 cards?

**Comment by mlsterpr0** [comment]
I thought i would never get to use zluda with my ryzen 7735hs, but  miracle happened, actually two :) First was that someone suggested to try "stability matrix" (it makes everything easier and has Comfyui Zluda). But the error still existed. So the second miracle was that i accidentally tried  "--cuda-device 0" in launch options. It's probably at "1" by default. And now it works :) I guess i can finally stop using directml, which doesn't even work properly.

It's incredible how this little "--cuda-device 0" changes everything. And i didn't even see any info about this...(saw this arg under "--help" and just tried)

**Comment by ukromalybot** [comment]
> > this was the latest AMD-ID drivers. so i think i am forced to move to linux :(
> 
> [@ukromalybot](https://github.com/ukromalybot) id drivers as in radeon-id/amernine? Did you try official drivers? If not mistaken Polaris/Vega cards are on extended support, only quarterly releases, 25.3.1 is unofficial. Officially for Radeon VII (Vega 20/gfx906) you can try 25.8.1, 25.5.1, 24.9.1 or older.
> 
> You should try doing one step at a time, first make sure hip 6.2 actually works on your card and drivers. From there pick zluda version that works with your drivers version (rocm6-nighty above v25.5.1 / rocm6 v25.5.1 or above). Try comfyui without triton, than try fiddling with triton and extra stuff.
> 
> > Radeon VII / MI50 Driver Version 31.0.23013.14001 (Adrenalin 25.3.1) DCH / Win11 64 sooo bad luck for me? :(
> 
> As I was writing reply I noticed your post [#286](https://github.com/patientx/ComfyUI-Zluda/issues/286), so turns out it's MI50 (32 GB) with Radeon VII (16 GB) bios. Gotcha.
> 
> [@patientx](https://github.com/patientx) Would adding:
> 
> ```
> 
>     "AMD Radeon RX Vega 64": 2048,
>     "AMD Radeon RX Vega 56": 2048,
>     "AMD Radeon VII": 4096,
> ```
> 
> inside **zluda.py** have any use case for users with vega10/20 (gfx900/gfx906) GCN5 cards?

amd-software-adrenalin-edition-25.8.1-minimalsetup-250801_web.exe
and
whql-amd-software-adrenalin-edition-25.5.1-win10-win11-may8-vega-polaris.exe
same error
```
Oops! Something went wrong.
Error 182 - AMD Software Installer detected AMD graphics hardware in your system configuration that is not supported
```
Mi50 flashed with Radeon VII vbios (LM Studio working perfectly on windows)

<img width="510" height="657" alt="Image" src="https://github.com/user-attachments/assets/7c332256-bbba-4504-9e4c-4658895a2edb" />

**Comment by ukromalybot** [comment]
Moved to ubuntu 24.04.1, working right away. qwen image edit generation 1 image 30 minutes D: need to find better workflow with sageattention :D

**Comment by awkk111** [comment]
I used for my integrated GPU.
set "COMMANDLINE_ARGS=--auto-launch --use-quad-cross-attention --reserve-vram 0.9 --cuda-device 0"

**Comment by TheFerumn** [comment]
https://github.com/advanced-lvl-up/Rx470-Vega10-Rx580-gfx803-gfx900-fix-AMD-GPU/releases/download/v1.0.0/rocm.gfx800-gfx900-for.hip.sdk.5.7.1-and-6.2.4.7z

I suggest you to try this files
