### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by capitano799** [patientx/ComfyUI-Zluda#28]
### Your question

Got an issue after following the installation instructions. When clicking on comfyui.bat it fails to open with the error RuntimeError: No CUDA GPUs are available. 
Under "logs" you can see the content of the  "comfyui.log" file. 

What I've done: 
-formerly nvidia GPU installed, uninstalled with DDU untility
-deleting venv
-pip cache purge

I hope you can help me. 
Thanks in advance!

### Logs

```powershell
## ComfyUI-Manager: installing dependencies. (GitPython)
[2024-10-13 00:29] ## ComfyUI-Manager: installing dependencies done.
[2024-10-13 00:29] ** ComfyUI startup time: 2024-10-13 00:29:02.809279
[2024-10-13 00:29] ** Platform: Windows
[2024-10-13 00:29] ** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
[2024-10-13 00:29] ** Python executable: C:\Users\fisch\Dateien\StableDiffusion\ComfyUI-Zluda\venv\Scripts\python.exe
[2024-10-13 00:29] ** ComfyUI Path: C:\Users\fisch\Dateien\StableDiffusion\ComfyUI-Zluda
[2024-10-13 00:29] ** Log path: C:\Users\fisch\Dateien\StableDiffusion\ComfyUI-Zluda\comfyui.log
[2024-10-13 00:29] 
Prestartup times for custom nodes:
[2024-10-13 00:29]   10.0 seconds: C:\Users\fisch\Dateien\StableDiffusion\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2024-10-13 00:29] 
Traceback (most recent call last):
[2024-10-13 00:29]   File "C:\Users\fisch\Dateien\StableDiffusion\ComfyUI-Zluda\main.py", line 90, in <module>
[2024-10-13 00:29]     import execution
[2024-10-13 00:29]   File "C:\Users\fisch\Dateien\StableDiffusion\ComfyUI-Zluda\execution.py", line 13, in <module>
[2024-10-13 00:29]     import nodes
[2024-10-13 00:29]   File "C:\Users\fisch\Dateien\StableDiffusion\ComfyUI-Zluda\nodes.py", line 21, in <module>
[2024-10-13 00:29]     import comfy.diffusers_load
[2024-10-13 00:29]   File "C:\Users\fisch\Dateien\StableDiffusion\ComfyUI-Zluda\comfy\diffusers_load.py", line 3, in <module>
[2024-10-13 00:29]     import comfy.sd
[2024-10-13 00:29]   File "C:\Users\fisch\Dateien\StableDiffusion\ComfyUI-Zluda\comfy\sd.py", line 5, in <module>
[2024-10-13 00:29]     from comfy import model_management
[2024-10-13 00:29]   File "C:\Users\fisch\Dateien\StableDiffusion\ComfyUI-Zluda\comfy\model_management.py", line 143, in <module>
[2024-10-13 00:29]     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
[2024-10-13 00:29]   File "C:\Users\fisch\Dateien\StableDiffusion\ComfyUI-Zluda\comfy\model_management.py", line 112, in get_torch_device
[2024-10-13 00:29]     return torch.device(torch.cuda.current_device())
[2024-10-13 00:29]   File "C:\Users\fisch\Dateien\StableDiffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
[2024-10-13 00:29]     _lazy_init()
[2024-10-13 00:29]   File "C:\Users\fisch\Dateien\StableDiffusion\ComfyUI-Zluda\venv\lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
[2024-10-13 00:29]     torch._C._cuda_init()
[2024-10-13 00:29] RuntimeError: No CUDA GPUs are available
```

**Comment by patientx** [comment]
TO BE ON THE SAFE SIDE :: Uninstall all gpu drivers (nvidia and amd) with DDU,
Uninstall hip ,reinstall display drivers and HIP SDK (make sure 5.7.x) again. After these are installed before trying out the comfy , you can test if your gpu is correctly recognised with this ,

run "hipinfo" on a cmd window.

The output should start like this 

--------------------------------------------------------------------------------
device#                           0
Name:                             AMD Radeon RX 6600
pciBusID:                         12
...

If you see your amd gpu correctly, now delete and reinstall comfy from the start -including venv-

**Comment by capitano799** [comment]
Thanks, I got it working now. 
My GPU wasn't detected with "hipinfo", which was caused by some old system variables from previous installs. Deleted any additional variables that where stable diffusion related but not exactly like in your installation description and the GPU was recognized correctly.

**Comment by TroitiARTs** [comment]
Hello guys, I'm having the same issue over here.

I've gone through what @patientx suggested above, uninstalled and re-installed the graphic card drivers and the HIP SDK packages, and after running the hipinfo command I receive the following error:

←[31merror: 'no ROCm-capable device is detected'(100) at C:\constructicon\builds\gfx\two\23.30\drivers\compute\hip-tests\samples\1_Utils\hipInfo\hipInfo.cpp:205←[0m
←[31merror: API returned error code.
error: TEST FAILED
←[0m

Any ideas of what could be happening? I have a AMD Radeon RX 6700 XT.

**Comment by patientx** [comment]
5.7.1 installed - paths are correct /including the bin one/ - correct libraries are put , always one or some of those are the culprit. also have the latest gpu driver as well for a good measure ...

**Comment by TroitiARTs** [comment]
Hmmmm I've done that now two or three times, making sure that I'm following the right steps, but I can't seem to make it work, I still get the same error when running "hipinfo".

I've copied the files from the updated rocm libraries as described and updated the system variables, that's really the only two manual steps that I have to undergo, but still no luck!

Here's a look at my HIP variables:
![image](https://github.com/user-attachments/assets/8bf156cf-fbae-4da4-959c-4eb0f5e7f7c0)

and my path variables:
![image](https://github.com/user-attachments/assets/1b8767b1-1443-4de2-8e7d-9efa55d95c68)
