### ISSUE TITLE
cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by zolotov7200** [patientx/ComfyUI-Zluda#280]
I got this error on sampler when trying to generate a video using the Wan2.2 All-In-One workflow from the cfz folder:
`cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnSgesvdj(handle, jobz, econ, m, n, A, lda, S, U, ldu, V, ldv, work, lwork, info, params)`. If you keep seeing this error, you may use `torch.backends.cuda.preferred_linalg_library()` to try linear algebra operators with other supported backends. See https://pytorch.org/docs/stable/backends.html#torch.backends.cuda.preferred_linalg_library`
I didn't run 1step-cudnn-disabler-workflow before generating, and here is my .bat for running: [comfyui-n-alt.txt](https://github.com/user-attachments/files/22048492/comfyui-n-alt.txt)
Installation is clean, using the original install-n.bat

**Comment by patientx** [comment]
first time seeing this , maybe memory related ? I don't know. what is your gpu and system ram situation, what models are you using ? with models like wan at first start with lowest resolution + framecount then go higher , like start from 320x240x33 maybe even lower if your gpu isn't powerful enough. also again if vram is scarce go for higher block swap numbers. just make it work then change things to get faster.  

Also @sfinktah could this be because of cudnn again ...

**Comment by sfinktah** [comment]
never seen anything like that one before, but best double check what gpu he's running, i seem to recall it's one of the new ones. 

if it is cudnn related it's even money whether it would work better WITH or WITHOUT cudnn (if it's a gfx1151 or somesuch)

**Comment by zolotov7200** [comment]
> what models are you using ?

Kijai's Wan 2.2 I2V fp8_e5m2_scaled models with block_swap 15 (generating 64x64x81 and other resolutions). I didn't use Loras.

> gpu and system ram

They are not fully loaded, but in total (on system) 32 GB RAM + 100 GB page + 16 GB VRAM (RX 7600 XT).

**Comment by zolotov7200** [comment]
Before recent updates (related to disabling cudnn, moving to hip sdk 6.4 and maybe something else) I have not seen such a problem.

**Comment by sfinktah** [comment]
Can you list all the changes/updates that you have applied, and what version(s) you were running when everything worked?

**Comment by zolotov7200** [comment]
> Can you list all the changes/updates that you have applied

I'm talking about the install-n changes that patienx made, namely commented out the line with cudnn, but I don't think it's somehow related, rather the transition to HIP SDK 6.4 or the transition to installing VS Build Tools could have affected the error. Now I'll try to generate something with HIP SDK 6.5.
I tried generating with HIP SDK 6.5 but I got the same error, although I had everything fine with it before. (maybe it's because I had HIP SDK 6.2 and VS Studio installed before?)

**Comment by sfinktah** [comment]
Well, you're not going to be able to use HIP SDK 6.5 with that confyui-s.bat file.  You'll need something more substantial like this:

```
if not defined ROCM_VERSION set ROCM_VERSION=6.5

set TRITON_OVERRIDE_ARCH=gfx1102

set HIP_PATH=C:\Program Files\AMD\ROCm\%ROCM_VERSION%\
set HIP_PATH_62=%HIP_PATH%
set HIP_PATH_64=%HIP_PATH%
set HIP_PATH_65=%HIP_PATH%
set CC=%HIP_PATH%bin\clang.exe
set CXX=%HIP_PATH%bin\clang++.exe
set CXXFLAGS=-march=native -mtune=native
```

_modified slightly from https://github.com/sfinktah/ComfyUI-Zluda/blob/sfink-hip64/comfyui-s.bat_

**I would highly recommend against playing with HIP SDK 6.4 at this point.** (We don't really have the proper custom HIP SDK modifications for it yet)

HIP SDK 6.2 or 6.5 should both be fine. Ideally 6.2 I guess, since it does support your card, and it makes everything easier for patientx to diagnose issues if people aren't running non-standard stuff.

Either way, run `install-n.bat` again, I recall that is pretty thorough.  Just make sure you have the latest version by running `git pull` from your comfy directory, and double check that cudnn.dll line is there (and most definately not commented).  

If in doubt, you can run `patchzluda-n.bat` after you have run `install-n.bat` which should also have the required cudnn copy commands (again, double check).   

And if doubt, it doesn't hurt to run sfinktah's ever reliable alternative [patchzluda-s.bat](https://github.com/sfinktah/ComfyUI-Zluda/blob/sfink-hip64/patchzluda-s.bat) which is the same, but with prettier colors, and no funny ideas about cudnn.  **But only after running patientx's install-n.bat**

**Comment by zolotov7200** [comment]
Maybe I just shouldn't change my .bat for launching in any way and launch the original one? (except for launch arguments)
I tried to go back to install HIP SDK 6.2 with addon and VS Studio, but it didn't give me any result (didn't change .bat contents).
I guess that leaves me with only one option, which is my .bat for launching, since I was only changing the launch parameters in it before (and also using your patch for SageAttention, which was probably useless without the .bat add-on)

**Comment by sfinktah** [comment]
My patch for sageattention is totally self contained and requires no batch file stuff.

If that was the batch file you always used, then you never had triton working properly.  It might have worked a little, but it wouldn't have handled kijai/torch compile.  You are going to want to have those bits that I pasted earlier in there, no matter what version you are running.

Also, you didn't mention re-running install-n or patchzluda-n.

**Comment by zolotov7200** [comment]
> My patch for sageattention is totally self contained and requires no batch file stuff.

I had another thought, but the translator doesn't always convey them correctly ;)

> re-running install-n

I'm currently doing a clean reinstall of ComfyUI, it's the same thing, right?

After installation I will try to run comfyui-user.bat with a few changes, namely:
`set COMMANDLINE_ARGS=--auto-launch --use-sage-attention --lowvram --cache-none --reserve-vram 0`
`set TRITON_OVERRIDE_ARCH=gfx1102`
If the same error occurs, I will update the post, if not, I will close the issue.

> you never had triton working properly

It's possible, but at least I haven't seen this error before.

**Comment by sfinktah** [comment]
> I'm currently doing a clean reinstall of ComfyUI, it's the same thing, right?

You can certainly try, and as long as that reinstall involves running install-n.bat, and you set those environment variables in your comfy batch file, you should be pretty close/

**Comment by zolotov7200** [comment]
And yes, it finally worked! Most likely comfy-user.bat contained some variables set by me (from comfyui-s) that caused me errors on the sampler.

**Comment by zolotov7200** [comment]
It turns out that the error was related to setting the CFG on the sampler higher than 1 (yes, without changing the workflow, it is stated in the error and there is something like "with CFG higher than 1, a negative promt is needed" (which also didn't work), but I deleted some nodes from the promt and threw positive and negative promt on one WanWrapperVideo Bridge and connected it to the samplers). But how to set the CFG higher than 1 so that such errors do not occur?
That's it, I finally solved the problem by disabling some nodes.
