### ISSUE TITLE
CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by PhoenixGames73** [patientx/ComfyUI-Zluda#357]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

I just recently installed ComfyUi and launched it for the first time. After figuring out some things I tried to generate a simple image to test and that is when I got that error. I am using an RX 6700 XT so I followed the second instruction list downloading HIP SDK 6.2.4 and gfx1031.

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 7
- **Node Type:** CLIPTextEncode
- **Exception Type:** RuntimeError
- **Exception Message:** CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

## Stack Trace

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\execution.py", line 286, in process_inputs
    result = f(**inputs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\nodes.py", line 74, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd.py", line 177, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd.py", line 239, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd1_clip.py", line 689, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd1_clip.py", line 291, in encode
    return self(tokens)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd1_clip.py", line 264, in forward
    outputs = self.transformer(None, attention_mask_model, embeds=embeds, num_tokens=num_tokens, intermediate_output=intermediate_output, final_layer_norm_intermediate=self.layer_norm_hidden_state, dtype=torch.float32, embeds_info=embeds_info)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 155, in forward
    x = self.text_model(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 128, in forward
    x, i = self.encoder(x, mask=mask, intermediate_output=intermediate_output)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 74, in forward
    x = l(x, mask, optimized_attention)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 51, in forward
    x += self.self_attn(self.layer_norm1(x), mask, optimized_attention)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 17, in forward
    q = self.q_proj(x)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\ops.py", line 154, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)

  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\ops.py", line 147, in forward_comfy_cast_weights
    x = torch.nn.functional.linear(input, weight, bias)


## System Information
- **ComfyUI Version:** 0.3.67
- **Arguments:** main.py --auto-launch --use-quad-cross-attention --reserve-vram 0.9
- **OS:** nt
- **Python Version:** 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.7.0+cu118
## Devices

- **Name:** cuda:0 AMD Radeon RX 6700 XT [ZLUDA] : native
  - **Type:** cuda
  - **VRAM Total:** 12868124672
  - **VRAM Free:** 12720963584
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs

2025-10-31T05:55:52.357483 - [START] Security scan2025-10-31T05:55:52.357483 - 
2025-10-31T05:55:53.618730 - [DONE] Security scan2025-10-31T05:55:53.618730 - 
2025-10-31T05:55:53.885730 - ## ComfyUI-Manager: installing dependencies done.2025-10-31T05:55:53.885730 - 
2025-10-31T05:55:53.885730 - ** ComfyUI startup time:2025-10-31T05:55:53.885730 -  2025-10-31T05:55:53.885730 - 2025-10-31 05:55:53.8852025-10-31T05:55:53.886732 - 
2025-10-31T05:55:53.886732 - ** Platform:2025-10-31T05:55:53.886732 -  2025-10-31T05:55:53.886732 - Windows2025-10-31T05:55:53.886732 - 
2025-10-31T05:55:53.886732 - ** Python version:2025-10-31T05:55:53.886732 -  2025-10-31T05:55:53.886732 - 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]2025-10-31T05:55:53.886732 - 
2025-10-31T05:55:53.886732 - ** Python executable:2025-10-31T05:55:53.886732 -  2025-10-31T05:55:53.886732 - E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\Scripts\python.exe2025-10-31T05:55:53.886732 - 
2025-10-31T05:55:53.886732 - ** ComfyUI Path:2025-10-31T05:55:53.886732 -  2025-10-31T05:55:53.886732 - E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda2025-10-31T05:55:53.886732 - 
2025-10-31T05:55:53.887730 - ** ComfyUI Base Folder Path:2025-10-31T05:55:53.887730 -  2025-10-31T05:55:53.887730 - E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda2025-10-31T05:55:53.887730 - 
2025-10-31T05:55:53.887730 - ** User directory:2025-10-31T05:55:53.887730 -  2025-10-31T05:55:53.887730 - E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\user2025-10-31T05:55:53.887730 - 
2025-10-31T05:55:53.887730 - ** ComfyUI-Manager config path:2025-10-31T05:55:53.887730 -  2025-10-31T05:55:53.888730 - E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini2025-10-31T05:55:53.888730 - 
2025-10-31T05:55:53.888730 - ** Log path:2025-10-31T05:55:53.888730 -  2025-10-31T05:55:53.888730 - E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\user\comfyui.log2025-10-31T05:55:53.888730 - 
2025-10-31T05:55:54.969121 - 
Prestartup times for custom nodes:
2025-10-31T05:55:54.969121 -    3.0 seconds: E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
2025-10-31T05:55:54.969121 - 
2025-10-31T05:55:56.439844 - Checkpoint files will always be loaded safely.
2025-10-31T05:55:57.432993 - 
  ::  Checking package versions...2025-10-31T05:55:57.432993 - 
2025-10-31T05:55:57.435993 - Found pydantic: 2.12.3, pydantic-settings: 2.11.02025-10-31T05:55:57.435993 - 
2025-10-31T05:55:57.510997 -   ::  Pydantic packages are compatible, skipping reinstall2025-10-31T05:55:57.510997 - 
2025-10-31T05:55:57.511997 - Installed version of comfyui-frontend-package: 1.28.82025-10-31T05:55:57.511997 - 
2025-10-31T05:55:57.514993 - Installed version of comfyui-workflow-templates: 0.2.42025-10-31T05:55:57.514993 - 
2025-10-31T05:55:57.515994 - Installed version of av: 16.0.12025-10-31T05:55:57.515994 - 
2025-10-31T05:55:57.516995 - Installed version of comfyui-embedded-docs: 0.3.02025-10-31T05:55:57.516995 - 
2025-10-31T05:55:57.516995 -   ::  Package version check complete.2025-10-31T05:55:57.517994 - 
2025-10-31T05:55:57.517994 - 
  ::  ------------------------ ZLUDA -----------------------  ::  2025-10-31T05:55:57.517994 - 
2025-10-31T05:55:57.583553 -   ::  Auto-detecting AMD GPU architecture for Triton...2025-10-31T05:55:57.583553 - 
2025-10-31T05:55:57.583553 -   ::  Detected GPU via Windows registry: AMD Radeon RX 6700 XT2025-10-31T05:55:57.583553 - 
2025-10-31T05:55:57.583553 -   ::  Set TRITON_OVERRIDE_ARCH=gfx10312025-10-31T05:55:57.584551 - 
2025-10-31T05:55:57.584551 -   ::  Triton not installed2025-10-31T05:55:57.584551 - 
2025-10-31T05:55:57.622550 -   ::  Patching ONNX Runtime for ZLUDA — disabling CUDA EP.2025-10-31T05:55:57.622550 - 
2025-10-31T05:55:57.622550 -   ::  Using ZLUDA with device: AMD Radeon RX 6700 XT [ZLUDA]2025-10-31T05:55:57.623549 - 
2025-10-31T05:55:57.623549 -   ::  Applying core ZLUDA patches...2025-10-31T05:55:57.623549 - 
2025-10-31T05:55:57.623549 -   ::  Triton optimizations skipped (not available)2025-10-31T05:55:57.623549 - 
2025-10-31T05:55:57.624549 -   ::  Configuring PyTorch backends...2025-10-31T05:55:57.624549 - 
2025-10-31T05:55:57.624549 -   ::  Disabled CUDA flash attention2025-10-31T05:55:57.624549 - 
2025-10-31T05:55:57.624549 -   ::  Enabled math attention fallback2025-10-31T05:55:57.625549 - 
2025-10-31T05:55:57.625549 -   ::  ZLUDA initialization complete2025-10-31T05:55:57.625549 - 
2025-10-31T05:55:57.625549 -   ::  ------------------------ ZLUDA -----------------------  ::  
2025-10-31T05:55:57.626549 - 
2025-10-31T05:55:58.220383 - Total VRAM 12272 MB, total RAM 65406 MB
2025-10-31T05:55:58.220383 - pytorch version: 2.7.0+cu118
2025-10-31T05:55:58.222383 - Set vram state to: NORMAL_VRAM
2025-10-31T05:55:58.222383 - Device: cuda:0 AMD Radeon RX 6700 XT [ZLUDA] : native
2025-10-31T05:55:58.542387 - Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
2025-10-31T05:56:00.309609 - Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
2025-10-31T05:56:00.309609 - ComfyUI version: 0.3.67
2025-10-31T05:56:00.335608 - ComfyUI frontend version: 1.28.8
2025-10-31T05:56:00.337609 - [Prompt Server] web root: E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\comfyui_frontend_package\static
2025-10-31T05:56:01.247740 - ### Loading: ComfyUI-Manager (V3.37)
2025-10-31T05:56:01.247740 - [ComfyUI-Manager] network_mode: public
2025-10-31T05:56:01.739911 - ### ComfyUI Revision: 5460 [3c90d0ea] | Released on '2025-10-31'
2025-10-31T05:56:02.045910 - 
Import times for custom nodes:
2025-10-31T05:56:02.045910 -    0.0 seconds: E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\custom_nodes\cfz_vae_loader.py
2025-10-31T05:56:02.046911 -    0.0 seconds: E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\custom_nodes\cfz_cudnn.toggle.py
2025-10-31T05:56:02.046911 -    0.0 seconds: E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\custom_nodes\websocket_image_save.py
2025-10-31T05:56:02.046911 -    0.0 seconds: E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\custom_nodes\cfz_patcher.py
2025-10-31T05:56:02.046911 -    0.0 seconds: E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\custom_nodes\CFZ-caching
2025-10-31T05:56:02.046911 -    0.8 seconds: E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
2025-10-31T05:56:02.046911 - 
2025-10-31T05:56:02.157452 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-10-31T05:56:02.177452 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-10-31T05:56:02.240453 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-10-31T05:56:02.345461 - Context impl SQLiteImpl.
2025-10-31T05:56:02.345461 - Will assume non-transactional DDL.
2025-10-31T05:56:02.348460 - No target revision found.
2025-10-31T05:56:02.365461 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-10-31T05:56:02.420460 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-10-31T05:56:02.434460 - Starting server

2025-10-31T05:56:02.435461 - To see the GUI go to: http://127.0.0.1:8188
2025-10-31T05:56:04.695449 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-10-31T05:56:04.699447 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/groupNode.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-10-31T05:56:04.867449 - [CFZ Load] No cache files found2025-10-31T05:56:04.867449 - 
2025-10-31T05:56:04.868448 - [CFZ Load] No cache files found2025-10-31T05:56:04.868448 - 
2025-10-31T05:56:04.973449 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/buttonGroup.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-10-31T05:56:04.980450 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/button.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-10-31T05:56:05.772963 - FETCH ComfyRegistry Data: 5/1032025-10-31T05:56:05.772963 - 
2025-10-31T05:56:09.792041 - FETCH ComfyRegistry Data: 10/1032025-10-31T05:56:09.792041 - 
2025-10-31T05:56:14.355671 - FETCH ComfyRegistry Data: 15/1032025-10-31T05:56:14.355671 - 
2025-10-31T05:56:17.730635 - FETCH ComfyRegistry Data: 20/1032025-10-31T05:56:17.730635 - 
2025-10-31T05:56:21.057941 - FETCH ComfyRegistry Data: 25/1032025-10-31T05:56:21.057941 - 
2025-10-31T05:56:24.404233 - FETCH ComfyRegistry Data: 30/1032025-10-31T05:56:24.404233 - 
2025-10-31T05:56:27.716700 - FETCH ComfyRegistry Data: 35/1032025-10-31T05:56:27.717699 - 
2025-10-31T05:56:31.066189 - FETCH ComfyRegistry Data: 40/1032025-10-31T05:56:31.066189 - 
2025-10-31T05:56:34.336255 - FETCH ComfyRegistry Data: 45/1032025-10-31T05:56:34.336255 - 
2025-10-31T05:56:37.673724 - FETCH ComfyRegistry Data: 50/1032025-10-31T05:56:37.673724 - 
2025-10-31T05:56:41.000922 - FETCH ComfyRegistry Data: 55/1032025-10-31T05:56:41.000922 - 
2025-10-31T05:56:44.670986 - FETCH ComfyRegistry Data: 60/1032025-10-31T05:56:44.671785 - 
2025-10-31T05:56:47.966440 - FETCH ComfyRegistry Data: 65/1032025-10-31T05:56:47.966440 - 
2025-10-31T05:56:51.290997 - FETCH ComfyRegistry Data: 70/1032025-10-31T05:56:51.290997 - 
2025-10-31T05:56:54.584590 - FETCH ComfyRegistry Data: 75/1032025-10-31T05:56:54.584590 - 
2025-10-31T05:56:57.929909 - FETCH ComfyRegistry Data: 80/1032025-10-31T05:56:57.930920 - 
2025-10-31T05:57:01.283016 - FETCH ComfyRegistry Data: 85/1032025-10-31T05:57:01.284016 - 
2025-10-31T05:57:04.615864 - FETCH ComfyRegistry Data: 90/1032025-10-31T05:57:04.615864 - 
2025-10-31T05:57:07.944393 - FETCH ComfyRegistry Data: 95/1032025-10-31T05:57:07.944393 - 
2025-10-31T05:57:11.289125 - FETCH ComfyRegistry Data: 100/1032025-10-31T05:57:11.289125 - 
2025-10-31T05:57:13.720096 - FETCH ComfyRegistry Data [DONE]2025-10-31T05:57:13.720096 - 
2025-10-31T05:57:13.868096 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2025-10-31T05:57:13.889097 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-10-31T05:57:13.889097 - 2025-10-31T05:57:14.137172 -  [DONE]2025-10-31T05:57:14.138172 - 
2025-10-31T05:57:14.209736 - [ComfyUI-Manager] All startup tasks have been completed.
2025-10-31T05:58:14.068434 - got prompt
2025-10-31T05:58:16.057222 - model weight dtype torch.float16, manual cast: None
2025-10-31T05:58:16.058224 - model_type EPS
2025-10-31T05:58:16.628656 - Using split attention in VAE
2025-10-31T05:58:16.629653 - Using split attention in VAE
2025-10-31T05:58:16.782656 - VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
2025-10-31T05:58:16.898657 - CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
2025-10-31T05:58:17.011654 - Requested to load SD1ClipModel
2025-10-31T05:58:17.168659 - loaded completely; 10390.86 MB usable, 235.84 MB loaded, full load: True
2025-10-31T05:58:17.728247 - !!! Exception during processing !!! CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
2025-10-31T05:58:17.731248 - Traceback (most recent call last):
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\execution.py", line 286, in process_inputs
    result = f(**inputs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\nodes.py", line 74, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd.py", line 177, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd.py", line 239, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd1_clip.py", line 689, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd1_clip.py", line 291, in encode
    return self(tokens)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd1_clip.py", line 264, in forward
    outputs = self.transformer(None, attention_mask_model, embeds=embeds, num_tokens=num_tokens, intermediate_output=intermediate_output, final_layer_norm_intermediate=self.layer_norm_hidden_state, dtype=torch.float32, embeds_info=embeds_info)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 155, in forward
    x = self.text_model(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 128, in forward
    x, i = self.encoder(x, mask=mask, intermediate_output=intermediate_output)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 74, in forward
    x = l(x, mask, optimized_attention)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 51, in forward
    x += self.self_attn(self.layer_norm1(x), mask, optimized_attention)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 17, in forward
    q = self.q_proj(x)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\ops.py", line 154, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\ops.py", line 147, in forward_comfy_cast_weights
    x = torch.nn.functional.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

2025-10-31T05:58:17.733248 - Prompt executed in 3.66 seconds
2025-10-31T06:00:02.747802 - got prompt
2025-10-31T06:00:02.755802 - !!! Exception during processing !!! CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
2025-10-31T06:00:02.756805 - Traceback (most recent call last):
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\execution.py", line 286, in process_inputs
    result = f(**inputs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\nodes.py", line 74, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd.py", line 177, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd.py", line 239, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd1_clip.py", line 689, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd1_clip.py", line 291, in encode
    return self(tokens)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\sd1_clip.py", line 264, in forward
    outputs = self.transformer(None, attention_mask_model, embeds=embeds, num_tokens=num_tokens, intermediate_output=intermediate_output, final_layer_norm_intermediate=self.layer_norm_hidden_state, dtype=torch.float32, embeds_info=embeds_info)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 155, in forward
    x = self.text_model(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 128, in forward
    x, i = self.encoder(x, mask=mask, intermediate_output=intermediate_output)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 74, in forward
    x = l(x, mask, optimized_attention)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 51, in forward
    x += self.self_attn(self.layer_norm1(x), mask, optimized_attention)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\clip_model.py", line 17, in forward
    q = self.q_proj(x)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\ops.py", line 154, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "E:\Stable Diffusion\ComphyUI\ComfyUI-Zluda\comfy\ops.py", line 147, in forward_comfy_cast_weights
    x = torch.nn.functional.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

2025-10-31T06:00:02.758801 - Prompt executed in 0.01 seconds


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.

{"id":"2ba0b800-2f13-4f21-b8d6-c6cdb0152cae","revision":0,"last_node_id":16,"last_link_id":10,"nodes":[{"id":7,"type":"CLIPTextEncode","pos":[410,410],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":7,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":5},{"localized_name":"text","name":"text","type":"STRING","widget":{"name":"text"},"link":null}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[6]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.65","Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"],"color":"#223","bgcolor":"#335"},{"id":5,"type":"EmptyLatentImage","pos":[520,690],"size":[315,106],"flags":{},"order":0,"mode":0,"inputs":[{"localized_name":"width","name":"width","type":"INT","widget":{"name":"width"},"link":null},{"localized_name":"height","name":"height","type":"INT","widget":{"name":"height"},"link":null},{"localized_name":"batch_size","name":"batch_size","type":"INT","widget":{"name":"batch_size"},"link":null}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","slot_index":0,"links":[2]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.65","Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]},{"id":14,"type":"MarkdownNote","pos":[1220,780],"size":[470,130],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[],"title":"Note: Output","properties":{},"widgets_values":["Image will auto-save to the `ComfyUI/output` folder. You can also right-click on the `Save Image` node and then use the menu to save the image locally."],"color":"#432","bgcolor":"#653"},{"id":6,"type":"CLIPTextEncode","pos":[411.21649169921875,203.68695068359375],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":6,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":3},{"localized_name":"text","name":"text","type":"STRING","widget":{"name":"text"},"link":null}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[4]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.65","Node name for S&R":"CLIPTextEncode"},"widgets_values":["beautiful scenery nature glass bottle landscape, purple galaxy bottle,"],"color":"#232","bgcolor":"#353"},{"id":15,"type":"MarkdownNote","pos":[400,-70],"size":[440,180],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[],"title":"Note: Prompt","properties":{},"widgets_values":["**Prompts usually have two types:**\n\n* **Positive Prompt:** Tells the model what you *want* to see.\n* **Negative Prompt:** Tells the model what you *don’t want* to see.\n\nThink of it as:<br/>\n👉 Positive = “Do this” <br/>\n👉 Negative = “Don’t do this”\n\n\nDifferent models may interpret prompts differently.<br/>\nSome prefer short, simple phrases; others respond well to detailed descriptions or styles.\nExperiment to see how each model reacts.\n\nAbout SD1.5:<br/>\nStable Diffusion 1.5 is one of the most popular base models.\nIt works best with short, clear prompts and simple concepts, and it has a natural, realistic visual style.\n"],"color":"#432","bgcolor":"#653"},{"id":11,"type":"MarkdownNote","pos":[-370,160],"size":[400,240],"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[],"title":"Note: Model link","properties":{},"widgets_values":["[Tutorial](https://docs.comfy.org/tutorials/basic/text-to-image)\n\n\n## Model link\n\n**checkpoints**\n\n- [v1-5-pruned-emaonly-fp16.safetensors](https://huggingface.co/Comfy-Org/stable-diffusion-v1-5-archive/resolve/main/v1-5-pruned-emaonly-fp16.safetensors?download=true)\n\n\nModel Storage Location\n\n\n📂 ComfyUI/\n├── 📂 models/\n│   └── 📂 checkpoints/\n│          └── v1-5-pruned-emaonly-fp16.safetensors\n\n"],"color":"#432","bgcolor":"#653"},{"id":13,"type":"MarkdownNote","pos":[510,860],"size":[330,150],"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[],"title":"Note: Image size","properties":{},"widgets_values":["Different models are trained based on datasets of different image sizes. This workflow is using Stable Diffusion 1.5, which is trained based on 512x512 datasets. So, it doesn't perform well on large image sizes."],"color":"#432","bgcolor":"#653"},{"id":4,"type":"CheckpointLoaderSimple","pos":[60,200],"size":[315,98],"flags":{},"order":5,"mode":0,"inputs":[{"localized_name":"ckpt_name","name":"ckpt_name","type":"COMBO","widget":{"name":"ckpt_name"},"link":null}],"outputs":[{"localized_name":"MODEL","name":"MODEL","type":"MODEL","slot_index":0,"links":[1]},{"localized_name":"CLIP","name":"CLIP","type":"CLIP","slot_index":1,"links":[3,5]},{"localized_name":"VAE","name":"VAE","type":"VAE","slot_index":2,"links":[8]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.65","Node name for S&R":"CheckpointLoaderSimple","models":[{"name":"v1-5-pruned-emaonly-fp16.safetensors","url":"https://huggingface.co/Comfy-Org/stable-diffusion-v1-5-archive/resolve/main/v1-5-pruned-emaonly-fp16.safetensors?download=true","directory":"checkpoints"}]},"widgets_values":["SD1.5\\v1-5-pruned-emaonly.ckpt"]},{"id":3,"type":"KSampler","pos":[870,170],"size":[315,474],"flags":{},"order":8,"mode":0,"inputs":[{"localized_name":"model","name":"model","type":"MODEL","link":1},{"localized_name":"positive","name":"positive","type":"CONDITIONING","link":4},{"localized_name":"negative","name":"negative","type":"CONDITIONING","link":6},{"localized_name":"latent_image","name":"latent_image","type":"LATENT","link":2},{"localized_name":"seed","name":"seed","type":"INT","widget":{"name":"seed"},"link":null},{"localized_name":"steps","name":"steps","type":"INT","widget":{"name":"steps"},"link":null},{"localized_name":"cfg","name":"cfg","type":"FLOAT","widget":{"name":"cfg"},"link":null},{"localized_name":"sampler_name","name":"sampler_name","type":"COMBO","widget":{"name":"sampler_name"},"link":null},{"localized_name":"scheduler","name":"scheduler","type":"COMBO","widget":{"name":"scheduler"},"link":null},{"localized_name":"denoise","name":"denoise","type":"FLOAT","widget":{"name":"denoise"},"link":null}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","slot_index":0,"links":[7]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.65","Node name for S&R":"KSampler"},"widgets_values":[368038482522568,"randomize",20,8,"euler","normal",1]},{"id":8,"type":"VAEDecode","pos":[975,700],"size":[210,46],"flags":{},"order":9,"mode":0,"inputs":[{"localized_name":"samples","name":"samples","type":"LATENT","link":7},{"localized_name":"vae","name":"vae","type":"VAE","link":8}],"outputs":[{"localized_name":"IMAGE","name":"IMAGE","type":"IMAGE","slot_index":0,"links":[10]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.65","Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":16,"type":"PreviewImage","pos":[1443.5987007232616,268.52940597387317],"size":[140,26],"flags":{},"order":10,"mode":0,"inputs":[{"localized_name":"images","name":"images","type":"IMAGE","link":10}],"outputs":[],"properties":{"cnr_id":"comfy-core","ver":"0.3.67","Node name for S&R":"PreviewImage"}}],"links":[[1,4,0,3,0,"MODEL"],[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[10,8,0,16,0,"IMAGE"]],"groups":[{"id":1,"title":"Step 1 - Load model","bounding":[50,130,335,181.60000610351562],"color":"#3f789e","font_size":24,"flags":{}},{"id":2,"title":"Step 3 - Image size","bounding":[510,620,335,189.60000610351562],"color":"#3f789e","font_size":24,"flags":{}},{"id":3,"title":"Step 2 - Prompt","bounding":[400,130,445.27801513671875,467.2060852050781],"color":"#3f789e","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":0.7773326634696579,"offset":[302.1146389722202,276.92560952419905]},"frontendVersion":"1.27.10","VHS_latentpreview":false,"VHS_latentpreviewrate":0,"VHS_MetadataImage":true,"VHS_KeepIntermediate":true},"version":0.4}


## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

**Comment by PhoenixGames73** [comment]
Used the patchzluda2.bat and used the latest build (v3.9.5 nightly) which got past the original problem. After that I ran into "GET was unable to find an engine to execute this computation" which was fixed by using the CFZ CUDNN Toggle node mentioned in the first troubleshooting guide.
